openshift/ovn-kubernetes

OWNERS
=> Adjust OWNERS file for Red Hat employees

.travis.yml, Dockerfile
Also revert the travis change, it breaks linting and we don't actually need to change any paths from openvswitch to openshift.
@pecameron
=> Add RHEL7 dockerfile from OSE

Dockerfile, dist/images/Dockerfile
SDN-503 Dockerfiles: verify that packages are installed
https://jira.coreos.com/browse/SDN-503
=> Dockerfiles: verify that packages are installed

go-controller/pkg/cni/helper_linux.go
Since we didn't figure out a higher-level approach to this for 4.2, here is a port of https://github.com/openshift/origin/pull/22821 to our build of ovn-kubernetes. This should go away in 4.3.
(This lack of this currently causes an e2e-aws-ovn-kubernetes test failure, `node client cert requests armoring: deny pod's access to /config/master API endpoint`.)
=> Bug 1749131: Block access to MCS and metadata

Dockerfile
=> bug 1752023: images: disable cgo

go-controller/pkg/cluster/gateway_localnet.go
Something is removing the IP address from br-nexthop which of
course makes things go south. Use a giant hammer to add it back.
@squeed @danwinship @JacobTanenbaum
=> gateway/localnet: work around disappearing br-nexthop IP address

go-controller/pkg/cluster/gateway_init_linux_test.go, go-controller/pkg/cluster/gateway_localnet.go
Fixes the unit tests; the race condition with NM doesn't last long so we just need to make sure the address is there for a couple seconds.
=> CARRY: gateway: fix unit tests for br-nexthop IP enforcement

Dockerfile
SDN-611
https://jira.coreos.com/browse/SDN-611
=> OVN: bump to ovs-2.12

dist/templates/ovnkube-db-vip.yaml.j2, dist/templates/ovnkube-db.yaml.j2, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Brings in https://github.com/ovn-org/ovn-kubernetes/pull/908 and two changes to ovnkube.sh that we don't use.
@danwinship @squeed
=> Upstream merge 2019 11 10

Dockerfile
=> Fixes missing oc client during openshift image build

Dockerfile, go-controller/hack/build-go.sh
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/995
This should moot https://github.com/openshift/ovn-kubernetes/pull/75
=> Fix Windows cross-compilation

Dockerfile, go-controller/pkg/cluster/cluster.go, go-controller/pkg/cluster/node_test.go
This reverts commit f21e6316e62acc0d539a9bd3913acde52ee187ec.
It also restores PR111
=> Revert "WIP: test monitor-all fix"

go-controller/hybrid-overlay/pkg/controller/node_linux.go
This reverts commit eebb13497a295c0ed638a649b39a1082ff1ffe3e.
=> Revert "Add flow to route packets to external GW via VXLAN tunnel"

Dockerfile
Mostly for soak testing at this time.
=> Bug 1819876: build: use OVS and OVN 2.13

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1828637
https://bugzilla.redhat.com/show_bug.cgi?id=1823755
=> Bug 1834430: build: require OVN >= 2.13.0-30 for rhbz#1828637 and rhbz#1823755

go-controller/pkg/node/block_mcs.go, go-controller/pkg/node/gateway_localnet.go
=> Bug 1759338: hostnetwork pod can access MCS port 22623 or 22624 on master

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1834838
https://bugzilla.redhat.com/show_bug.cgi?id=1822290
@abhat @jtaleric
=> Bug 1845702: build: require openvswitch2.13 >= 2.13.0-29 or later

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1834838
https://bugzilla.redhat.com/show_bug.cgi?id=1822290
@abhat @jtaleric
=> Bug 1845705: build: require openvswitch2.13 >= 2.13.0-29 or later

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1834838
https://bugzilla.redhat.com/show_bug.cgi?id=1822290
@abhat @jtaleric
=> Bug 1845706: build: require openvswitch2.13 >= 2.13.0-29 or later

Dockerfile
This reverts commit 8f5343d2f7755d262a7a32f3c15b92aa2cd1e9df.
With everything going on last week we added `iputils` twice to our Dockerfile. This reverts my commit for that. 
/assign @dcbw 
=> Revert "Adding arping to OCP ovn-kube image for egress IP"

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
(cherry picked from commit 37d39dc6c2196dc242b45454c8ee4490d4c9dfac)
=> Bug 1858304: Set MTU for br-ext hybrid overlay bridge

Dockerfile
ovn2.13-20.06.2-3.el8fdp
openvswitch2.13-2.13.0-52.el8fdp
=> Bug 1874579: Bump OVN and OVS rpms

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
(cherry picked from commit 37d39dc6c2196dc242b45454c8ee4490d4c9dfac)
=> Bug 1858309: Set MTU for br-ext hybrid overlay bridge

OWNERS
=> Add myself to owners list

README.md, contrib/kind.sh, dist/images/.gitignore, dist/images/Dockerfile, dist/images/Dockerfile.fedora, dist/images/Dockerfile.fedora.dev, dist/images/Dockerfile.ubuntu, dist/images/Dockerfile.ubuntu.arm64, dist/images/daemonset.sh, dist/images/ovndb-raft-functions.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-db-raft.yaml.j2, go-controller/Makefile, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/util/ovs.go, test/e2e/e2e_test.go, test/e2e/go.mod, test/e2e/utils_test.go
Fixes Include:
1. Prefer routing external gateways over hybrid overlay gateways
2. Handling OVN DB corruption and ensuring raft membership
=> Bug 1837953: 9-24-2020 merge

go-controller/pkg/ovndbmanager/ovndbmanager.go
Includes fix for db checker detecting if database is corrupt and removing it.
=> 10 14 2020 merge

Dockerfile
=> Bump OVN to 20.09.0-20

go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go
Backport of:
https://github.com/ovn-org/ovn-kubernetes/pull/1711
https://github.com/ovn-org/ovn-kubernetes/pull/1785
=> Bug 1883917: backport reject acl fixes

Dockerfile
=> Bug 1915981: Dockerfile: add ethtool & conntrack, and change maintainer email to Tim

go-controller/pkg/ovn/egressgw.go
We need to ensure we only add the proper family routes when exgw
annotations are used.
Signed-off-by: Ricardo Carrillo Cruz <ricarril@redhat.com>
=> Bug 1908888: Check IP family for exgws

go-controller/pkg/node/helper_linux.go
We were detecting the default gateway based in the assumption that
the netlink library was populating the de Gw field with it, however,
it turns out that when multipath is enabled that field is empty and
the corresponding information is in the MultiPath field.
Also, in order to obtain the default gateway, we were dumping all
routes filtering by FAMILY_ALL, and iterating on the results to get
the ones we are interested. We can filter directly by the IP Family instead,
to avoid future possibles problems with the FAMILY_ALL interpretation.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1914250
=> Bug 1914250: support multipath to detect default gateway

go-controller/pkg/ovn/egressgw.go
The ovn_cluster_router policy was being removed for a pod anytime an
exgw was deleted. This is incorrect, because a pod may have more than
one exgw configured. The policy should only be removed for a pod if it
no longer has any exgws configured.
Additionally, the policy was being removed for potentially the wrong
node. This patch corrects the node to be the one where the affected pod
lives.
=> Bug 1917605: Fixes deleting exgw pod

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/management-port.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/1772
=> Bug 1890274: Fixes External IP with local gateway mode

Dockerfile
=> Bump OVN to ovn2.13-20.12.0-24.el8fdp

Dockerfile
To fix https://bugzilla.redhat.com/show_bug.cgi?id=1933752
=> Bug 1933752: Bump to ovn2.13-20.09.0-7.el8fdn

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/node/port_claim_test.go
This backports commit https://github.com/ovn-org/ovn-kubernetes/commit/4efbb59969223c4090c572be2c99d7280a871c8e to 4.6
=> Bug 1935691: [release-4.6] Backport port_claim improvement 

go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/subnetallocator/allocator.go
cherry-pick from dual-stack conversion code
=> Bug 1937829: Cherry-pick dual-stack conversion 

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/net.go
=> Bug 1935180: Backport Fix mcast querier

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/types.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/config/utils.go, go-controller/pkg/node/node.go, go-controller/pkg/testing/mock_ls.go, go-controller/pkg/testing/mock_stubs.go, go-controller/pkg/types/const.go, test/e2e/e2e.go
=> 3-24-21 merge

go-controller/pkg/cni/OCP_HACKS.go
Seeing these failures in okd-e2e-gcp-ovn ci:
`ns/e2e-statefulset-6866 pod/ss2-2 node/**************-55cc1-rnmqt-worker-d-z2mdf - 21.94 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ss2-2_e2e-statefulset-6866_9e22f197-9f64-4793-b1e2-ca45d32a1727_0(7d50f2a1f69d75133e3c33a3e5bb343b850c93d9993c6809277ff8fa5fc82148): [e2e-statefulset-6866/ss2-2:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-statefulset-6866/ss2-2 7d50f2a1f69d75133e3c33a3e5bb343b850c93d9993c6809277ff8fa5fc82148] [e2e-statefulset-6866/ss2-2 7d50f2a1f69d75133e3c33a3e5bb343b850c93d9993c6809277ff8fa5fc82148] failed to configure pod interface: could not set …
=> Add wait to iptables commands for OCP Hacks

Dockerfile
=> Dockerfile: bump OVS to openvswitch2.15-2.15.0-2

go-controller/pkg/ovn/gateway_init.go
This adds a commit which should be adding correctness to the management port synchronization. It does not fix the bug mentioned in the title, but it should improve the general fix for what concerns syncing the state w.r.t to this specific OVN-Kubernetes setup. I am however using the bug, as to get the fix in on 4.8 and then back-port both the commit that did fix this issu, and this one: which improves the general fix.  
=> Bug 1930248: Sync management port for an existing node

go-controller/pkg/ovn/egressfirewall_dns.go, test/e2e/e2e.go
Currently when adding EgressFirewalls with 5 or so dnsNames (observed
with 5 dnsNames) it is probable that a deadlock will occur.
thread #1 calls (e *EgressDNS) Add() grabs lock e.lock and calls
signalAdded(dnsName) and continues looping to the next dnsName calling
(e *EgressDNS) Add() grabbing e.lock and trying to write to the channel
thread #2 recieves the signalAdded(dnsName) and is waiting to grab
e.lock in updateEntry for name
thread #1 cannot write to the channel because the channel blocks waiting
for the write and holds e.lock
thread #2 cannot continue with updateEntryForName() because it is wating
for e.lock
Solve this problem by taking the add goroutine out of the long running
update goroutine. By spawning a goroutine for every DNS name the
goroutines can wait until it is there …
=> Bug 1947917: fix deadlock in EgressFirewall DNS code

go-controller/pkg/ovn/pods.go, go-controller/pkg/testing/mock_lsp.go
To prevent port binding ping-pongs between ovn-controllers, if an
ovnkube-node isn't running or hasn't been able to clear the iface-id
for an old instance of a pod, but the pod has been rescheduled,
request the chassis the pod has been scheduled on.
4.7 backport of https://github.com/openshift/ovn-kubernetes/pull/500
=> Bug 1950432: [4.7] pods: bind pod logical switch ports to the node's chassis with requested-chassis

go-controller/pkg/ovn/ovn.go
Currently we require that if you specify an external gateway that corresponds
to a multus network, then you must do so as a pod update to add the exgw
annotations. This is due to the fact that multus will not add the network
attachment definition until after OVN CNI runs, and therefore OVN will not be
able to locate the exgw information. The current workflow is this:
1. Create exgw pod (OVN will add pod, multus will add network attachment def)
2. Once created, edit the pod and annotate it with the exgw annotations that
link to a multus network:
k8s.v1.cni.cncf.io/network-status: "[{\"name\":\"blah\",\"interface\":\"net1\",
\"ips\":[\"172.18.0.4\"],\"mac\":\"62:ff:69:f0:83:03\",\"dns\":{}}]"
k8s.ovn.org/routing-namespaces: exgw
k8s.ovn.org/routing-network: blah
However, we should be able …
=> Bug 1939488: Backport Handle Multus network-status annotations on pod update

Dockerfile
=> Bug 1949240: Bump OVN version in 4.6 to 20.12.0-24

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovn-setup.yaml.j2, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go
This PR back-ports the allow-from-router feature for release-4.7.
=> Bug 1942603: [release-4.7] Allow from router network policy support 

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/ovn.go
This back-ports the changes made to egress firewall to implement it as ACLs instead of logical router policies. See original PR for why this is needed: https://github.com/ovn-org/ovn-kubernetes/pull/1971
=> Bug 1946682: egress firewall as ACLs

go-controller/pkg/node/gateway_shared_intf.go
This activates the same MCS-blocking rules as for local gateway.
=> Bug 1960757: CARRY: block MCS for shared-gateway mode.

go-controller/pkg/ovn/policy.go
When a policy selects many pods, there can be lock contention. This doesn't need to be the case - all the pod creation wants to do is update a hash.
So, instead, take a read lock and use a sync-safe map instead.
Signed-off-by: Casey Callendrello <cdc@redhat.com>
This is a cherry-pick of upstream PR https://github.com/ovn-org/ovn-kubernetes/pull/2228
=> Bug 1961852: policy: reduce lock contention on policy object

Dockerfile
=> Bug 1958375: Bump OVN to 20.12.0-140.el8fdp

OWNERS
OWNERS: add JacobTanenbaum to approvers
primarily so that I can approve CI changes 
=> add JacobTanenbaum to the list of approvers

docs/kind.md, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/util/ovs.go, test/scripts/e2e-kind.sh
Includes:
- batching scale fix
- check_pkt_len action support detection
- ovn-controller cache limiting options
@jcaamano
=> Bug 1973813: 6-21-2021 merge

go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
Cherry-pick `Properly log when hybrid overlay errors out` to 4.7
/assign @dcbw @trozet @sebsoto 
=> [release-4.7] Bug 1940566: Properly log when hybrid overlay errors out

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/ovn.go
This is a new attempt at back-porting https://github.com/openshift/ovn-kubernetes/pull/487 , with an added commit which fixes service connectivity for egress firewall matching pods. 
The cherry-pick did not go cleanly, so please pay attention to that. 
Master commits are:
- https://github.com/openshift/ovn-kubernetes/commit/f18a027078c2bd908197d6cc9281841a0873211d
- https://github.com/openshift/ovn-kubernetes/commit/f1ceb96e3e0faf6e609de8df15e5e6ea6b88c564
- https://github.com/openshift/ovn-kubernetes/commit/5fdc850df5702410af2fceb6b244edca88027f4b
- https://github.com/openshift/ovn-kubernetes/commit/63401b4c4abe057144f8ac5e561d1f6c0c9a546c
**- Description for the …
=> Bug 1972484: egress firewall as ACLs + service connectivity fixes

Dockerfile
=> Bump OVS to openvswitch2.15-2.15.0-28.el8fdp

Dockerfile
=> Bump OVN to ovn21.09-21.09.0-8.el8fdp

Dockerfile
=> Bug 1986440: Bump OVN to ovn21.09-21.09.0-9.el8fdp

Dockerfile
Going to fail for the next 4 hours until the RPM repo mirrors sync...
=> Bug 1989694: Bump OVN to ovn21.09-21.09.0-10.el8fdp

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, test/e2e/e2e.go
=> [release-4.8] Bug 1988487: Fix lgw eip 4.8

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Cherry-picked without problems from: https://github.com/ovn-org/ovn-kubernetes/pull/2300
/assign @abhat @trozet 
=> Bug 1976215: Fix: sync egress IP for missed events on start-up

Dockerfile
- lflow: Refactor OpenFlow snat hairpin flows
https://github.com/ovn-org/ovn/commit/f89a506de2a6b211a8c8865df22c79b863421e3c
https://github.com/ovn-org/ovn/commit/07467cfac499b1d906478c9e9b3d332eaf773566
https://patchwork.ozlabs.org/project/ovn/list/?series=257685&state=*
- ovn-northd: Multiple distributed gateway port support.
https://github.com/ovn-org/ovn/commit/15348b7b806f7a9680606c3e9348708980129949
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
=> Bug 1994069: bump OVN to ovn21.09-21.09.0-13.el8fdp

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/cnismartnic_test.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/utils.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/handler.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/port_group_unit_test.go, go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/logical_switch_port.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/go-ovn/port_group.go, go-controller/vendor/modules.txt
Includes a bunch of scale fixes to make ovnkube-master more efficient at pod handling.
=> Bug 1959352: scale fixes 1

go-controller/pkg/factory/handler.go, go-controller/pkg/metrics/master.go
Backport of upstream https://github.com/ovn-org/ovn-kubernetes/pull/2384
@kedark3
=> Bug 1995816: [4.9] backport "attempting to reduce cardinality in the interest of memory performance"

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1995326
https://bugzilla.redhat.com/show_bug.cgi?id=1995333
@trozet @putnopvut
=> Bug 1997270: bump OVN to ovn21.09-21.09.0-15.el8fdp

go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
release-4.7 backport of #681 
/assign @abhat 
=> [release-4.7] Bug 1997104: fix reserve joinSwitch LRP IPs

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
4.8 back-port of https://github.com/openshift/ovn-kubernetes/pull/655
/assign @dcbw @abhat 
=> [release-4.8] Bug 1994937: Fix: sync egress IP for missed events on start-up

README.md
Improve repo README to replace https://danielmellado.github.io/openshift_sdn_devel_docs/
=> README: Add doc links

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
4.7 backport of #665 
/assign @abhat 
=> [release-4.7] Bug 1997574: Fix: sync egress IP for missed events on start-up

go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
Reverts openshift/ovn-kubernetes#681
=> Bug 1999895: Revert "[release-4.8] fix reserve joinSwitch LRP IPs"

go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
Reverts openshift/ovn-kubernetes#683
=> Bug 1999896: Revert "[release-4.7] fix reserve joinSwitch LRP IPs"

go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go
=> Bug 1998423: kube master don't fail trying to cache same GW LRP IPs as already exist

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
4.6 back-port of #687
/assign @abhat 
=> [release-4.6] Bug 2001980: Fix sync egress IP for missed events on start-up

go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go
Background to this PR:
- #681 fixed a problem w.r.t syncing the join IP for each node upon a ovnkube-master restart
- it however introduced the regression: https://bugzilla.redhat.com/show_bug.cgi?id=1999895
- Hence #706 reverted it. 
- #705 fixed the regression on master
- Hence we now have to revert the revert (#706) and back-port the complete fix #705
/assign @abhat @dcbw  
=> [release-4.8] Bug 2001542: fix reserve joinSwitch LRP IPs 

go-controller/pkg/ovn/egressip_test.go
Removed duplicate command added to fake exec.
=> Fix bad merge on egressip test

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/types.go
(This is a backport of upstream PRs https://github.com/ovn-org/ovn-kubernetes/pull/2479 and https://github.com/ovn-org/ovn-kubernetes/pull/2486)
When logging the result of CNI requests, filter out kubeAuth from the response, since it might contain sensitive information.
Today ovnkube-node logs include the entire response from all CNI requests, which includes the KubeAPIToken from the KubeAPIAuth part of the response. For instance:
> I0909 15:57:37.113983 1081 cni.go:246] [kube-system/coredns-74ff55c5b-rpbwj 78bcab6c1889a04f6e14d83d2a5caf6143f82bdaf162bb543f7c36857755051f] ADD finished CNI request [kube-system/coredns-74ff55c5b-rpbwj 78bcab6c1889a04f6e14d83d2a5caf6143f82bdaf162bb543f7c36857755051f], result "{"Result":{"interfaces":[{"name":"78bcab6c1889a04","mac":"b6:a5:6a:b4:2e:10"},{"name …
=> Bug 1999261: filter out KubeAPIAuth when logging CNI requests

Dockerfile
Includes fix for:
https://bugzilla.redhat.com/show_bug.cgi?id=2006306
=> Bug 2006325: Bump OVN to ovn21.09-21.09.0-19.el8fdp

Dockerfile
Includes performance fixes and memory usage reductions:
ovsdb-data: Deduplicate string atoms. [RH git: 24e7d1140e] (#2006839)
ovsdb-data: Add function to apply diff in-place. [RH git: df0e4bda98] (#2006851)
ovsdb-data: Optimize subtraction of sets. [RH git: 5bace82405] (#2005483)
ovsdb-data: Optimize union of sets. [RH git: e2a4c7d794] (#2005483)
ovsdb: transaction: Use diffs for strong reference counting. [RH git: 85da133eaa] (#2003203)
@dceara @trozet
=> ovs: bump to 2.16.0-15.el8fdp

go-controller/pkg/ovn/pods.go
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/802
=> [release-4.9] Bug 2016945: Update iface-id-ver for existing ports

docs/design/external_traffic_policy.md, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/port_claim_test.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go, test/scripts/e2e-cp.sh
=> [DownstreamMerge] 21-12-9

go-controller/pkg/cni/OCP_HACKS.go
This commit adds support for blocking access from workload pods
to Alibaba cloud platform's metadata service.
=> Block access to metadata service based on platform type

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/types.go
This is a cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/897, after manually fixing all conflicts.
closes #2039282
=> [release-4.7][backport] Bug 2039282: filter out KubeAPIAuth when logging CNI requests

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/datapath.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/ovn.go
https://github.com/ovn-org/ovn-kubernetes/commit/1b94cbb795af5817c7258109642d185bb3c3f07d
Managed to break Hybrid overlay specifically with the creation of the
MAC binding for the HO logical Port since we never actually passed
a valid sbClient to the ho Controller.
Also the unit tests were broken in the sense that we didn't have a test
that ensured we actually created all the needed OVN objects from
scratch, these objects are
The HO Logical Switch Port
The HO Logiacal Router Policy
The HO Mac binding
this commit fixes the above problems and more related to HO
found while fixing the tests
(cherry picked from commit 51f3d5f669595a8a9efd2e2292faefe359e84543)
Conflict in `MasterController struct` since we are missing …
=> Bug 2041830: Fix panic in Hybrid Overlay

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/net_linux.go
1. updating service route correctly
2. removing egress firewalls from join switch on sgw -> local
=> Bug 2036977: Fixes for shared to local gateway migration

.github/workflows/test.yml, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go
=> Bug 2034155: Make egressIPs compatible with ICNI

go-controller/pkg/cni/helper_linux.go
Corrects formatting error in ovsargs.
Fixes: #2726
Signed-off-by: Hareesh Puthalath <hareeshp@nvidia.com>
(cherry picked from commit 2dada25771c6b235651933494449e33abe6ea8d8)
=> Bug 2040540: Fix String formatting error

docs/design/external_traffic_policy.md, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go
Host -> svc (ETP=local) backed by ovn pods
does not work in SGW because we add the DNAT
rule that converts the NP to CIP before it
hits the LB on the GR.
Current flow which is wrong:
1) traffic from host gets DNAT-ed to clusterIP svc using iptables
2) traffic sent to br-ex
3) hits the GR load balancer
4) gets DNAT-ed to the backend pods,
5) depending on if this is on the same node or a different one,
we'll have packet delivered to the pod if its on the same node,
or it passes via geneve tunnel to the destination node where the pod lives.
Technically if the backends are not local to the node, the
request should get rejected. This PR removes the iptable DNAT rule
towards CIP if the traffic is of ETP=local type. Instead it adds
the DNAT rule towards masqueradeIP which we already do for LGW …
=> Bug 2025467: ETP=local,SGW: Add DNAT rule towards 169.254.169.3

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/net_linux.go
updating service route correctly
removing egress firewalls from join switch on sgw -> local
=> Bug 2042516: Fixes for shared to local gateway migration

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/api.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/api_test_model.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go, go-controller/vendor/modules.txt
Backports of:
https://github.com/ovn-org/libovsdb/pull/286
https://github.com/ovn-org/libovsdb/pull/285
https://github.com/ovn-org/libovsdb/pull/280
@squeed
=> Bug 2044680: libovsdb performance and resource consumption fixes

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
=> Bug 2044303: Fix update of CloudPrivateIPConfig

OWNERS
- Add Jaime as reviewer/approver
- Remove Alex
- Alphabetical Order
=> Update project owners

.github/actions/cleanup-action/package-lock.json, .github/workflows/test.yml, go-controller/pkg/config/config.go, go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_retry.go, go-controller/pkg/ovn/policy_test.go
=> Bug 2048538: [DownstreamMerge] 2-14-22

Dockerfile
Pick up the fix for https://bugzilla.redhat.com/show_bug.cgi?id=2049011
=> Bug 2052966: [release-4.8] bump ovn to 20.12.0-193

go-controller/hack/lint.sh, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_retry.go, go-controller/pkg/ovn/policy_test.go
=> Bug 2048538: [DownstreamMerge] 2-22-22

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
(cherry picked from commit 452f286ecfc9344e2ce06e83461ffc17ec84cb61)
=> [release-4.7] Bug 2021224: Add ovn-controller logical flow cache options

go-controller/pkg/ovn/egressip.go
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2691/commits/65e5a2f46501f9796fbe42e6162e6bdf3a47db09
=> [release-4.9] Bug 2034744: Fix egress IP allocator sync

go-controller/pkg/sbdb/bfd.go, go-controller/pkg/sbdb/dhcp_options.go, go-controller/pkg/sbdb/dhcpv6_options.go, go-controller/pkg/sbdb/load_balancer.go, go-controller/pkg/sbdb/logical_flow.go, go-controller/pkg/sbdb/model.go, go-controller/pkg/sbdb/port_binding.go, go-controller/pkg/sbdb/service_monitor.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/info.go
Updates the schema so updates for SBDB will not result in error. Corrects cache update error handling.
=> Bug 2058762: Fixes libovsdb errors + hang

dist/images/Dockerfile.fedora, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
=> Bug 2052975: Downstream merge 07-03-2022

OWNERS
=> [release 4.9] Update project owners

OWNERS
=> [release 4.8] Update project owners

Dockerfile
Includes performance fixes for:
https://bugzilla.redhat.com/show_bug.cgi?id=2058679
https://bugzilla.redhat.com/show_bug.cgi?id=2058681
=> Bug 2058679: Bumps ovn2.13-20.12.0-195.el8fdp

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_retry.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/util/pod_annotation.go, go-controller/pkg/util/pod_annotation_unit_test.go
- Fixes error messages for getting ips from pods on pod add in netpol handlers
- Fixes sorting/duplicate IPs in address sets
- Adds retry mechanism for network policy
=> Bug 2057723: Multiple fixes around Network Policies

Dockerfile, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
=> Bug 2063834: backport 2052975 to 4.10

.github/workflows/test.yml, dist/images/daemonset.sh, go-controller/pkg/kube/kube.go, go-controller/pkg/metrics/master.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/node_annotations.go, test/e2e/e2e.go, test/e2e/util.go
=> Bug 2063321: [DownstreamMerge] Downstream merge 17-03-2022

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/controllers/upgrade/node_upgrade.go, go-controller/pkg/node/node.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/topology_version.go, go-controller/pkg/types/const.go
Pick up https://github.com/ovn-org/ovn-kubernetes/pull/2837
=> Downstream merge 2022-03-22

Dockerfile, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
=> Bug 2063835: backport 2052975 to 4.9

go-controller/pkg/ovn/egressgw.go
Backports https://github.com/ovn-org/ovn-kubernetes/pull/2659 to 4.9
/cc @dcbw @trozet
=> [release-4..9] Bug 2068619: egressgw: fix deadlock due to behavior of RWLock

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
=> Bug 2063836: backport 2052975 to 4.8

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Cherry pick of: https://github.com/openshift/ovn-kubernetes/pull/895
minor conflicts were in 2nd commit:
both modified:   go-controller/pkg/ovn/namespace.go
both modified:   go-controller/pkg/ovn/pods.go
=> Bug 2058683: [4.9z] Multiple ExGW cache validation/improvements

go-controller/pkg/ovn/egressgw.go
=> [release-4.7] Bug 2069247: egressgw: Fix deadlocks

Dockerfile
=> Bug 2047710: Bump OVS version to 2.16.0-57.el8fdp

Dockerfile
Has some DB performance improvements and will be the newest "stable"
FDP release in a week or two.
@jcaamano @tssurya @trozet
=> Dockerfile: bump to OVS 2.17

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Cherry pick of https://github.com/openshift/ovn-kubernetes/pull/972
minor conflicts were in 2nd commit:
both modified: go-controller/pkg/ovn/namespace.go
both modified: go-controller/pkg/ovn/pods.go
=> Bug 2070762: [release-4.8] Multiple ExGW cache validation/improvements

go-controller/pkg/ovndbmanager/ovndbmanager.go
We've seen instances where the migration initially failed because the db
wasn't ready yet. This change adds some retrying to the migration to
handle that situation more gracefully and efficient, as failing this a
couple of times currently results in getting the pod into crashlooop
backoff.
A sample transient error for initial failures looks like e.G. this:
```
F0511 04:31:57.928725       1 ovndbmanager.go:44] NBDB Upgrade failed: %!w(*fmt.wrapError=&{failed to get schema version for NBDB, stderr: "ovsdb-client: transaction returned error: {\"details\":\"get_schema request specifies database OVN_Northbound which is not yet available because it has not completed joining its cluster\",\"error\":\"database not available\"}\n", error: OVN command '/usr/bin/ovsdb-client -t 10 get-schema-version …
```
=> Bug 2090537: OVNDBManager: Retry migrations

go-controller/pkg/ovn/egressip.go
When handling NAT table updates for EgressIPs, the previous implementation
relied on node from egress ip status field to locate logical router.
Additionally, update of NAT rows did not check logical_port field and
ended up with a SNAT row using the wrong logical router.
=> [release-4.9] Bug 2088630: EgressIP NATs are not being cleared correctly from the logical router

go-controller/pkg/ovn/egressip.go
When handling NAT table updates for EgressIPs, the previous implementation
relied on node from egress ip status field to locate logical router.
Additionally, update of NAT rows did not check logical_port field and
ended up with a SNAT row using the wrong logical router.
(cherry picked from commit d00ec784721c107db20facc45c8b9e32455ac609)
=> [release-4.8] Bug 2084110: EgressIP NATs are not being cleared correctly from the logical router

go-controller/pkg/ovn/egressip.go
This commit ensures node name is added into EgressIPStatusItem so that
executeCloudPrivateIPConfigOps removes the egress ip from cloud config
store even though assignment didn't actually happen on the node.
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/1af0a7bee7ab2b9295450736866c91c001d4965a)
=> Bug 2073378: Add node name into egress ip status for the removal

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/gateway.go, go-controller/vendor/github.com/safchain/ethtool/.travis.yml, go-controller/vendor/github.com/safchain/ethtool/ethtool.go, go-controller/vendor/github.com/safchain/ethtool/ethtool_cmd.go, go-controller/vendor/github.com/safchain/ethtool/ethtool_msglvl.go, go-controller/vendor/modules.txt
Cherry-picked from https://github.com/ovn-org/ovn-kubernetes/pull/3033
/cc
/hold
=> Bug 2085089: Add support for enabling UDP packet aggregation on veth interfaces

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/ovn/master.go
When the elected master pod is forced to exit, release
leader election lock so other ovnkube-master can become
the new leader.
(clean backport)
(cherry picked from commit c5ec55f101acf28bb1eeec4e63b6dad0e73cb5fb)
=> Bug 2089807: Release Leader election lock on errors

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
EIP handler uses logicalPortCache for getting pod's
portInfo. Since cache removes entries only 60 seconds
after deletion, its possible that when pod is recreated
with the same name within the 60seconds timer, stale
info gets used to create SNATs and reroutes for the eip pods
(cherry picked from commit 13f3f3f9f11ba9e28b9c824e0d34f40c064a6638)
Clean Cherry Pick
=> Bug 2097243: Fix egressips for pods recreated with same name

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Not clean cherry-pick. I included some fixes from Cathy's PR's that will be useful in 4.10.
All conflicts are outlined in each of the commits if any.
=> [release-4.10] Bug 2105276: Fix panics in DestroyNetworkPolicy if policy is nil

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/uuidset.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/api.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/condition.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/doc.go, go-controller/vendor/github.com/ovn-org/libovsdb/model/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/set.go, go-controller/vendor/modules.txt
Also includes some test case fixes. Minor conflicts while backporting.
=> Bug 2099680: [release-4.10] libovsdb fixes for empty values

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/iptables.go
=> [release-4.11] Bug 2106855: Append the SNAT rule in management chain

dist/images/daemonset.sh, go-controller/hack/build-go.sh, go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/controller/overlay_windows.go, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck_test.go, go-controller/pkg/node/management-port_dpu_test.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/management-port_test.go, go-controller/pkg/node/node_test.go, go-controller/pkg/node/port_claim_test.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/policy.go, test/e2e/external_gateways.go
commit owners: /cc @andreaskaris @dceara @maiqueb @npinaeva @dcbw 
@trozet for approve
=> Bug 2111534: Downstream Merge: 27-07-2022

Dockerfile.base
=> Fix ovn version in Dockerfile.base

go-controller/cmd/ovn-kube-util/app/ovs-exporter.go, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/mocks/gauge.go, go-controller/pkg/metrics/ovs.go, go-controller/pkg/metrics/ovs_test.go, go-controller/pkg/metrics/ovs_windows.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_go115.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_pre_go115.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go, go-controller/vendor/modules.txt
Includes a bunch of fixes around OVS metrics and exposing+exporting them
=> Bug 2111588: [release-4.10] export OVS metrics

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Backports of upstream PRs https://github.com/ovn-org/ovn-kubernetes/pull/3085 and part of https://github.com/ovn-org/ovn-kubernetes/pull/3057
@trozet @rook
=> [release-4.11] Bug 2115481: master: don't list node pods on add/update unless necessary

go-controller/pkg/node/gateway_shared_intf.go
When service is deleted, we were removing the conntrack
entries before removing the flows/iptable rules. It's
safer to do the reverse so that in the nano second interim
the conntrack entries don't get recreated before the rules/flows
get deleted.
(cherry picked from commit 58b23ea)
(cherry picked from commit 525e7f1)
(cherry picked from commit bedef57)
Conflicts from 4.10 since ETP isn't present in 4.9
(cherry picked from commit 4cdb37647cfb221648be9896f47ae198ee653411)
CLEAN PICK from https://github.com/openshift/ovn-kubernetes/pull/1220
=> [release-4.8] Bug 2111557: Remove conntrack entries after rules

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Initially when the commit to cleanup ACLs was done in https://github.com/ovn-org/ovn-kubernetes/pull/3038 I had assumed that ACL names weren't truncated to fit the 63 char length and thought they were like other fields. Based on that assumption there were two places in code where I used a predicate match based on acl names which was plain stupidity. This PR fixes that:
1) When the arp && arp || nd bug was being cleaned up, I was trying to be extra careful in matching on old exp: "arp" and the acl name. I deleted the second part of that logic since there can be cases where the entire suffix is missing like when the namespace is 63 chars. So let us stick to matching on acl.Match alone
2) When the deny default ACL duplicates per namespace were being updated - again I was matching on ACL …
=> OCPBUGS-1705: Don't use ACL names ever!

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
Reported-at: https://issues.redhat.com/browse/SDN-3573
(cherry picked from commit 1598b332c066308c13976fd3953357d791c1767b)
=> OCPBUGS-2826: ovnkube-trace: Fix ofproto/trace for IPv6

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
(cherry picked from commit 816e30a1fbb5beb8b20fe3e96906285762dd8eb6)
CLEAN PICK, no conflicts.
/cc @bn222
=> OCPBUGS-2222: Don't add ITP specific gw setup for DPU mode

go-controller/pkg/ovn/acl.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/port_cache.go, go-controller/pkg/syncmap/syncmap.go
cherry-pick for https://github.com/openshift/ovn-kubernetes/pull/1323
=> OCPBUGS-3075: [release-4.12]  Fix netpol races

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
Clean cherry pick of https://github.com/ovn-org/ovn-kubernetes/pull/3224
=> OCPBUGS-298: Adapt ovnkube-trace to work with external controlplane

go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/ovn/hybrid.go, go-controller/pkg/ovn/hybrid_test.go
=> OCPBUGS-3292: downstream windows fixes 

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/ovn/controller/egress_services/egress_services_service.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/pod_annotation.go
Cherry picked from commit dbe0a9137698088b0516acdafba9e38a9853d699
Merge conflicts:
- pkg/node/gateway_shared_intf.go
- pkg/node/node.go
- pkg/ovn/egressgw.go
=> OCPBUGS-3658: [release-4.12] Support proper parsing of IPs with leading zeros

go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>
(cherry picked from commit d2ca5d6c32ad6ca1e7de4f9a9ae91598a36bd738)
fixes #OCPBUGS-3871
**can go in after https://github.com/openshift/ovn-kubernetes/pull/1381 merges**
=> [release-4.12] OCPBUGS-3871: Ignore addresses in masquerade subnet when retrieving gateway IPs

Dockerfile, Dockerfile.base
Cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1403 see 1403 for the changes that we are bringing in.
=> OCPBUGS-4356: Bump OVN to 22.09.0-22

go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/utils.go
This is a cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2327 which never made it to 4.8.
/assign @dcbw
=> [release-4.8] OCPBUGS-3554: services: log errors and don't panic if the service doesn't exist

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/pods.go
=> Bug 2115872: Fix unit-test failures in 4.10

go-controller/hybrid-overlay/pkg/controller/master_test.go
=> OCPBUGS-5040: [release-4.10] Fix hybrid overlay unit tests

Dockerfile.base
This is to get the bug fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2041746 and component templates for LB performance optimizations.
See https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2311925 for changelog.
=> Bug 2041746: Bump OVN to 22.12.0-4

go-controller/pkg/libovsdbops/lbgroup.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/1497
=> OCPBUGS-6813: [release-4.11] Ensure loadbalancer cleanup doesn't fail

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Clean cherry-pick.
Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384
=> OCPBUGS-6823: [release-4.12] Fix Egress FW ACL rules in dualstack mode

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/network-controller-manager/network_controller_manager.go, go-controller/pkg/ovn/controller/egress_services/egress_services_node.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Brings in the fixes for https://issues.redhat.com/browse/OCPBUGS-6953 and https://issues.redhat.com/browse/OCPBUGS-6955
tagging commit owners @pperiyasamy @dcbw
=> OCPBUGS-6953, OCPBUGS-6955: [Downstream Merge 6th Feb 2023]

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Clean cherry-pick.
Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384
=> OCPBUGS-7010: [release-4.11] Fix Egress FW ACL rules in dualstack mode

Dockerfile.base.rhel9, Dockerfile.microshift.rhel9, Dockerfile.rhel9
Needs to go in before we can actually build the parallel images via https://github.com/openshift/release/pull/36182
=> Add RHEL9 image Dockerfiles

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Clean cherry-pick.
Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384
=> OCPBUGS-7012: [release-4.10] Fix Egress FW ACL rules in dualstack mode

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/chassis.go, go-controller/pkg/libovsdbops/chassis_test.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/uuidset.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/monitor.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/database.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/errors.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/mutate.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/transaction.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go, go-controller/vendor/modules.txt
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3399
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1510
=> [release-4.12] OCPBUGS-7230: Delete IGMP Groups when deleting stale chassis

Dockerfile, Dockerfile.base, Dockerfile.base.rhel9, Dockerfile.rhel9
=> iptables package is missing in microshift image

go-controller/pkg/node/gateway_shared_intf.go
This PR fixes two traffic flows:
1) podCIDR to svcCIDR:unexposedPort. This flow currently sends the packets towards br-ex in both gateway modes since OVN LB's won't DNAT and OVN doesn't know what to do then other than to send these packets out. However the argument here is svcCIDR is a private range, these packets shouldn't be sent outside. Hence like SDN let's drop them.
2) nodeCIDR to svcCIDR:unexposedPort. Same as above.
Fix: Add a new flow at 105 priority right above the default 100 priority flow (that sends the pkt out to primary interface if coming from OVN) which will drop it instead of sending it out the primary interface.
cookie=0xdeff105, duration=7804.947s, table=0, n_packets=18, n_bytes=1332, idle_age=6984, priority=105,ip,in_port=2,nw_dst=10.96.0.0/16 actions=drop …
=> [release-4.10] OCPBUGS-6641: Drop in-cluster traffic towards svcCIDR at wrong port

go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of:
- https://github.com/ovn-org/ovn-kubernetes/pull/3433
=> OCPBUGS-8741: [release-4.13] Handle Completed pods deletion

go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/node.go
MetricResourceRetryFailuresCount metric is registered in NetworkControllerManager and Node modes. When both are specified, the second registration fails with the following error:
panic: duplicate metrics collector registration attempted goroutine 234 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x1e1a662?, {0xc000e35620?, 0x1, 0x15?})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/github.com/prometheus/client_golang/prometheus/registry.go:178
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.RegisterMasterFunctional() …
=> OCPBUGS-10251: fix duplicated metric registration

go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
backport of https://github.com/ovn-org/ovn-kubernetes/pull/3449 (clean!)
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1574
=> OCPBUGS-10796: [release-4.13] Egress firewall fix retry

contrib/kind.sh, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/network-controller-manager/network_controller_manager.go, go-controller/pkg/network-controller-manager/node_network_controller_manager.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/node/node_ip_handler_linux_test.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/namespace_test.go
/assign @bn222 @jordigilh @trozet 
PTAL and attach appropriate bugs if any
=> OCPBUGS-10889, OCPBUGS-8473: Downstream Merge [27-mar-2023]

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/batching/batch.go, go-controller/pkg/util/batching/batch_test.go
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3463
downstream https://github.com/openshift/ovn-kubernetes/pull/1574
clean cherry-pick
=> OCPBUGS-10801: [release-4.13] Batch potentially big transaction on egress firewall ACLs migration

.github/actions/cleanup-action/package-lock.json, go-controller/pkg/libovsdbops/db_object_types.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/pod_selector_address_set_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, test/e2e/e2e.go
=> OCPBUGS-10839, OCPBUGS-10962: [DownstreamMerge] 28 March 2023

go-controller/pkg/ovn/egressfirewall.go
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3508
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1611
no conflicts
=> OCPBUGS-11022: [release-4.13] Fix node update handling for egressfirewall

go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
4.11 Backport of 
- https://github.com/openshift/ovn-kubernetes/pull/1581
Solved conflicts due to file move:
- `go-controller/pkg/ovn/obj_retry.go` -> `go-controller/pkg/ovn/obj_retry_master.go`
=> OCPBUGS-11035: [release-4.11] Handle Completed pods deletion

go-controller/pkg/libovsdbops/db_object_types.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/pod_selector_address_set_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, test/e2e/e2e.go
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3500
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1611
no conflicts
=> OCPBUGS-11023: [release-4.13] Update hairpinning ACLs for network policy

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/node/base_node_network_controller_dpu_test.go, go-controller/pkg/ovn/policy.go, test/e2e/static_pods.go
Clean backport of https://github.com/ovn-org/ovn-kubernetes/pull/3347
=> OCPBUGS-11511: [release-4.13] static pod creation

go-controller/pkg/ovn/pods.go
starting with release-4.12 it was possible for nodes to use any address in there subnet for the hybridOverlay distributed router IP. However the ICNIv1 pods are still using only the .3 address for the hybrid Overlay router IP.
This fix queries the node for the correct Hybrid Overlay Distributed Router IP on pod creation and startup
=> [release-4.12] OCPBUGS-8226: fix hybridOverlay DRIP in ICNIv1 pods

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/acl_test.go, go-controller/pkg/libovsdbops/portgroup.go
=> OCPBUGS-11447: [release-4.13] Delete equivalent ACLs when searching by predicate.

go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
=> OCPBUGS-12971:Fix bug that resulted in routes not be restored to a new vnic

go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/ovn/controller/services/loadbalancer.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1652
no conflicts
=> OCPBUGS-12725: [release-4.13] Use loadbalancer.Name as client index

go-controller/pkg/node/healthcheck_service.go
There is a race condition observed when the
endpointslice is added before the service.
We will not pass
https://github.com/ovn-org/ovn-kubernetes/blob/e7a92dbdab7d2f0c056ae2c6e549140c1809c7c0/go-controller/pkg/node/healthcheck_service.go#L131 this check and hence will not call `syncEndPointSlices` since service doesn't exist yet. Later when we do
AddService, we were not calling syncEndpoints and so we end up in a situation where the localEndpoints count is not updated.
This PR fixes that by moving the logic to call syncEndpoints to AddService. In the reverse case of endpointslice being added after the service, its possible we call the syncEndpoints from two places - both AddService and AddEndpointSlice, but better to be functionally correct and avoid race before worrying about …
=> OCPBUGS-6013: Call SyncEndpoints from AddService

go-controller/pkg/node/healthcheck_service.go
There is a race condition observed when the
endpointslice is added before the service.
We will not pass
https://github.com/ovn-org/ovn-kubernetes/blob/e7a92dbdab7d2f0c056ae2c6e549140c1809c7c0/go-controller/pkg/node/healthcheck_service.go#L131 this check and hence will not call `syncEndPointSlices` since service doesn't exist yet. Later when we do
AddService, we were not calling syncEndpoints and so we end up in a situation where the localEndpoints count is not updated.
This PR fixes that by moving the logic to call syncEndpoints to AddService. In the reverse case of endpointslice being added after the service, its possible we call the syncEndpoints from two places - both AddService and AddEndpointSlice, but better to be functionally correct and avoid race before worrying about …
=> OCPBUGS-13598: Call SyncEndpoints from AddService

go-controller/pkg/node/healthcheck_service.go
There is a race condition observed when the
endpointslice is added before the service.
We will not pass
https://github.com/ovn-org/ovn-kubernetes/blob/e7a92dbdab7d2f0c056ae2c6e549140c1809c7c0/go-controller/pkg/node/healthcheck_service.go#L131 this check and hence will not call `syncEndPointSlices` since service doesn't exist yet. Later when we do
AddService, we were not calling syncEndpoints and so we end up in a situation where the localEndpoints count is not updated.
This PR fixes that by moving the logic to call syncEndpoints to AddService. In the reverse case of endpointslice being added after the service, its possible we call the syncEndpoints from two places - both AddService and AddEndpointSlice, but better to be functionally correct and avoid race before worrying about …
=> OCPBUGS-13599: Call SyncEndpoints from AddService

go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go, go-controller/pkg/ovn/controller/egress_services/egress_services_service.go, go-controller/pkg/ovn/egressservices_test.go, go-controller/pkg/util/service_annotations.go, go-controller/pkg/util/service_annotations_test.go
clean cherry-picks of:
50fb2b176c14a0b4599e6ac996e4da56278bbab3
faecf4e70970efe86f67d8020f1b9e9e14ac6ad2
=> OCPBUGS-7439: [release-4.12]: Egress Service: Fix nodeSelector parsing

FAQ.md, README.md, dist/images/ovnkube.sh, dist/templates/ovnkube-monitor.yaml.j2, dist/templates/ovnkube-single-node-zone.yaml.j2, dist/templates/ovnkube-zone-controller.yaml.j2, docs/ha.md, go-controller/README.md, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/config/config.go, go-controller/pkg/factory/factory.go, go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go, go-controller/pkg/network-controller-manager/network_controller_manager.go, go-controller/pkg/network-controller-manager/network_controller_manager_suite_test.go, go-controller/pkg/ovn/base_network_controller_policy.go, go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/util/kube.go, test/e2e/unidling.go, test/e2e/util.go
=> OCPBUGS-14632: [DownstreamMerge] 30 jun 23

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/1726/commits/198c316a17ce58b2530d64670e067e9cc98c8264
upstream https://github.com/ovn-org/ovn-kubernetes/pull/3686
minor conflicts that were auto-resolved
=> OCPBUGS-15585: [release-4.13] Fix egressFirewall create error handling

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/util/kube.go
Manual cherry-pick of 4.12 commit c3fbfed12bca5f55682ecb1b5461a4b91c5d7649
No conflicts. 
(cherry picked from commit 7b88e0acbfa7041ad056d32f7b0169565b44f874)
(cherry picked from commit cd99b41e441a917e51f983f69d34578167293395)
(cherry picked from commit c3fbfed12bca5f55682ecb1b5461a4b91c5d7649)
=> [release-4.11] OCPBUGS-16003: Fix stale SNAT entries for completed pods

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL9-built shim on a RHEL8 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL8 shim into a special location …
=> Dockerfile: build both RHEL8 and RHEL9 shims

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/1733
adds unit test fix from https://github.com/openshift/ovn-kubernetes/pull/1745
=> OCPBUGS-15719: [relase-4.12] Fix egressFirewall create error handling

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL7 shim into a special location …
=> [release-4.9] OCPBUGS-15865: Dockerfile: build both RHEL7 and RHEL8 shims

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL7 shim into a special location …
=> [release-4.7] OCPBUGS-16209: Dockerfile: build both RHEL7 and RHEL8 shims

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL7 shim into a special location …
=> [release-4.6] OCPBUGS-16210: Dockerfile: build both RHEL7 and RHEL8 shims

go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/util/kube.go
Fixes https://issues.redhat.com/browse/OCPBUGS-16336
~~~
git cherry-pick -x 40199eed08d999e760deba3d09a1125a09c8624b
git cherry-pick -x 0111e1faec20d16505a110449966273b430b7ad1
~~~
a)  Conflicts in pkg/node/gateway_shared_intf.go require  40199eed08d999e760deba3d09a1125a09c8624b, therefore I cherry-picked that one as well
b) /development/ovn-kubernetes/go-controller/pkg/node/gateway_iptables.go
Minor conflict on comment only at:
~~~
491 //        if !svcHasLocalHostNetEndPnt and svcTypeIsITPLocal, rule that marks clusterIP traffic to steer it to ovn-k8s-mp0 is added.
492 //                                                                                                                      
>>493 <<<<<<< HEAD …
=> [release-4.12] OCPBUGS-16336: Backport support AllocateLoadBalancerNodePortsFalse 

go-controller/pkg/factory/factory.go, go-controller/pkg/libovsdb/ops/chassis.go, go-controller/pkg/libovsdb/ops/db_object_types.go, go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go, go-controller/pkg/ovn/controller/apbroute/master_controller.go, go-controller/pkg/ovn/controller/apbroute/network_client.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/external_gateway_apb_test.go, go-controller/pkg/ovn/namespace_test.go
Includes the fix for azure pdb-new disruption.
=> [DownstreamMerge] 8-1-23

go-controller/pkg/ovn/gateway_init.go
No conflicts in cherry-picks 
Backporting to 4.13 to resolve https://issues.redhat.com//browse/OCPBUGS-11567 and https://issues.redhat.com/browse/OCPBUGS-13863
=> [release-4.13] OCPBUGS-13175:Check the status of a pod before trying to get its ip

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/clustermanager/clustermanager.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/metrics/cluster_manager.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/default_node_network_controller_test.go
=> OCPBUGS-17666: Downstream Merge august 15th 2023

go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/retry/obj_retry.go
=> OCPBUGS-17910: Emit node events only when retry failure

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, dist/templates/ovnkube-single-node-zone.yaml.j2, dist/templates/ovnkube-zone-controller.yaml.j2, go-controller/pkg/ovn/zone_interconnect/chassis_handler.go, go-controller/pkg/ovn/zone_interconnect/chassis_handler_test.go
Clean cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3851.
=> OCPBUGS-18110: Fix encap port configuration for remote chassis

go-controller/pkg/ovn/base_network_controller_namespace.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pod_selector_address_set.go, go-controller/pkg/util/multi_network.go, go-controller/pkg/util/pod_annotation.go
Includes critical performance fixes for 4.14.
=> OCPBUGS-17773: Perf increases to pod deletion

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, test/e2e/pod.go, test/e2e/service.go
=> OCPBUGS-18467: Fix OVN SNATing on GR by enabling gateway_mtu on rtoe port of GR

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, test/e2e/pod.go, test/e2e/service.go
=> OCPBUGS-18585: Fix OVN SNATing on GR by enabling gateway_mtu on rtoe port of GR

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, test/e2e/pod.go
minor conflict outlined in 1st commit.
=> OCPBUGS-18586: Fix OVN SNATing on GR by enabling gateway_mtu on rtoe port of GR

Dockerfile
=> Add ovnkube-identity binary to the downstream image

.github/workflows/test.yml, .github/workflows/test_periodic.yml, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/linkmanager/link_network_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovnwebhook/nodeadmission.go, go-controller/pkg/ovnwebhook/nodeadmission_test.go, go-controller/pkg/util/node_annotations.go
=> OCPBUGS-19792,OCPBUGS-19836,OCPBUGS-18162: [DownstreamMerge] 9-27-23

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/obj_retry_node.go, go-controller/pkg/ovn/controller/apbroute/external_controller.go, go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go, go-controller/pkg/ovn/controller/apbroute/master_controller.go, go-controller/pkg/ovn/controller/apbroute/network_client.go, go-controller/pkg/ovn/controller/apbroute/node_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/syncmap/syncmap.go, test/e2e/external_gateways.go
CLEAN PICK
FYI: @jordigilh @npinaeva 
=> OCPBUGS-18317: DownStream Merge: 28th-September-2023

go-controller/pkg/ovn/pods.go
we need to ensure that we only call allocateHybridOverlayDRIP() in syncPods() when there is an existing hybrid overlay distributed router ip address on the node.
the initial allocation of the hybrid overlay distributed router ip should be made during the call to allocateHybridOverlayDRIP() during the addUpdateNodeEvent(). The call to allocateHybridOverlayDRIP() is in syncPods() to ensure that on restart the annotated hybrid overlay distributed router ip is allocated before processing pod events so it is reserved. without the check for the presence of the annotation there is a good chance that the syncPods() will call allocateHybridOverlayDRIP() with a stale node object and cause a reallocation of the hybrid overlay distributed router ip without changing associated the MAC address or …
=> [release-4.12] OCPBUGS-20241: fix race condition in hybrid overlay DRIP alloc

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/util/net_linux.go, go-controller/vendor/k8s.io/client-go/informers/factory.go
Really just pulls in https://github.com/ovn-org/ovn-kubernetes/pull/4012 and an improvement related to https://github.com/openshift/machine-config-operator/pull/4040
=> OCPBUGS-24014: Downstream merge 28th November 2023

Dockerfile.base
=> [release-4.12] OCPBUGS-22091: Bump OVN to 23.06.1-39.el8fdp

go-controller/pkg/clustermanager/zone_cluster_controller.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/node_annotations.go, test/e2e/service.go, test/e2e/util.go
=> OCPBUGS-24350: [release-4.14] fixes MTU configuration on gateway router

contrib/kind.sh, dist/images/ovnkube.sh, go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/metrics/ovs.go, go-controller/pkg/ovn/base_network_controller_namespace.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/pods_test.go
=> OCPBUGS-25394,SDN-4194,OCPBUGS-24055: [DownstreamMerge] 14 Dec 2023

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Clean cherry pick from commit db4aaf417af4df9ffa587482d5b2e4b86e53418b (via https://github.com/openshift/ovn-kubernetes/pull/1990)
Resolved an issue where the Egress IP deletion handler misidentified affected pods, leading to unintended leaks of OVN logical router policies and SNATs. This occurred in scenarios with matchExpressions that only excluded keys and values.
=> [release-4.15] OCPBUGS-25486: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

.github/workflows/test.yml, CODEOWNERS, dist/images/Dockerfile.fedora, go-controller/pkg/config/config.go, go-controller/pkg/informer/informer_test.go, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/egress_service_test.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/linkmanager/link_network_manager.go, go-controller/pkg/node/linkmanager/link_network_manager_test.go, go-controller/pkg/node/openflow_manager.go, go-controller/pkg/util/ovs.go, test/e2e/go.mod, test/e2e/node_ip_mac_migration.go, test/e2e/service.go, test/scripts/e2e-cp.sh
@flavio-fernandes @tssurya FYI
=> OCPBUGS-18716: [DownstreamMerge] 1-5-24

go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, test/e2e/service.go
Manual cherry-pick of 4.14 commits bd40c034a3ce87442fd24dd61925e88a0788f63a and a747d8e89a7e60c684a26fe570c46650bc91eed4. No conflicts.
=> [release-4.13] OCPBUGS-25923: Forward ICMP packets to OVN loadbalancer

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2003
/assign flavio-fernandes
=> [release-4.13] OCPBUGS-26242: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
This is a clean cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2011
=> [release-4.12] OCPBUGS-26243: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go, go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync_test.go
delete all acls that were not synced since they should be stale. Add unit test for a specific multicast leftover acl that was a result of libovsdb migration.
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
(cherry picked from commit 469e752fc8adc105fc23b061d9405b91e559b496)
=> OCPBUGS-25081: Update ACL syncer: make default deny acls filter more strict,

go-controller/pkg/node/gateway_shared_intf.go
(cherry picked from commit 44a7018ed736f93cf8d1c2844559fce583252a09) (cherry picked from commit c7f9b9953b195151a249757b7379fb7b020accfc)
=> OCPBUGS-24419: OVNK/GW: Ignore headless services in syncServices

go-controller/pkg/node/gateway_shared_intf.go
(cherry picked from commit 44a7018ed736f93cf8d1c2844559fce583252a09) (cherry picked from commit c7f9b9953b195151a249757b7379fb7b020accfc) (cherry picked from commit 804b7b5a6cb526725643c11f377d1ad704f4ddac)
=> OCPBUGS-24420: OVNK/GW: Ignore headless services in syncServices

.github/workflows/test.yml, Dockerfile.base, README.md, community-meeting-info.md, contrib/kind.sh, dist/images/Dockerfile.fedora, dist/images/daemonset.sh, dist/templates/ovnkube-single-node-zone.yaml.j2, docs/multi-homing.md, go-controller/pkg/clustermanager/egressip_controller.go, go-controller/pkg/clustermanager/egressip_controller_test.go, go-controller/pkg/clustermanager/egressip_event_handler.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/controller/services/lb_config.go, go-controller/pkg/ovn/egressqos.go, go-controller/pkg/ovn/egressqos_test.go, go-controller/pkg/ovn/hybrid.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, tasks.md, test/e2e/egressip.go, test/e2e/service.go
PTAL and add your bug number to the title if necessary :) 
@andreaskaris @abhat @jcaamano @oribon @maiqueb
=> OCPBUGS-23430,OCPBUGS-24363,OCPBUGS-27211,OCPBUGS-26023: [DownstreamMerge] Merge 1-16-24

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/util.go, test/e2e/service.go, test/e2e/util.go
Some minor conflicts, mainly in the tests.
=> OCPBUGS-26700: [release-4.12] fixes MTU configuration on gateway router

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/clustermanager/egressservice/egressservice_cluster.go, go-controller/pkg/controller/controller.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/controllers/egressservice/egressservice_node.go, go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go, go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go, go-controller/pkg/ovn/hybrid_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/sync.go
=> OCPBUGS-20336,OCPBUGS-28558: [DownstreamMerge] 7 Feb 2024

.github/workflows/test.yml, go-controller/pkg/ovn/base_network_controller.go
=> OCPBUGS-27853: [DownstreamMerge] 9 Feb 2024 

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/4109
d/s merge https://github.com/openshift/ovn-kubernetes/pull/2057
=> [release-4.15] OCPBUGS-29185: Wait for ovnkube controller to start before checking result error.

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go, test/e2e/multihoming.go, test/e2e/multihoming_utils.go, test/e2e/service.go
cc @jcaamano @kyrtapz @maiqueb @oribon @tssurya
=> OCPBUGS-28742, OCPBUGS-17207: Downstream Merge 22nd Feb 2024

Dockerfile
This reverts commit 2f51c186ff5adcdf4fe4f94486469af6b67b598d.
Reverts #2083, RHEL8 layers are still needed for rhel8 workers
run periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-workers-rhel8
OCPBUGS-31557: Revert "Remove unnecessary rhel8 build layer"
=> OCPBUGS-31557: Revert "Remove unnecessary rhel8 build layer"

go-controller/pkg/util/kube.go
clean cherry-pick of 23c8e0cd55bd04b4f4711c789f1e556d55031c47
=> [release-4.15] OCPBUGS-31081: Periodically check the ovnkube-node certificate is not expired

Dockerfile.base, dist/images/Dockerfile.fedora, test/e2e/service.go
=> OCPBUGS-32202: [release-4.15] Bump OVN to 23.09.0-139

go-controller/pkg/ovn/base_network_controller.go
In general, a node might be set as Ready and have things scheduled on it before we have had the chance to process the corresponding AddNode.
(cherry picked from commit 2233344281939da897605005fbc67e1bb47cb442)
=> OCPBUGS-29316: [release-4.15] Ignore missing live migratable pod annotation on AddNode

Dockerfile.base, dist/images/Dockerfile.fedora, test/e2e/service.go
=> OCPBUGS-32247: [release-4.14] OVN bump to 23.09.0-139

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/controller/services/lb_config.go, go-controller/pkg/ovn/controller/services/lb_config_test.go, go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/testing/kube.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
Clean cherry pick of https://github.com/openshift/ovn-kubernetes/pull/2025
=> OCPBUGS-32319:  [release-4.14] Full implementation of KEP-1669 ProxyTerminatingEndpoints + ETP=local fix

go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go
Cherry pick of https://github.com/ovn-org/ovn-kubernetes/pull/4343 from https://github.com/openshift/ovn-kubernetes/pull/2162
=> OCPBUGS-33960: Egressip garp fix 4.15

go-controller/pkg/ovn/egressfirewall_dns.go
backport of https://github.com/openshift/ovn-kubernetes/pull/2182
=> OCPBUGS-34405: [release-4.14] dns: fix deadlock in case of error

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/types/errors.go
/cc
/hold
See bugs / commits for more details
=> OCPBUGS-33623,OCPBUGS-33624: Improve CI signal by removing/suppressing signals

.ci-operator.yaml, Dockerfile
=> OCPBUGS-34462: Updating ose-ovn-kubernetes-container image to be consistent with ART for 4.17

go-controller/pkg/ovn/admin_network_policy_test.go, go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go, go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go, go-controller/pkg/ovn/controller/admin_network_policy/repair.go, go-controller/pkg/ovn/controller/admin_network_policy/utils.go, test/e2e/acl_logging.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/2201
more details of minor "import library conflict" outlined in commit2
u/s PRs:
1. https://github.com/ovn-org/ovn-kubernetes/pull/4413
2. https://github.com/ovn-org/ovn-kubernetes/pull/4445
3. https://github.com/ovn-org/ovn-kubernetes/pull/4367
=> OCPBUGS-35061: Allow ANPs at same priority

go-controller/pkg/ovn/base_network_controller.go
Fix race condition:
1. deleteNamespaceLocked, after the 20s delay, checks that the current nsInfo for the namespace is nil
2. ensureNamespaceLockedCommon adds a new nsInfo referencing the existing address set
3. deleteNamespaceLocked destroys the existing address set
(cherry picked from commit b1bb8edf95f14c1afc0454296f1f704225e9c51a)
=> OCPBUGS-36486: Fix race condition when creating/deleting namespace address set

go-controller/pkg/node/ovspinning/ovspinning_linux.go, go-controller/pkg/node/ovspinning/ovspinning_linux_test.go, go-controller/pkg/node/ovspinning/testdata/fake_thread_process.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/2220
=> OCPBUGS-37196: [release-4.15] ovspinning: Set affinity of each thread

go-controller/pkg/node/ovspinning/ovspinning_linux.go, go-controller/pkg/node/ovspinning/ovspinning_linux_test.go, go-controller/pkg/node/ovspinning/testdata/fake_thread_process.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/2235
=> OCPBUGS-37197: [release-4.14] ovspinning: Set affinity of each thread

go-controller/pkg/config/config.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdb/ops/acl.go, go-controller/pkg/libovsdb/ops/address_set.go, go-controller/pkg/libovsdb/ops/chassis.go, go-controller/pkg/libovsdb/ops/lbgroup.go, go-controller/pkg/libovsdb/ops/loadbalancer.go, go-controller/pkg/libovsdb/ops/model_client.go, go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/libovsdb/ops/qos.go, go-controller/pkg/libovsdb/ops/router.go, go-controller/pkg/libovsdb/ops/switch.go, go-controller/pkg/libovsdb/ops/template_var.go, go-controller/pkg/libovsdb/ops/transact.go, go-controller/pkg/ovn/controller/unidling/unidle.go, go-controller/pkg/ovn/controller/unidling/unidle_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/2244
=> OCPBUGS-38262: [release-4.15] Bump OVSDBTimeout and make it configurable.

go-controller/pkg/network-attach-def-controller/network_manager.go, go-controller/pkg/network-controller-manager/node_network_controller_manager.go, go-controller/pkg/node/gateway_udn.go, go-controller/pkg/node/gateway_udn_test.go, go-controller/pkg/node/iprulemanager/ip_rule_manager.go, go-controller/pkg/node/management-port_dpu_test.go, go-controller/pkg/node/secondary_node_network_controller.go, go-controller/pkg/node/secondary_node_network_controller_test.go, go-controller/pkg/ovn/gatewayrouter/policybasedroutes.go, go-controller/pkg/ovn/gatewayrouter/policybasedroutes_test.go, go-controller/pkg/util/node_annotations.go
=> SDN-4930,OCPBUGS-38949: Downstream Merge 28th August

go-controller/pkg/config/config.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdb/ops/acl.go, go-controller/pkg/libovsdb/ops/address_set.go, go-controller/pkg/libovsdb/ops/chassis.go, go-controller/pkg/libovsdb/ops/lbgroup.go, go-controller/pkg/libovsdb/ops/loadbalancer.go, go-controller/pkg/libovsdb/ops/model_client.go, go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/libovsdb/ops/qos.go, go-controller/pkg/libovsdb/ops/router.go, go-controller/pkg/libovsdb/ops/switch.go, go-controller/pkg/libovsdb/ops/template_var.go, go-controller/pkg/libovsdb/ops/transact.go, go-controller/pkg/ovn/controller/unidling/unidle.go, go-controller/pkg/ovn/controller/unidling/unidle_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/2252
=> OCPBUGS-38263: [release-4.14] Bump OVSDBTimeout and make it configurable

go-controller/pkg/config/config.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/address_set.go, go-controller/pkg/libovsdbops/chassis.go, go-controller/pkg/libovsdbops/lbgroup.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/qos.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/libovsdbops/template_var.go, go-controller/pkg/libovsdbops/transact.go, go-controller/pkg/ovn/controller/unidling/unidle.go, go-controller/pkg/ovn/controller/unidling/unidle_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/2275
Had a couple of conflicts, files are mentioned in the commit message
=> OCPBUGS-38264: [release-4.13] Bump OVSDBTimeout and make it configurable

docs/getting-started/configuration.md, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, mkdocs.yml
This PR is to remove iptables rules from FORWARD chain if config.Gateway.DisableForwarding is set to false. Following iptables rules gets removed from FORWARD chain given 10.1.0.0/16 is clusterNetwork CIDR and 10.96.0.0/16 is serviceNetwork CIDR.
-A FORWARD -s 10.96.0.0/16 -j ACCEPT
-A FORWARD -d 10.96.0.0/16 -j ACCEPT
-A FORWARD -s 169.254.169.1 -j ACCEPT
-A FORWARD -d 169.254.169.1 -j ACCEPT
-A FORWARD -d 10.1.0.0/16 -j ACCEPT
-A FORWARD -s 10.1.0.0/16 -j ACCEPT
-A FORWARD -i breth1 -j DROP
-A FORWARD -o breth1 -j DROP
Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com>
(cherry picked from commit 47408e0d70b01d784d8ed0be7e1a2c0cfce4c9cc)
Fixes #
```release-note
```
=> [release-4.16] OCPBUGS-36210: Implementation required to enable Forwarding if it is already disabled

Dockerfile.base, go-controller/pkg/allocator/pod/pod_annotation_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/pod_annotation.go, test/e2e/external_gateways.go, test/scripts/e2e-cp.sh
=> [sandbox-release-4.17] SDN-5297: 4.17 sandbox merge 11-12-2024

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
Routes via mp0 were being deleted on every ovnkube-node restart: [root@ovn-worker ~]# ip monitor route
Deleted 192.72.3.0/24 dev ovn-k8s-mp0 proto kernel scope link src 192.72.3.2 Deleted broadcast 192.72.3.255 dev ovn-k8s-mp0 table local proto kernel scope link src 192.72.3.2 Deleted local 192.72.3.2 dev ovn-k8s-mp0 table local proto kernel scope host src 192.72.3.2 local 192.72.3.2 dev ovn-k8s-mp0 table local proto kernel scope host src 192.72.3.2 broadcast 192.72.3.255 dev ovn-k8s-mp0 table local proto kernel scope link src 192.72.3.2
This causes traffic outage during upgrade, as well as other unwanted side effects when pod-destined traffic is routed via default gateway route in the host. This is especially disruptive in local gateway mode.
This patch removes the teardown, and then …
=> OCPBUGS-48777: Fixes unexpected mp0 route removal during start up

go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
(cherry picked from commit 4e4539eac8289a5495e10185b6f8a4cddb1a887b)
=> [release-4.17] OCPBUGS-52409: Change dynamic_neigh_routers to false for the Interconnect topology.

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_udn.go, go-controller/pkg/node/gateway_udn_test.go, test/e2e/route_advertisements.go
@kyrtapz did a piece of your fix go into the previous merge somehow?
=> OCPBUGS-52278, OCPBUGS-51165: Downstream Merge 28th april 2025

go-controller/pkg/node/gateway_shared_intf.go, test/e2e/multihoming.go, test/e2e/multihoming_utils.go
cc @ricky-rav and @asood-rh since this means the original bug needs to be moved to NEW state?
=> OCPBUGS-55825: Release 4.19 blocker bug ovs cpu backport: special cherry-pick

go-controller/pkg/types/const.go
This is a clean cherry-pick for a customer escalation bug.
The cache synce time could take longer time when pulling a large number of objects for apiserver.
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/c57e83c96b2fc676aa75eb588c574b08d118ea59)
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/812a0ca39af84fa409664cc509b7c049790f37f6)
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/0b9e5ab97eb332b1073f6bd5944c103d9e56e95a)
Fixes #
=> [release-4.16] OCPBUGS-48121: Increase InformerSyncTimeout to 60s

go-controller/pkg/clustermanager/node/node_allocator.go, go-controller/pkg/clustermanager/node/node_allocator_test.go, go-controller/pkg/clustermanager/node/subnet_allocator.go, go-controller/pkg/clustermanager/node/subnet_allocator_test.go, go-controller/pkg/util/net.go
This is a clean cherry-pick for a customer escalation bug.
When hybrid overlay clustersubnets is undefined, the hybrid overlay node subnet allocation is not managed by ovn-k.
But we need to  ensures hybrid overlay node subnets are properly marked as allocated in the cluster subnet allocator when they overlap with the cluster subnet ranges, preventing potential subnet allocation conflicts.
The fix helps maintain proper subnet allocation tracking when hybrid overlay nodes use subnets that fall within the cluster's subnet ranges.
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/192f575d351acc9bc049db213bf65f25a315e2c6)
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/13fb9bf54f97136e6eb5bba19240ce58dca2bf94)
Fixes #
=> [release-4.17] OCPBUGS-57109: Fix hybrid overlay node subnets collision with cluster subnets

OWNERS
@jluhrsen let's carry this till 4.18 and then @martinkennelly please cherry-pick this into 4.17 and 4.16 once they land till 4.18 via auto-merges.
Responsibility Split
@jcaamano - all master merges
@tssurya  - all 4.19 merges
@kyrtapz  - all 4.18 merges
@martinkennelly  - all 4.17 and 4.16 cherry-picks
cc @trozet PTAL
=> NO-JIRA: Update OWNERS file: Add Patryk/Martin as approvers

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Manual cherry-pick of 4.21 commit fea3444db90f166cb3d3371d4ce453c57d931f88. No conflicts.
=> [release-4.20] OCPBUGS-62336: Fix EgressIP controller deadlock by sorting node locks lexicographically
