openshift/ovn-kubernetes

dist/images/ovnkube.sh
`ovnkube.sh` hardcodes the namespace to look for the `ovnkube-master` service in, causing the nodes to never come up in a cluster-network-operator-managed cluster.
Upstream we should probably fix it so that this comes from an environment variable rather than being hardcoded, so that we don't need to carry a patch.
=> Fix hardcoded namespace in ovnkube.sh

Dockerfile
Fixes #5 
I was not able to test building this locally because it ends up pulling in a yum repo file that tells it to get something from `base-4-0.ocp.svc` (ie, assuming the build is running inside a container in the ci cluster). But I think it should work? Do we have to poke anything to get the image rebuilt?
=> Copy kubectl into image, for use by ovnkube.sh

Dockerfile, dist/images/iptables-scripts/ip6tables, dist/images/iptables-scripts/ip6tables-restore, dist/images/iptables-scripts/ip6tables-save, dist/images/iptables-scripts/iptables, dist/images/iptables-scripts/iptables-restore, dist/images/iptables-scripts/iptables-save
ovnkube creates iptables rules for nodeport ports, so it needs to use the right iptables binaries
see also https://github.com/openshift/cluster-network-operator/pull/197
=> Install iptables wrappers

dist/images/Dockerfile.fedora
It is "difficult" to build the RHEL-based openshift/ovn-kubernetes image by hand. ("Difficult" meaning I have no idea how to do it; if you try to build from the toplevel Dockerfile it ends up trying to pull RPMs from some repo inside the CI cluster.)
However, the upstream image also no longer works with our CNO DaemonSet, which assumes you will have iptables wrappers installed.
So this fixes `Dockerfile.fedora` in our fork of ovn-kubernetes to use the iptables wrappers, so we can build images based off that for local testing.
(@dcbw I believe the upstream `Dockerfile.fedora` currently creates an image that has *no* iptables binaries in it, which makes the node image crash at startup at least with local gateway mode.)
=> Add iptables wrappers to Fedora image

go-controller/pkg/cluster/gateway_init_linux_test.go, go-controller/pkg/cluster/gateway_localnet.go, go-controller/pkg/cluster/gateway_shared_intf.go, go-controller/pkg/cluster/gateway_spare_intf.go, go-controller/pkg/util/gateway-init.go
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/785. Not sure exactly what the problem is, but service IPs are unreachable from hostNetwork pods, breaking the install.
/assign @squeed 
/cc @dcbw
=> Revert "gateway/local: stop double-NAT-ing"

Dockerfile
numactl-libs is not built on s390x in RHEL 7.  It will be pulled in as a requirement of openvswitch2.11 on those architectures on which it is required.
=> Do not install arch-specific dependencies

dist/images/ovnkube.sh
This allows better debugging of startup/dependency issues in onvkube.sh
from the daemonset/deployment YAML of each container, so that we don't
need to build special container images just for debugging.
(cherry picked from commit cb10cc37bb8b0fd65257abf4ff9989d90fd7f9fc)
=> ovnkube.sh: add OVNKUBE_SH_VERBOSE for 'set -x' debugging

go-controller/pkg/cluster/gateway_init.go, go-controller/pkg/cluster/gateway_init_linux_test.go, go-controller/pkg/cluster/gateway_localnet.go, go-controller/pkg/ovn/management-port.go, go-controller/pkg/ovn/management-port_linux.go, go-controller/pkg/ovn/management-port_linux_test.go, go-controller/pkg/ovn/management-port_windows.go, go-controller/pkg/ovn/management-port_windows_test.go, go-controller/pkg/util/iptables.go, go-controller/pkg/util/net.go, go-controller/pkg/util/util.go
Certain CloudProviders (eg, Azure) assume that they can redirect loadbalancer traffic directly to a node with no rewriting, and the node will accept the packets. This works with kube-proxy because of a rule that was intended just as a shortcut to avoid sending local traffic to the load-balancer unnecessarily. Make it work with ovn-kubernetes too.
This was easier to fix for local gateway only than it would be to fix for everything, so I only fixed it for local gateway here. We need to fix this correctly upstream still.
This PR also pulls in the fixes to make HostPorts work and a random iptables-rules cleanup fix because it simplifies my new code. Only the last commit is new.
=> Bug 1749403: add iptables rules for Azure, etc, loadbalancers

dist/images/ovnkube.sh
Added environment variables OVN_NB_PORT, OVN_SB_PORT to support custom
ports. The defaults are 6641, 6642 respectively.
Jira: SDN-353 - OVN: move ports to 9000-9999
https://jira.coreos.com/browse/SDN-353
cherry-pick ovn-org/pr/832
=> bug 1748162 : OVN: make db ports configurable

go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go, go-controller/vendor/vendor.json
govendor fetch github.com/coreos/go-iptables/iptables@=v0.4.3
=> update the vendor for the go-iptables vendor code

go-controller/pkg/cluster/management-port_windows_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Clearing excluded IPs was only added to prevent some ovn-controller
logspam, but it also prevents correct handling of the hybrid overlay
port IP address which is statically assigned. The logspam is also
fixed in OVN 2.12.
=> Don't clear node switch exclude IPs

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/types.go
Same as https://github.com/ovn-org/ovn-kubernetes/pull/903 upstream; should tell us the real reason for `Nil response to CNI request`:
```
Nov 05 17:43:29 ip-10-0-136-174 crio[1881]: 2019-11-05T17:43:29Z [error] Multus: error adding pod to network "ovn-kubernetes": delegateAdd: error invoking DelegateAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: 'Nil response to CNI request
```
=> cni: actually return error messages on pod ADD failures

Dockerfile
Turns out we don't need to --enablerepo for yumdownloader; the repo is already enabled.
@jupierce @wking @squeed @gmarkley-VI
=> Dockerfile: remove unecessary --enablerepo

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_old.go
belated backport of the NetworkPolicy deadlock bug to 4.2... do we still care?
=> Bug 1755190: ovn: fix a deadlock in the NetworkPolicy code

Dockerfile
Adding the windows binary to the container build will allow the windows binary to be built in a way that can be released 
Jira Card: https://issues.redhat.com/browse/SDN-702
=> Build the windows binary as part of the container ovn-kubernetes container build

Dockerfile
Currently the windows binary does not get placed in the ovn-kubernetes image because the
dockerfile does not create the directory for it to be copied to.
=> correct the directory placement of windows binary

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
When nodes are added to the cluster, it may be that our pod add
handler is waiting for the node switch to show up. It might win
the race and create the pod between our node switch being
created in master.go and the exclude IPs being updated immediately
after. Fix this by reverting to setting the exclude IPs during
logical switch creation.
This is essentially a revert of part of 806dff11
Fixes: 80d6dff11983a4358693eef06467b1390e96e880
=> Bug 1796531: CARRY: fix race updating exclude IPs on node switch

go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/ipv4_hack.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/args.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/exec.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/find.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/os_windows.go, go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go, go-controller/vendor/modules.txt
This is a hack we originally did for IPv6 on AWS on 4.3, where lots of pods needed IPv4 access in order to make anything work. We were hoping to not need it for Azure, but at least for the moment DNS is broken without it. We may be able to kill it in the future. Note that it completely no-ops unless you're in a single-stack IPv6 cluster.
I left in the AWS hack list in case we need it again in the future...
Note that we do not plan to ever support single-stack IPv6 for customers on cloud platforms so the hardcoded IP range doesn't really matter.
/assign @dcbw 
/cc @russellb
=> HACK: add ipv4 interfaces to pods that need them

go-controller/pkg/cni/ipv4_hack.go
@trozet was asking questions about this and I realized it should probably be documented better
/cc @dcbw @russellb @knobunc
=> Add more docs to pkg/cni/ipv4_hack.go

go-controller/pkg/cluster/cluster.go, go-controller/pkg/cluster/node_test.go
This reverts commit 799df52e72d24d77d5531e0961609ae9e43ca8b6.
=> Revert "cluster.go: Disable Southbound DB conditional monitoring."

go-controller/pkg/cluster/gateway_localnet.go
We have a local hack to make load balancers on Azure work (#23) which was never upstreamed because I didn't know how to implement it for shared gateway mode. We should fix that. But anyway, the code needs a fix for IPv6.
/assign @dcbw 
/cc @ironcladlou
=> Bug 1810814: CARRY: ovn: fix cloud load balancer rules for IPv6

go-controller/pkg/cluster/gateway_localnet.go
=> Bug 1810816: [4.4] CARRY: ovn: fix cloud load balancer rules for IPv6

go-controller/hybrid-overlay/cmd/hybrid-overlay/hybrid-overlay.go, go-controller/pkg/cluster/node_test.go
Prevents a "cluster subnet invalid" error on starting the Windows binary. Because of Tim's config defaults changes in https://github.com/ovn-org/ovn-kubernetes/pull/1044 the cluster subnets option will now be empty unless the config flags are added that fill in the defaults.
@JacobTanenbaum @aravindhp @ravisantoshgudimetla
=> CARRY: hybrid-overlay: fix argument handling for Windows hybrid-overlay.exe

go-controller/pkg/cluster/cluster.go, go-controller/pkg/cluster/node_test.go
ovn-controller enables conditional monitoring by default for tables in
the Southbound Database it is interested in (e.g., Logical_Flow). This
effectively performs row level filtering for the SB DB tables such that
an ovn-controller would receive only updates about records that refer to
logical datapaths that are local to the chassis.
However, in an ovn-kubernetes cluster, all node logical switches are
connected to the ovn-cluster-router which forces all ovn-controllers to
register for updates about all logical switches.
The conditional monitoring implementation in OVSDB turns out to not
scale so well in such scenarios.
OVN 20.03 supports a new configuration knob (ovn-monitor-all=true) which
instructs ovn-controllers to not use row level filtering of records.
This was introduced by: …
=> cluster.go: Disable Southbound DB conditional monitoring.

go-controller/pkg/ovn/ovn.go
This is apparently not needed as it's been removed in release-4.5 and master, and upstreams. So let's just remove it.
=> Bug 1814712: Removing node bring up debug log level

go-controller/hybrid-overlay/pkg/controller/node_linux.go
cherry pick of https://github.com/ovn-org/ovn-kubernetes/pull/1286
along with https://github.com/openshift/cluster-network-operator/pull/604 restores communication over the hybrid overlay network for an openshift cluster 
It was returning exactly the opposite of what it was supposed to.
Fixes: 0303efa4de5a13
=> Bug 1827391: hybrid-overlay: fix podChanged() return values

go-controller/hybrid-overlay/pkg/controller/node_linux.go
cherry pick of https://github.com/ovn-org/ovn-kubernetes/pull/1286
along with https://github.com/openshift/cluster-network-operator/pull/604 restores communication over the hybrid overlay network for an openshift cluster 
It was returning exactly the opposite of what it was supposed to.
Fixes: 0303efa4de5a13
=> [release-4.4] Bug 1827392: hybrid-overlay: fix podChanged() return values

Dockerfile
`HAProxy Router performance is off with OVNKubernetes as SDN on OCP 4.3.9 deployed on AWS`
https://bugzilla.redhat.com/show_bug.cgi?id=1819785 [ovn]
https://bugzilla.redhat.com/show_bug.cgi?id=1830370 [ocp]
`ovn-northd: Optimize flows for LB Hairpin traffic.`
https://bugzilla.redhat.com/show_bug.cgi?id=1827403
=> Bug 1830370: build: require OVN >= 2.13.0-21 for rhbz#1819785 and rhbz#1827403

go-controller/pkg/ovn/pods.go, go-controller/pkg/util/pod_annotation.go, go-controller/pkg/util/pod_annotation_test.go
cherry pick of upstream: b5fb5b
Currently passing nil elements to MarshalPodAnnotations will cause "<nil>"
to be added to the json fields where they are not appropriate.
This PR removes one specific example of attempting to pass a nil element
to MarshalPodAnnotations() and fixes an error in UnmarshalPodAnnotations()
which incorrectly handled a call to net.ParseIP() in which was expecting
an error in the case of an invalid IP address but in the docs returns nil
on invalid IP. This exposes the error of attempting to unmarshal an
invaild gatewayIP and add a test case to verify the error returned.
=> Bug 1828988: Remove errors based on passing nil elements to MarshalPodAnnotations()

Dockerfile
HAProxy Router performance is off with OVNKubernetes as SDN on OCP 4.3.9 deployed on AWS
https://bugzilla.redhat.com/show_bug.cgi?id=1819785 [ovn]
https://bugzilla.redhat.com/show_bug.cgi?id=1830370 [ocp]
ovn-northd: Optimize flows for LB Hairpin traffic.
https://bugzilla.redhat.com/show_bug.cgi?id=1827403
ovn-northd: Clear SB records depending on stale datapaths.
https://bugzilla.redhat.com/show_bug.cgi?id=1828637
Fix ACL reject action for UDP packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1823755
Also lock openvswitch2.13 to 2.13.0-10 to ensure signed RPMs are picked up rather than stuff from the FDN repos.
=> Bug 1830416: build: require OVN >= 2.13.0-30 for rhbz#1819785, rhbz#1827403, rhbz#1828637, rhbz#1823755

Dockerfile
We need signed OVN RPMs which are in the FDN repos, but those repos
also include OVS 2.13.0-17 which is unsigned and which we don't yet
need. So we need to lock both OVS and OVN versions to get the right
signed RPMs for now.
@sdodson
=> Bug 1830370: lock OVS version to 2.13.0-10 to ensure signed RPMs

go-controller/pkg/ovn/pods.go, go-controller/pkg/util/pod_annotation.go, go-controller/pkg/util/pod_annotation_test.go
cherry pick of upstream: b5fb5b
master PR: https://github.com/openshift/ovn-kubernetes/pull/156
Upstream PR: https://github.com/ovn-org/ovn-kubernetes/pull/1319
Currently passing nil elements to MarshalPodAnnotations will cause "<nil>"
to be added to the json fields where they are not appropriate.
This PR removes one specific example of attempting to pass a nil element
to MarshalPodAnnotations() and fixes an error in UnmarshalPodAnnotations()
which incorrectly handled a call to net.ParseIP() in which was expecting
an error in the case of an invalid IP address but in the docs returns nil
on invalid IP. This exposes the error of attempting to unmarshal an
invaild gatewayIP and add a test case to verify the error returned.
=> [release 4.4] bug 1829442: Remove errors based on passing nil elements to MarshalPodAnnotations()

go-controller/pkg/factory/factory.go
This commit enables creating queued informers for pod events and
increases the number of event queues for handling events to 15.
At scale, the pod informer gets events more rapidly, but the handling
of these events is rather serialized. This will allow for multiple pod
events to be handled in parallel for a given namespace.
Scale tests were ran with this change.
At higher node scale (n > 150), the event handlers start contending if the numEventQueues is > 25.
Signed-off-by: Aniket Bhat anbhat@redhat.com
=> Bug 1820737: scale: Enable parallel pod creation

go-controller/cmd/ovnkube/ovnkube.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn_test.go
Backport of two upstream PRs:
https://github.com/ovn-org/ovn-kubernetes/pull/1378 - long service creation time.
https://github.com/ovn-org/ovn-kubernetes/pull/1384 - informer deadlock
This fixes two issues I've seen during debugging tests.
=> Bug 1845202: Fix deadlock, fix service lag.

go-controller/pkg/factory/factory.go
This commit enables creating queued informers for pod events and
increases the number of event queues for handling events to 15.
At scale, the pod informer gets events more rapidly, but the handling
of these events is rather serialized. This will allow for multiple pod
events to be handled in parallel for a given namespace.
Scale tests were ran with this change.
At higher node scale (n > 150), the event handlers start contending if the numEventQueues is > 25.
Signed-off-by: Aniket Bhat anbhat@redhat.com
=> Bug 1838259: scale: Enable parallel pod creation

go-controller/pkg/ovn/ovn.go
On a restart of ovnkube master due to leader election change
(normal) and perhaps loading and processing all the existing pods.
E0609 18:43:27.194389       1 ovn.go:396] timeout waiting for namespace event
Occured. We process services and endpoints before namespaces, which is
the wrong order because pods (which are first) depend on Namespaces.
So if there are a lot of services & endpoints their initial processing
will block the namespaces which will block and fail pods.
SDN-1037 - Processing services and endpoints incorrectly happens before namespaces.
https://issues.redhat.com/browse/SDN-1037
=> Fix order of pods, namespaces, services and endpoints

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/iptables_blocking.go
noticed by @celebdor 
/assign @dcbw 
Also fixed failure-to-do-MCS-blocking to be a fatal pod error rather than just a warning. And for the same reason, I made the IPv4 and IPv6 sections conditional on whether we are using IPv4/IPv6, since you don't want to block IPv4-only pods because we couldn't create ip6tables rules.
=> cni: update MCS-blocking code to do both IPv4 and IPv6

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/util/util.go
not all hybrid network cases will have externalGateway and VTEP IPs.
Correct the functionality of CopyNamespaceAnnotationToPod() to only
copy annotations types.HybridOverlayExternalGw and
types.HybridOverlayVTEP to a pod if they exist on the namespace.
Then the AddPod() can correctly deal with unset values.
without this patch the test 'sets up local pod flows' in
go-controller/hybrid-overlay/pkg/controller/node_linux_test.
shows errors.
=> Bug 1849728: UPSTREAM 1465: Correct the way that externalGateway and VTEP IP are copied

Dockerfile
This makes the Dockerfile compatible with RHEL 8 by not requiring unused
and obsolete packages.
PyYAML should no longer be required as of commit f2dbc63c5efbb23743a31c1a46db589d9a5bb6dd.
yum-utils should no longer be required as of commit 2d4733b352265106fab7bfd6d5087b29a57f09d1.
Image should build and pass CI as before.
Remove unused packages from Dockerfile
=> Remove unused packages from Dockerfile

go-controller/pkg/cni/OCP_HACKS.go, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_init_linux_test.go
The downstream merge broke the unit-test compilation for one of the tests.
This fixes the unit-test file and makes gofmt happy.
=> Fix broken unit-tests and make gofmt happy

go-controller/pkg/config/config.go
We added a hack in the downstream code to set the common name of the certs
to let CI pass. This PR removes that hack. 
=> Undo the hack for CNO common name

Dockerfile
We need to add arping to the containers we use as to not have the ovn-kube complain (crash) if we run egress IP until we fully transition to shared gateway mode for OpenShift. 
Can go in before / after https://github.com/openshift/ovn-kubernetes/pull/222
/assign @dcbw 
=> Adding arping to OCP ovn-kube image for egress IP

go-controller/pkg/ovn/pods.go
We were missing a continue when we couldn't lock the namespace which
ended up segfaulting during port deletion..
=> Fix segfault in exgw route deletion

contrib/kind.sh, go-controller/hack/build-go.sh, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_others.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_windows.go, go-controller/hybrid-overlay/pkg/windows/service/service.go, go-controller/pkg/config/config.go, go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/node.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_local.go, go-controller/pkg/ovn/egressip_local_test.go, go-controller/pkg/ovn/egressip_shared.go, go-controller/pkg/ovn/egressip_shared_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go
Includes fixes for Network policy and egress IP.
Note the revert for allow-related will lower performance for pod<->pod traffic without network policy.
=> Bug 1873311: 8 27 2020 merge

Dockerfile
Pin the version for 4.5.8 as to avoid problems during the upgrade from 4.5.7 -> 4.5.8
/assign @knobunc @joepvd 
=> Bug 1874928: Pinning the OVN version for 4.5.8 release

go-controller/pkg/node/gateway_localnet.go
Using br-local with NORMAL action wasn't working because both ports have the same MACUsing.
This PR sets the annotation so that the OVN GR will use a different MAC address
=> Bug 1870867: Fix br-local duplicate MAC

Dockerfile
ART is still using a rhel7 base content set, while CI uses rhel8.
Which means we have to keep the RPM pinning agnostic.
@danwinship
=> Bug 1878295: Dockerfile: fix ART image builds by making RPM pinning agnostic

go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/config/config.go
The hybrid-overlay-cluster-subnets argument is not required to have a
value for hybrid overlay to work. It is only required when using Windows
nodes that are part of the cluster. It is not required when sending to
3rd party gateways. This patch removes the default subnet value for the
arg.
(cherry picked from commit d117020089abafbc0ffa7b32a27e776efd18e963)
=> Bug 1868501: Do not default HO cluster subnets

.github/workflows/test.yml, contrib/kind.sh, dist/images/Dockerfile.ubuntu, go-controller/pkg/factory/factory.go, go-controller/pkg/informer/const.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/gress_policy_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/net_linux.go, test/scripts/e2e-kind.sh, test/scripts/install-kind.sh
Fixes for:
- ipv6
- host networking
- exgws
- egress firewall
=> Bug 1880974: 9-21-2020 merge

Dockerfile
4.4.24 latest 4.4.Z release is running 20.06.2-4.el7fdp :  https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.4.24
Pin to that
/assign @trozet @dcbw 
=> Bug 1882066: Pin 4.4 OVN to 20.06.2-4.el7fdp

Dockerfile
This pins the 4.6 version to the version 20.06.2-11.el8fdp which is shipped with 4.6.0-0.ci-2020-09-23-155325 (latest CI release)
=> Bug 1882085: Pin 4.6 OVN to 20.06.2-11.el8fdp

Dockerfile
https://github.com/openshift/ovn-kubernetes/pull/283 pins OVN to 20.06.2-4.el7fdp so we pin 4.5 to the same version
=> Bug 1882092: Pin 4.5 OVN to 4.4.24

go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/OCP_HACKS.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/master.go
For OCP we upgrade CNO before MCO. This means that ovn-k8s will get upgraded first when 4.5->4.6 upgrade happens and will try to create a bridge for local gateway mode now. We have to have an intermediate step where we do not create a shared gateway bridge until after the node reboots with ovs-configuration. Therefore this downstream only patch allows us to launch local gateway mode with no shared gateway bridge, and it should still function during upgrade.
=> Bug 1880591: Allow local no bridge

Dockerfile
Pin to latest CI (which at the moment of writing is https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.6.0-0.nightly/release/4.6.0-0.nightly-2020-09-25-070943) 
=> Bug 1882707: [release-4.6] Pin OVS to latest 4.6 RPM version

Dockerfile
=> Bug 1882569: Update downstream Dockerfile for adding the ovndbchecker binary

.github/actions/cleanup-action/package-lock.json, .github/workflows/test_periodic.yml, go-controller/hack/test-go.sh, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/config/config.go, go-controller/pkg/informer/informer.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/endpoints_test.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/util/net.go
Fixes:
- Upgrade by ensuring reject ACLs get removed.
- logical route policy deletion when nodes are deleted.
=> Bug 1880591: 9-30-2020 merge

go-controller/pkg/ovn/OCP_HACKS.go, go-controller/pkg/ovn/gateway_init.go
When we upgrade from 4.5->4.6 we transition from the old local gateway
mode to the new. In this case, OVS is clean when 4.6 comes up, but OVN
DB still has a leftover "br-local" port that exists on the external
switch. ovn-controller will try to wire this port to br-int, creating
double patch ports between br-ex and br-int, thus causing a broadcast
storm.
This patch ensures we remove the old port from OVN NB DB, which
ovn-controller will then ensure is removed from the external switch.
=> Bug 1885517: Clean up old local gw mode external ports

go-controller/pkg/ovn/loadbalancer.go
Fix service sync reject ACL name matching
The generateACLName function was including backslash escapes for the ACL
name for use in OVN commands that have trouble with literal ":". That
was causing a mismatch when services were syncing because the name
actually returned from an OVN command does not include any backslashes
so the names would not match.
=> Bug 1880591: Fix service sync reject ACL name matching

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go
…memory bloating
During the pod creation, ovnkube-node dump all the flows from br-int and grep
for the ip address of the pod to verify that pod related flows are programmed.
This can cause aggrasive and big memory allocation to store the string output
from ovs-ofctl command.
This patch optimized the ovs-ofctl dump-flow query to dump flows only related
to the pods. This will avoid dumping the massive string output and prevent
from memory bloating.
Signed-off-by: Anil Vishnoi <avishnoi@redhat.com>
=> Bug 1862700: Fix ovnkube-node aggressive memory allocation to prevent memory bloating

Dockerfile
Updating ose-ovn-kubernetes builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-ovn-kubernetes.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating ose-ovn-kubernetes builder & base images to be consistent with ART

go-controller/pkg/node/gateway_localnet.go
Fixes an IPv6 regression introduced by #238
=> Bug 1888352: Fix IPv6 neighbor discovery hack

Dockerfile
Add missing python3-openvswitch library
This PR adds a missing library to the Dockerfile in order to be able to run
ovn-detrace later on.
=> Add missing python3-openvswitch library

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/policy.go
This PR backports the fixes found in https://github.com/ovn-org/ovn-kubernetes/pull/1665
I also had to solve some merge conflicts: 
in `policy.go` With with how we loop though the `gressPolicies`, it now uses a `namespacePolicy` now rather than a *knet.NetworkPolicy to get the policy's name and namespace 
in `namespace.go` remove `oc.deleteGWRoutesForNamespace(nsInfo)` and keep `deleteAddressSet(hashedAddressSet(ns.Name))`
=> Bug 1877561:  [release-4.5]Fix orphaned ACLs backport to 4.5

go-controller/pkg/node/OCP_HACKS.go
When an ovnkube-node upgrades, it annotates its gateway config onto the
kubernets node object. When ovnkube-master sees this node add/update
event it then will try to sync its gateway configuration in OVN. In
ovnkube-master 4.6, if we see a node that is in a 4.5 state, but its pod
is a 4.6 ovnkube-pod we will ignore doing any OVN gateway config on it.
However, this patch addresses a case where 4.6 ovnkube-node upgraded,
started, and annotated its node, before ovnkube-master pod was upgraded
to 4.6. In that case the old 4.5 ovnkube-master code will try to create
a gateway interface, for the updated node, and we were never setting
that interface ID. Thus, OVN would get a new port with an empty name in
addition to its already configured br-local port and not know which one
to use. If it …
=> Bug 1880591: Fixes race during 4.5->4.6 upgrade with ovn node and master

Dockerfile
We have good signal for this build in 4.6 via https://github.com/openshift/ovn-kubernetes/pull/324 so we're pretty sure this OVN is solid.
@trozet
=> [master] Bump OVN to 20.09.0-7

dist/templates/ovnkube-db-raft.yaml.j2, dist/templates/ovnkube-db.yaml.j2, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go
In certain use-cases such as master replacement, we have seen
that the configuration of the db/master pods that holds the addresses
of the raft members isn't updated by the time the new master joins the
raft cluster. When this happens the db pods carrying the old address
configuration for nbdb and sbdb would kick the newly joined master out.
This commit addresses this issue by additionally checking existing master
pods' IPs against the server id list for determining whether a given
server id should be booted out of the raft cluster.
=> Bug 1885675: Consider changed configuration when kicking out raft members

.github/workflows/test.yml, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/ovs_test.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/ovs_unit_test.go
1. shared gw mode flows for ingress to pods
2. local gateway moving to normal flows from flood
3. fixes icmpv6 flooding in shared bridge flows
4. fix network policy when the namespace label changes
5. fixes for CNI with ADD failures related to using a namespace that starts with a number
=> Bug 1887456: 11-20-2020 merge

go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go
The release-4.6 branch are broken when running the command `make check`.
This commit fixes the build. 
I suspect this commit https://github.com/openshift/ovn-kubernetes/commit/15661c9d1d23fe0b30d266bda3668ee848884fb5 was the one that introduced the broken build. 
Tomorrow I am going to work on having `make check` be gating on release-4.6 and master (similar to `/test unit` on openshift/sdn) as to not have to do this again. 
=> Bug 1898269: Fix broken make check on 4.6

Dockerfile
OVS 71.fdp8 has fixed the lldpd CVE. OVS 72.fdp8 seems to also
enable IPSec support, given that this is happening soon: we might as well
bump to that.
/assign @dcbw 
=> Bug 1897480: Bump OVS to >= 2.13.0-72.fdp8 for lldpd CVE fix

Dockerfile
This PR adds python3-pyOpenSSL to the Dockerfile, needed for ovn-detrace to
work with ssl endpoints.
=> Add missing python3-pyOpenSSL library

Dockerfile
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Dockerfile: Add required packages to enable IPsec

Dockerfile
Only change is a fix to LB VIP selection in ovn-northd that was
broken in -14 and later.
@trozet
=> Dockerfile: bump OVN to 20.09.0-21

Dockerfile
iproute-tc provides tc binary for OVS HW offload debugging
=> Bug 1907328: add iproute-tc package

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go
We still see that at high scale, sometimes high latency will cause CNI
ADD to fail and then retry. During this time a subsequent CNI ADD may
succeed by accidentally checking the flows of the previous CNI
interface. This patch adds a check for the OpenFlow port in the OVS
flows to ensure that the flows we are checking are for the new port.
More context here:
https://bugzilla.redhat.com/show_bug.cgi?id=1885761
=> Bug 1885761: Adds OFPort to CNI OVS check

go-controller/pkg/node/gateway_localnet.go
Our flows for flooding icmpv6 to both OVN and the host were too generic.
This caused ICMPv6 echo requests to be sent to both, resulting in a
duplicate ack and other issues. This patch changes the flows for icmpv6
to be more specific and target only flooding for Neighbor Advertisements
and Route Advertisements. This will allow OVN to receive only the
packets it needs for peering/discovery, while all other ICMPv6 will go to
the host only.
(cherry picked from commit 1206bc2ba30d35a9c896b3cddf6f2f8fd6694583)
=> Bug 1899266: Fixes ICMPv6 flooding behavior

go-controller/pkg/util/kube.go
Our client will under high load exceed the default QPS (query per second)
and Burst setting when communicating with the API server, which will cause
the client request to get throttled by the API server. These default
values are currently 5 and 10 respectively. Scalability testing has shown that
25 and 25 are values which lead to reasonable pod ready latency times
under high load.
@alexanderConstantinescu @trozet
=> Bug 1908472: [4.6] Increase QPS and Burst setting

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Currently when using a namespaceSelector and podSelector in the same network
policy when changing the labels of the namespace nothing happens.
Correct the operation so that when updating the label removes a
namespace from a network policy the pods are correctly removed
=> Bug 1908803: [4.6] fix network policy when the namespace label changes

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
This back-ports the essential bits for the egress IP assignment procedure to guard against node IP assignment (as outlined in https://github.com/ovn-org/ovn-kubernetes/pull/1668). This PR requires a couple of additional commits that came after https://github.com/ovn-org/ovn-kubernetes/pull/1668, as that PR had some flaws that needed to be fixed afterwards. 
/assign @danwinship 
=> Bug 1898178: [release-4.6] Handle egress IP assignment for node IPs

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/kube.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/1653
In some cloud environments the Kube node name is a short name, while
the node's "hostname" is an FQDN. eg:
node.Name: ci-op-h2qtbcsi-99b10-qhxj2-worker-d-6wxxl
hostname:  ci-op-h2qtbcsi-99b10-qhxj2-worker-d-6wxxl.c.openshift-gce-devel-ci.internal
syncNodesPeriodic() assumed they were going to be the same, which
resulted in deleting all chassis records from the SBDB every five
minutes, because ovnkube-node was setting the node's FQDN as the
@trozet @fepan @fedepaol
=> Bug 1908921: ovn/node: use node name as chassis hostname

go-controller/pkg/node/gateway_localnet.go
Set readyFunc for OCP HACK. This is a downstream only fix.
=> Bug 1908231: Assign readyFunc during local gateway init

Dockerfile
This version of 'ovs-monitor-ipsec' contains a number of bugfixes
that are required to fix IPsec support.
=> Bug 1908789: Dockerfile: bump OVS to 2.13.0-79

go-controller/pkg/ovndbmanager/ovndbmanager.go
In some corner cases when the DB pods are brought up by the daemonset,
the ovn db file may exist. However, it may be in a state where it does
not have itself as a valid raft node or hasn't joined the existing
raft cluster and is therefore not having valid remote server addresses
in the local instance. Our daemonset code assumes that if the db file
exists, it has the right raft information present so that it can sync
with other db instances and rebuild the db. In the above mentioned
edge-case this doesn't hold true and eventually results in master/db
pods that are continuously crash-looping.
This change relies on the periodic cluster status check to ensure that
the local db is part of the cluster (or is atleast a candidate for
the cluster). If on 10 consecutive retries, the cluster status …
=> Bug 1903660: Handle pruning of unhealthy db files on disk

go-controller/pkg/ovn/ovn.go
If there are egressFirewall Policies with dnsName filters on them when
restarting an ovnkube-master container the ovnkube-master pod will
segfault because the EgressFirewall tries to add the rule before the
EgressDNS object is created
fix the order in which the EgressFirewall is started so that the DNS
object is started before the Watcher.
https://bugzilla.redhat.com/show_bug.cgi?id=1909911
backport of upstream ovn-kube commit 054ed6d... PR https://github.com/ovn-org/ovn-kubernetes/pull/1936
=> Bug 1909911: Fix egressFirewall segfault caused by restarting

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/service.go
This PR fixes the problem found here https://bugzilla.redhat.com/show_bug.cgi?id=1903651
When a POD sends traffic to a service it is loadbalanced(DNAT-ed) and sometimes the same pod is chosen as the backend to the service. To ensure this traffic travels through OVN-K8s rather than the POD2POD network since (srcIP==dstIP), the traffic is SNAT-ed to the VIP of the service's loadbalancer, which results in some packet loss with hairpinned traffic since this is not currently accounted for in the network Policy code
Temporary solution:
In the long term, a feature is being created that will allow for us to specify the loadbalancer's SNAT IP in OVN see -> https://bugzilla.redhat.com/show_bug.cgi?id=1908540. This will allow us to make a few rules to cover all the possible SNAT IPs, which is not …
=> Bug 1903651: Add clusterIP to ingress policy AS for SNAT-ed hairpin Traffic Cherry Pick 

Dockerfile
The network-tools repo requires ovnkube-trace for the scripts. Would
be nice if the openshift/ovn-kubernetes ships the binary so that
the binary can copied to the network-tools image. The alternative is
to vendor the whole ovn-kubernetes repo which cause pulling a lot
of dependencies. Considering the image already builds the dbchecker,
adding ovnkube-trace as well would only make it more consistent.
=> Bug 1917911: Add ovnkube-trace binary to image

go-controller/pkg/cni/OCP_HACKS.go, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_init_linux_test.go
The MCS-blocking rules were too aggressive, and would block connections using 22623/22624 as a source port in some cases.
`--syn` means "SYN and not ACK", so this should make it only block attempts to establish connections to port 22623/4, and not any other traffic involving those ports.
=> Bug 1915027: Fix MCS-blocking iptables rules

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
This PR fixes the bug referenced. It brings in several commits (which only touch the egress IP code) which are needed for a smooth back-port. All commits have been cherry-picked without any additional modification. 
These commits have fixed the incorrect behavior on master. 
/assign @danwinship 
=> Bug 1898160: Egress IP fail-over and health checks

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Cherry-pick of: https://github.com/ovn-org/ovn-kubernetes/pull/1939
Egress IP assignments can change depending on the health check detection
of routes to egress nodes. Once that re-assignment happens we previously
experienced several minutes of packet loss between the source pods and
any external services they were targetting because no GARP was configured
on the external gateway routers by OVN. This lead to several minutes of
interrupted traffic until the ARP cache expired between client and server
for the egress pods.
I am only configuring GARP on egress-assignable nodes, and removing the
configuration once the egress node is flagged as not usable anymore.
/assign @danwinship 
**- …
=> Bug 1910533: Configure GARP for egress IP re-assignment

go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go
The new service controller for endpoint slices has a repair
loop that runs once, during the controller startup process,
so we can delete out of sync data between OVN and Kubernetes,
specially to deal with upgrades and OVN new features.
The repair loop was using the controller service tracker as a
source of true, but this is racy because the service tracker
is updated just after the OVN Load Balancer has been configured,
so it can happen that the Service has an OVN loadbalancer, but
doesn´t exist on the service tracker. As a consequence the repair
loops things that is a stale loadbalancer and deletes it.
The repair loop must use the informer cache as source of true, also
it must run before starting the informers workers, so we avoid any
races.
Signed-off-by: Antonio Ojea <aojea@redhat.com> …
=> Bug 1915295: fix service controller repair loop race

Dockerfile
CI gives warning:
'Using '==' operator in reldeps can result in an undefined behavior.
It is deprecated and the support will be dropped in future versions.
Use '=' operator instead.'
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Dockerfile: yum '==' operator deprecated

go-controller/pkg/ovn/policy_test.go
PR: https://github.com/openshift/ovn-kubernetes/pull/389 merged and broke 4.6 for `make check`. This commit fixes that. Once: https://github.com/openshift/release/pull/13218 merges this should automatically be discovered, but for now committers need to run `make check` locally before pushing a PR. 
/assign @JacobTanenbaum 
=> Bug 1912388: Fix broken make check on 4.6

Dockerfile
As done in https://github.com/openshift/ovn-kubernetes/pull/284 but for OVS
=> Bug 1882694: Pin OVS to latest 4.4.22 RPM version

go-controller/pkg/ovn/egressgw.go
The ovn_cluster_router policy was being removed for a pod anytime an
exgw was deleted. This is incorrect, because a pod may have more than
one exgw configured. The policy should only be removed for a pod if it
no longer has any exgws configured.
Additionally, the policy was being removed for potentially the wrong
node. This patch corrects the node to be the one where the affected pod
lives.
(cherry picked from commit a843da3d15ecfaef857e07cc2c977fc2d94e3a96)
=> Bug 1917609: Fixes deleting exgw pod

Dockerfile
This bumps OVS to 2.13.0-72.el8fdp, same version as master. The goal being to bump to a version fixing the CVE mentioned in the referenced bug. 
/assign @dcbw  
=> Bug 1912328: Bump OVS to 2.13.0-72

go-controller/Makefile, go-controller/hack/lint.sh, go-controller/hack/test-go.sh
Cherry-pick changes from github.com/ovn-org/ovn-kubernetes#1935 and github.com/ovn-org/ovn-kubernetes#1976 for running lint, gofmt, and utest jobs in containers.
=> Bug 1892472: Run linter, utests, and gofmt in container

go-controller/Makefile, go-controller/hack/lint.sh
This commit allows the linter to be run with podman
as the runtime. It also removes the dependency on
GITHUB_ACTIONS env for checking if the make target is
container runnable.
(cherry picked from commit 79293f19eb54de246b847abd66cbc049fab91860)
=> Bug 1892472: Allow for linter to run with podman as a runtime

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
NOTE: back-port of #422
Egress IP assignments can change depending on the health check detection
of routes to egress nodes. Once that re-assignment happens we previously
experienced several minutes of packet loss between the source pods and
any external services they were targetting because no GARP was configured
on the external gateway routers by OVN. This lead to several minutes of
interrupted traffic until the ARP cache expired between client and server
for the egress pods.
I am only configuring GARP on egress-assignable nodes, and removing the
configuration once the egress node is flagged as not usable anymore.
/assign @danwinship 
**- How to …
=> Bug 1920482: Configure GARP for egress IP re-assignment

Dockerfile.utest
For OpenShift CI, we need to create a custom image that has podman
installed in it to run the containerized linter, gofmt, and utests
There is no base image that will provide podman by default. So the
alternative is to create our own image and use it in the tests.
=> Create a podman image to use with CI so linter/utests can be run

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/block_mcs.go, go-controller/pkg/node/gateway_localnet.go
backport of #400 to 4.5
This had to be rewritten to deal with code differences from 4.5 to master so it could use some extra sanity-checking
=> Bug 1921283: [4.5] Fix MCS-blocking iptables rules

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace.go
When an address set is created in the code, there is no guarantee that
the address set is created. Failure in ovn-nbctl can cause no address
set to be created for a namespace nsInfo struct, for example. In this
case other threads will assume there is an address set and this will
cause segfault. This patch adds some protection around calling address
set methods and ensuring the address set is created.
Found in:
https://bugzilla.redhat.com/show_bug.cgi?id=1888827
(cherry picked from commit cf4f8f5a1cef132178210d9783f6b0f619118dd6)
=> Bug 1889460: Guard against nil address set usage

go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go
Temporary fix idling and reject with the new service controller.
In 4.8 we leverage OVN for doing that, in 4.7 we use ACLs
=> Bug 1918442: Fix idling and rejects for 4.7

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/util/iptables.go
Our iptables rules for NodePort and ExternalIP services were setting
up rules in filter FORWARD, which is a table used for routing packets
which don't have the node IP as neither source nore destination IP.
This is not needed for NodePort and ExternalIP. For NodePort services we
currently DNAT directly to the gatewayIP/clusterIP when a packet hits
a node, and this happens on every node, which thus, does not warrant
setting up filter FORWARD rules. In no case will node port packets
just be forwarded to another node.
For ExternalIP there is one case where routing external IP packets to
another node does occur, but we use routing table rules to do this. Which
means the filter FORWARD rules are not needed in that case either.
The problem with having NodePort and ExternalIP iptables rules in …
=> Bug 1937238: Refactor chain setup for NodePort and ExternalIP

Dockerfile
Includes a required fix for force_snat_ip=router_ip for upcoming shared
gw.
=> Bump OVN to ovn2.13-20.12.0-25.el8fdp

go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/util/kube.go
the endpoint slice controller was checking if the kubernetes
version was greater than 1.20 in order to run, so it can verify
the dual-stack api was implemented.
Since the endpoint slice controller in ovn can run with or without
the dualstack api, we only need to check that the API for slices
is enabled.
Backport https://github.com/openshift/ovn-kubernetes/commit/cdabdc3244de873beaac168b7f613f445bdda380
=> Bug 1932268: detect if the cluster has endpoint slices

go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go
Will periodically release memory back to the OS.
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/1920 that was pulled into 4.8 as part of https://github.com/openshift/ovn-kubernetes/pull/438
@trozet
=> Bug 1943310: [4.7] Enable DB memory trimming on compaction

go-controller/pkg/ovn/policy.go
Note: The 4.7 backport PR https://github.com/openshift/ovn-kubernetes/pull/468 pulled in the 
ACL syntax changes. The only change left for this backport is for some logging fixes, which still
would be nice to have so that debug logs are not confusing.
While debugging on dual-stack KIND setup, ovn-trace
failed due to || and && grouping, with this error
msg:
ovntrace|WARN|reg0[7] == 1 && (outport == @a14390016336330567584 &&
(ip4.src == $a8720055785936351439 && ip4.mcast || ip6.src ==
$a8720057984959607861 && (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))):
parsing expression failed (&& and || must be parenthesized
when used together.)
Signed-off-by: vpickard <vpickard@redhat.com>
(cherry picked from commit a57423116175e856cafb455d433a195fc481d0e3)
**- What this PR does and why is it …
=> Bug 1931520: Backport Fix ACL syntax for dual-stack

Dockerfile
We bumped the ovn version to 20.09.0-7.el8fdn to try to fix Bug 1933752 (https://bugzilla.redhat.com/show_bug.cgi?id=1933752) where we would log messages when some NetworkPolicies were used.  However, other NetworkPolicies can cause that version to crash.
So, until we work out how we want to fix the problem, it is safer to revert the change.
=> Bug 1945725: Revert the ovn change to avoid a crash

Dockerfile
Bump OVS version to 2.15-0.9 in order to fix issue to enable IPv6 IPsec for SDN-1523. This package was soak tested in https://github.com/openshift/ovn-kubernetes/pull/471
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> Dockerfile: bump OVS to openvswitch2.15-2.15.0-9

go-controller/pkg/ovn/policy.go
4.7 back-port of:
-----------------
The updateFunc in handlePeerService when a service is updated casts the
previous / old objects to kapi.Service (instead of pointers). This
may result in a runtime.TypeAssertionError and a crash of kube master
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
/assign @trozet @dcbw 
=> Bug 1947835: Fix service update for policy type assertion

go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go
Back-port PR to 4.7
This patch simplifies ovnkube-node to remove the notion of node IP.
This notion only existed for the iptables rules to be configured
correctly. By utilizing `--dst-type LOCAL` we however don't need
that anymore and can simplify our logic.
=> Bug 1946696: iptables: add filter on node local traffic

go-controller/pkg/ovn/master.go
Logical datapath groups reduce the size of the southbound
database in large clusters. The option is ignored if unsupported
by ovn-northd. ovn-controllers should be upgraded to a version
that supports this option before it is turned on.
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2074 that was pulled into 4.8 as part of https://github.com/openshift/ovn-kubernetes/pull/440
@trozet
=> Bug 1943316: [4.7] master: enable logical datapath groups for OVN >= 20.12

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/testing/mock_lsp.go
To prevent port binding ping-pongs between ovn-controllers, if an
ovnkube-node isn't running or hasn't been able to clear the iface-id
for an old instance of a pod, but the pod has been rescheduled,
request the chassis the pod has been scheduled on.
=> Bug 1947712: pods: bind pod logical switch ports to the node's chassis with requested-chassis

go-controller/pkg/node/OCP_HACKS.go
Fix lint issues with the downstream OCP hack.
=> Bug 1950159: Fix linter errors in OCP Hacks

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/containernetworking/cni/pkg/skel/skel.go, go-controller/vendor/github.com/gogo/protobuf/proto/text_parser.go, go-controller/vendor/modules.txt
Here are the steps I used:
cd go-controller
go list -m all |grep gogo/protobuf
go get github.com/gogo/protobuf v1.3.2
go mod vendor
Add:
github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
in the replace section in go.mod, to make we only use this
version.
go mod tidy
Signed-off-by: vpickard vpickard@redhat.com
(cherry picked from commit 0a2aad5)
=> Bug 1924826: Backport Update gogo/protobuf to v1.3.2.

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/namespace.go
In production, it was observed that NetworkPolicies that select all /
many Namespaces often cause errors in ovn-controller:
error parsing match "reg0[7] == 1 && (ip4.dst == { (..snip..): Syntax error at `$a5585560803499416081' expecting address set name.
This is because we first delete the address set, then delete any network
policies that refer to it.
This defers deletion of the address set until 20 seconds have passed.
Signed-off-by: Casey Callendrello <cdc@redhat.com>
=> Bug 1944121: master: Delay deleting Namespace's address set for 20 seconds

go-controller/pkg/ovn/egressfirewall_dns.go, test/e2e/e2e.go
This is not an automated cherry pick there where some minor merge conflicts in egressfirewall_dns.go and had to disregard everything in /test/e2e/e2e.go
Currently when adding EgressFirewalls with 5 or so dnsNames (observed
with 5 dnsNames) it is probable that a deadlock will occur.
thread #1 calls (e *EgressDNS) Add() grabs lock e.lock and calls
signalAdded(dnsName) and continues looping to the next dnsName calling
(e *EgressDNS) Add() grabbing e.lock and trying to write to the channel
thread #2 recieves the signalAdded(dnsName) and is waiting to grab
e.lock in updateEntry for name
thread #1 cannot write to the channel because the channel blocks waiting
for the write and holds e.lock
thread #2 cannot continue with updateEntryForName() because it is wating
for e.lock
Solve this problem by …
=> [releaser-4.7] Bug 1950131: fix deadlock in EgressFirewall DNS code

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/ovn/master.go
When the master is terminated instead of just exiting, give leader
election a chance to release the leader lock so another ovnkube
master can grab it while this instance is down.
(cherry picked from commit 9c1d0c193d736d2d8180e5b0e5dc3c87f0b9ff03)
=> Bug 1951064: master: cancel leader election on exit

go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
Service targetPort is a selector for the endpoints/endpointslices
controller to create the endpoints based on that container port name.
It is not meant to be used in the Service implementation.
The relation is ServicePort.Name - EndpointPort.Name, however,
ServicePort.Name is only required for multiple ports and it may be empty.
If the endpoint matches the service and there is no name,
that means that is a single port service and there is only one endpoint.
=> Bug 1953169: endpoint slice controller doesn't handle services target port correctly

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/types/types.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
This reverts commit b77e0e3027d905089daa50bcd2731e9b4498079e and pulls back in external gateway support via hybrid overlay.
=> Bug 1952262: Revert "removing the hybrid overlay externalGW code"

go-controller/pkg/ovn/gateway_init.go
For each node, we add pbrs for each node subnet. When syncing pbrs, we purge
not expected rules. In case of dual stack, we are mistakenly purging the
rules that were added because of the subnet belonging to the other ip
family.
Here, we compare the family of the nexthop with the family of the new
nexthop and apply the logic only if they match.
=> Bug 1950471: Purge only the lprs with nexthops of the same family of new nexthop

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/types/types.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/ovn/egressfirewall_dns.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Adds back external gw code via hybrid overlay. Also includes various missing unit test fixes downstream that were causing lint and formatting issues.
=> Bug 1956318: Revert "removing the hybrid overlay externalGW code"

go-controller/pkg/cni/bandwidth.go, go-controller/pkg/cni/bandwidth_test.go, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/utils.go
When the cni is not chained with multus, the container runtime invokes
the check command. The check command checks the bandwith requirements
annotated on the pod, vs what's being configured in ovs. Ovs sets
ingress_policing_rate=0 by default, so the check always fails.
Here, when ingress_policing_rate is 0, we treat it as not found.
Cherry pick of https://github.com/ovn-org/ovn-kubernetes/pull/2182
=> Bug 1949582: CNI cmdCheck: treat ingress_policing_rate=0 as not found

go-controller/pkg/ovn/policy.go
Profiling indicated a lot of contention on this lock. We should release
it before we commit our changes to OVN.
Signed-off-by: Casey Callendrello <cdc@redhat.com>
This is a backport of ovn-org/ovn-kubernetes#2205
=> Bug 1959058: policy: release LSP lock before adding pods to default-deny portgroups.

go-controller/pkg/ovn/controller/services/utils.go
In LGW mode the special SGW Hairpin Masquerade IP
is being used in the loadbalancer where it should not
be.  This PR ensures we only use the Masquerade IP
In shared GW when adding backends to loadbalancers
that result in the hairpin traffic back to the node.
=> Bug 1957039: Fix pod -> svc -> host LGW flow

go-controller/pkg/ovn/pods.go, go-controller/pkg/testing/mock_lsp.go
To prevent port binding ping-pongs between ovn-controllers, if an
ovnkube-node isn't running or hasn't been able to clear the iface-id
for an old instance of a pod, but the pod has been rescheduled,
request the chassis the pod has been scheduled on.
4.6 backport of https://github.com/openshift/ovn-kubernetes/pull/500
=> Bug 1950434: [4.6] pods: bind pod logical switch ports to the node's chassis with requested-chassis

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go
When we have this configuration enabled, there should be no SNAT entry
for the pod subnet on the GR. Instead there should be per pod SNAT
entries added. On upgrade or enabling this feature we were failing to
remove any previous SNAT entries here.
(cherry picked from commit a9166cb0a998dd1d9c887269ec74ce2680bf6ff6)
=> Bug 1947097: [4.7z] Ensure no SNAT on GR for DisableSNATMultipleGws

go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/controller/services/utils_test.go
Cherry-pick from https://github.com/openshift/ovn-kubernetes/pull/515
Service targetPort is a selector for the endpoints/endpointslices
controller to create the endpoints based on that container port name.
It is not meant to be used in the Service implementation.
The relation is ServicePort.Name - EndpointPort.Name, however,
ServicePort.Name is only required for multiple ports and it may be empty.
If the endpoint matches the service and there is no name,
that means that is a single port service and there is only one endpoint.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> Bug 1956270: service controller should not use the target-port

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ebay/go-ovn/acl.go, go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/common.go, go-controller/vendor/github.com/ebay/go-ovn/load_balancer.go, go-controller/vendor/github.com/ebay/go-ovn/logical_router.go, go-controller/vendor/github.com/ebay/go-ovn/logical_router_policy.go, go-controller/vendor/github.com/ebay/go-ovn/logical_switch_port.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/go-ovn/ovnnotify.go, go-controller/vendor/github.com/ebay/go-ovn/test_common.go, go-controller/vendor/modules.txt
It includes https://github.com/eBay/go-ovn/pull/148, which ensures no
missed deletion events during a reconnection.
This was missed in https://github.com/openshift/ovn-kubernetes/pull/528
=> Bug 1952819: Bump the go-ovn version to f0122836cc35fcadf72de8698b26157c5a42a9f8

go-controller/pkg/ovn/address_set/address_set.go
newOvnAddressSets returns a concrete type, that gets assigned to an
interface. This makes the interface not being nil (even if the backing
value is).  In particular, having
nsInfo.addressSet, err = oc.createNamespaceAddrSetAllPods(ns)
called twice would result in having the interface not being nil but the
value behind it being nil and it will make sequent use of
nsInfo.addressSet refer to a nil value.
=> Bug 1958958: NewAddressSet: return nil in case of error

go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/service_tracker_test.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/controller/services/utils_test.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/util/ovs.go
- Implement a services cache to avoid calling remove vip so many times in OVN for different load balancers which may not have the vip on them.
- Fixes leaving around unidling VIPs in OVN accidentally.
- Fixes initial sync of ovnkube-master starting, where it would not repair/resync certain services. This would result in some services not working across the cluster on ovnkube-master restart.
- Batches OVN service transactions: Large scale service operations result in many ovn-nbctl commands. This is addressed by batching as many as possible into a single nbctl transaction.
=> Bug 1956955: Reduces number of OVN operations in services #2201

go-controller/hybrid-overlay/pkg/controller/node_linux.go
We are intentionally ignoring learn when something critical to the learn
flow changes like pod ip, mac, exgw annotations. However, once we sync
flows we should reset the pod to learn the flow on the next sync.
However, we were only resetting pods for which we found flows already in
OVS. This fixes that by restting ignoreLearn for all pods as long as we
have a successful sync.
=> Bug 1962392: CARRY: fix missed learn for hybrid exgw

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/util/kube.go
cherry-picked three commits from upstream ovn-kube to apply cleanly and solve the problem 
[c37c866f78765dfe15fb06943ead64d0723fedba](https://github.com/ovn-org/ovn-kubernetes/commit/c37c866f78765dfe15fb06943ead64d0723fedba) -  change the egressFirewall to use a cli flag instead of dynamically turn
on from watching CRDs
[2e870eb23259c71216bb56895d63394d84166527](https://github.com/ovn-org/ovn-kubernetes/commit/2e870eb23259c71216bb56895d63394d84166527) - Remove node-side egress IP clients to help everything apply cleanly
[f9af29bbd67dda81d7091c9651cef0cb3b1ff895](https://github.com/ovn-org/ovn-kubernetes/commit/f9af29bbd67dda81d7091c9651cef0cb3b1ff895) - remove the CRD watch and related bits as they are no longer needed
**- Special notes for …
=> Bug 1954773: adding cli flag for egressfirewall and removing CRD watcher

go-controller/pkg/ovn/ovn.go
Egress IP initializes a "watcher" which health checks connectivity to egress
nodes every 5 seconds. This is done in its sync function. However, due to a
bug in the state initialization in WatchEgressNodes we don't set the
different egress node fields correctly in our ADD func which screws up the health
check detection mechanism upon a ovnkube-master restart.
Essentially it does like this:
1) egress setup is made
2) there's a problem with connectivity to the egress node(s)
3) ovnkube-master is restarted
Once step 3) is made: it is expected that ovnkube-master will perform
health checks continously and detect when the connectivity in step 2) is
back up. However because of this problem that is not the case and even
if further connectivity is successful, we never flag the node as such in
our …
=> [release-4.7] Bug 1959737: Fix: egress IP route health check detection state on restart

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_test.go
we have,
external_ids        : {name=kube-system_v4}
external_ids        : {name=default_v4}
external_ids        : {name=default.access-web.egress.3_v4}
external_ids        : {name=kube-public_v4}
external_ids        : {name=ovn-kubernetes_v4}
external_ids        : {name=default.access-web.ingress.0_v4}
external_ids        : {name=kube-node-lease_v4}
external_ids        : {name=default.access-mysql.ingress.0_v4}
external_ids        : {name=default.access-web.egress.0_v4}
so, there is only one part of key=value in `external_ids` and this
results in ForEachAddressSet() not calling the iterator function.
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>
**- Description for the …
=> Bug 1956980: [release-4.7] fix ForEachAddressSet() as it is not calling the callback functions

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy_test.go
This is a slight modification for the ACL Audit Logging feature
Currently for every gress rule it is impossible to tell what
NS the rule is in just by the name of the ACL this patch
fixes that by naming the ACL
`<Namespace>_<NetworkPolicy_Name>_<rule#>`
Adding the rule number fixes the case where we have multiple
gress rules defined in a single network policy.
(Backport of upstream https://github.com/ovn-org/ovn-kubernetes/pull/2207 )
=> Bug 1955783: Add Namespace and rule Number to ACL name

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
With OVN-kubernetes we set the MTU of the pods to be 100 less than
physical network MTU. This becomes a problem when something outside of
the cluster tries to access a pod (local or shared gw mode) or via
service (shared gateway mode) with a packet larger than the pod MTU.
The packet will be dropped by OVS because OVS will not re-fragment
at the lower pod MTU when trying to send the packet to the pod.
This solves the problem by checking packet size for packets destined
towards OVN. If they are > pod MTU + 12 bytes (eth overhead) they are
forwarded to the kernel. The kernel has a route for pods via mp0
interface, which is a -100 byte MTU interface. This means the kernel
will automatically send ICMP needs frag back to the client.
For services, we add back the PREROUTING iptables rule to …
=> Bug 1927047: Handling packet sizes greater than pod MTU

go-controller/pkg/ovn/ovn.go
**FYI: this was a "semi-smooth" back-port (i.e: I had to resolve some conflicts). Please pay special attention to that when reviewing.** 
----------------------
If a pod add fails in ovnkube-master, and there is no subsequent update
event for the pod we never try to add it again and CNI will just
continuously fail. A prime example of this is if a pod is added for a
node, who has not yet registered with ovnkube-master by setting its L3
gateway config.
This patch adds a goroutine which will run and check to see if there are
any pods that need retry who have been sitting for longer than a minute.
If such pods exist, the goroutine will attempt to addLogicalPort for
them.
Co-Authored-by: Dan Williams <dcbw@redhat.com>
**- What …
=> [release-4.6] Bug 1966280: Adds reconciliation for hanging pod adds

go-controller/pkg/cni/bandwidth.go, go-controller/pkg/cni/bandwidth_test.go, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/utils.go
When the cni is not chained with multus, the container runtime invokes
the check command. The check command checks the bandwith requirements
annotated on the pod, vs what's being configured in ovs. Ovs sets
ingress_policing_rate=0 by default, so the check always fails.
Here, when ingress_policing_rate is 0, we treat it as not found.
Manual cherry pick of https://github.com/openshift/ovn-kubernetes/pull/522
=> Bug 1962819: CNI cmdCheck: treat ingress_policing_rate=0 as not found

go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go
The function was assuming dualstack, which was causing "Failed to find
node ips for gateway" error to appear over 14k times in our scale
test runs downstream.
=> Bug 1970068: Fixes getNodeIPs assuming dualstack

go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
It turns out what the system reports for maximum arguments may not be
the real amount of arguments that are usable in a shell. Different
kernels calculate it differently, but the gist is that the only reliable
way to know is to test for it. This patch does an initial search based
on the given max args in the kernel to find the actual usable amount.
The search is only done one time during initialization, so it shouldn't
impact performance.
=> Bug 1956955: Batching: Fixes finding maximum bash arguments

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/helper_linux.go
As seen in the associated bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1970779#c3 , there can be situations where the egress IP related code for finding the default IP address can sometimes pick up the virtual IPs on bare-metal clusters. Hence back-port the following commit which uses `getNetworkInterfaceIPAddresses` instead and has dedicated code to avoid that: https://github.com/openshift/ovn-kubernetes/blob/master/go-controller/pkg/util/net_linux.go#L370-L376
=> [release-4.7] Bug 1970779: Remove getDefaultIfAddr and use getNetworkInterfaceIPAddresses

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/util.go
Backport to fix multicast on 4.6
Commit 40a90f06644a removed the multicast deny port group and used
instead the cluster port group.  However, this breaks pod-to-pod
multicast when pods reside on different nodes.  That is because OVN ACLs
are applied on all logical switch ports, including logical switch ports
connected to router ports.
Hence, an ACL of the form "if ip.mcast then deny" applied on the
clusterPortGroup will drop all multicast traffic that would normally be
routed by the cluster router even when multicast is allowed for a
namespace.
Instead, add a new (smaller) cluster wide group that only contains the
node logical switch ports connected to the cluster router.  This allows us
to define two allow ACLs for multicast traffic from/to node switches to/from
cluster router, therefore …
=> Bug 1966833: BACKPORT Add a cluster-wide group with node ls-to-cluster-router ports.

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/util/ovs.go
In older kernels like RHEL 7, OVS does not support chk pkt length in
kernel datapath. This will cause all packets hitting these flows to go
to userspace, which is the majority of OVN destined ingress traffic into
the node. This will result in severe performance degradation. To avoid
this, detect and disable using these flows if the kernel datapath does
not support the action.
Note this will result in these nodes not being able to handle packets
larger than pod MTU and send ICMP frag needed, but the trade off vs.
performance impact is worth it.
(cherry picked from commit 7e832266167b518fdb9f6eba63623e7753e753f5)
=> Bug 1961506: Detect if OVS supports check pkt length

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovn-setup.yaml.j2, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/util/util.go
This PR cherry-picks commits needed for supporting allow-from-router feature to apply network policy to router endpoints when the endpoint publishing strategy is HostNetwork.
=> Bug 1942604: Allow-from-router network policy support for ovn-kubernetes

go-controller/pkg/ovn/master.go
This commit adds the previously missing v6 management interface
address to the host network policy address set.
(cherry picked from commit 255118c1031e9518bd04b111767f5e3ba8af0c5f)
=> Bug 1985512: Add v6 management interface address for host network policy

go-controller/pkg/ovn/ovn.go
Fixes another case where update pod and adding pods to retry could race. Also a trivial fix to skipping the pod when it is not scheduled.
=> Bug 1986443: Fix pod handler race downstream

go-controller/pkg/util/ovs.go
There are still bash errors for "too many args" which stem not from the
number of arguments but a combination of number of args and total length
of the args. This sets the maximum line length to 100k, which is less
than the default maximum of 130k (to be safe).
(cherry picked from commit 0f80eea1cd94bde568daa659869f7194baf03d9b)
This is the last fix that went in for batching commands that did not make it into 4.8.
=> Bug 1986573: Declare a maximum line length for batching

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy_test.go
backport of #530 ; we only handled NPs with multiple `ipBlock` entries if they were written in a particular way
/hold
Are there upgrade concerns here? Will this change leave stray ACLs around? Will they ever get cleaned up? (EDIT: Yes, Yes, No; fixed by second commit)
=> Bug 1967132: policy: handle NetworkPolicies single "from" multiple "ipBlock"

Dockerfile
Manual cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/591 because automatic cherry-pick failed due to DockerFile conflicts.
=> [release-4.7] Bug 1991445: Bump OVN to 20.12.0-140.el8fdp

Dockerfile
@abhat @alexanderConstantinescu @trozet 
Relevant changes include:
- [controller: Improve ct zone handling](http://patchwork.ozlabs.org/project/ovn/list/?series=256319&archive=both&state=*
) series which reduces the amount of work ovn-controller does when processing ct_zone changes.
- [northd: do not configure ECMP routes with wrong next-hop](https://github.com/ovn-org/ovn/commit/9cd64780d89c4acd2ae0c12693be66962ada97cd) for [rhbz#1978796](https://bugzilla.redhat.com/show_bug.cgi?id=1978796)
- [ofctrl: Add memory usage statistics](https://github.com/ovn-org/ovn/commit/7670db7ae137e97509f73cc48a5d792a1801a5bf)
Going to fail until mirrors sync and the -12 RPM becomes available in a few hours.
=> Bug 1991793: [4.9] bump OVN to ovn21.09-21.09.0-12.el8fdp

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
This PR is a cherry-pick to backport [818e04b3](https://github.com/openshift/ovn-kubernetes/commit/818e04b34507907cc09cc49eed611c4b9880bcf9) and [902c93a8](https://github.com/openshift/ovn-kubernetes/commit/902c93a8c7a8c6dbcaa46b36bc285d51382e6b6f) to 4.8.z, so that it is not required anymore for ovnkube-trace to have the `ip` package to be installed in the source/destination pods
none
1. start a 4.8 cluster with this patch
2. Follow https://access.redhat.com/solutions/5887511 with a source or destination pod that don't have iproute package on it (e.g. use an nginx image: `k create deploy hello-world --image nginxinc/nginx-unprivileged --replicas 3`)  …
=> Bug 1985957: Backport ovnkube-trace requires ip package to be installed to 4.8

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/types/const.go
UseCase: During upgrades, when the ovnkube pod is deleted and
before/while it gets recreated if a new pod request comes, it
will fail.
When node networking is down, we should not allow pods to be created
on that node. This PR fixes this by adding a taint on the node with
the NoSchedule effect when the ovnkube pod receives a SIGTERM and then
removes the taint when the ovnkube pod finishes setting up networking
and initializing the CNI config.
(cherry picked from commit 7e958e0aa8f3ef3816bd9a1f6ac56a3082598807)
=> Bug 1943334: Taint node with NoSchedule when ovnkube pod is down

go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
In GetPortAddresses, we check if we have both PortMAC and IP for
the port. If not we return nil for both values. While this works
for normal ports, for the HBO ports which don't have IPs for
the int-<node> interface, we will always hit this condition and
return an empty PortMAC which in turn triggers the lsp-add even
if the portMAC already exists.
When we have an external entity updating the node object, the
watcher triggers handleOverlayPort and we keep hitting this
condition.
Let's remove the "len(addresses)<2" check since its not needed
for HBO and in normal pod port case, pods.getPortAddresses already
handles the case for empty podMac or podIPs. This way when portMAC
is set but not the IPs, we will still return the portMAC and the
respective code paths handle it as needed. …
=> Bug 1989615: Fix GetPortAddresses for HBO

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go
While providing ipv6 addresses in these fields into the
nbctl calls, it fails with the error "unexpected ":" parsing string"
during hbo pod deletion. 
`This leads to stale bfd entries that don't get cleaned up.`
(cherry picked from commit a9363911ea90102b00871a7154b4b6f8c4b5a857)
=> Bug 1994647: Add quotes around nexthop and dst-ip fields

go-controller/pkg/ovn/address_set/address_set.go
Function was accidentally using the non-hashed names.
=> Bug 1997114: Fixes ensure address set

go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/loadbalancer/lb_cache.go, go-controller/pkg/ovn/loadbalancer/lb_cache_test.go, go-controller/pkg/ovn/master.go
When a node gets deleted, the logical switch and
gateway router get removed first. However we do
not update the LBCache and this causes dependency
failures during deletion leaving behind wrong ip->vip
pairing in the lbs.
When the pods on this node go away, ensureLBs
gets triggered and it tries to update endpoints across
load balancers. This set load_balancer command is
batched with ls-lb-del & ls-lr-del commands to remove
association of the lbs from the removed switches and
routers. These commands fail together because the switches
and routers are not present in ovn.
This PR updates the LBcache as soon as we remove the
routers and switches.
(cherry picked from commit 6de80e8dbb2c865209d6dffd32cd4d93eb46b77e)
=> Bug 1998146: Fix lb delete during node deletion

Dockerfile
- optimizations to loadbalancer logical flow creation in northd (reduced latency and iteration time)
- optimized hashing in northd (reduced latency and iteration time)
- additional northd stopwatches for debugging iteration times
- two northd perf optimizations to avoid multiple identical datapath groups
- optimization to JSON serialization improving all inter-component communication
=> Bug 1999852: bump OVN to ovn21.09-21.09.0-18.el8fdp

Dockerfile
- enables use of database relays
- JSON-RPC performance enhancements
- per-cpu upcall dispatch (OoO fragment fix)
- record/replay of database transactions for testing
- support for setting election timer at database creation
=> Bug 2000721: bump OVS userland to openvswitch2.16-2.16.0-6.el8fdp

go-controller/pkg/ovn/ovn.go
Currently we call addPodExternalGW from both ensurePod and
addLogicalPort. If ensurePod is called with addPort=false
from the UpdatePodHandler, it will keep trying to call
addPodExternalGW to add routes and policies repeatedly
for the same pod. During exgw pod creation, we see same routes
and policies getting added 3 times in a row.
Note that https://github.com/ovn-org/ovn-kubernetes/pull/2337
fixed this by adding a check into addGWRoutesForNamespace to
return if routes already exist for the pod, but this comes
later in the code flow. Its better to not call addPodExternalGW
at all unless needed. `This would save time and help with
pod latency issues specially at scale.` …
=> Bug 1986946: Fix ensurePod to call addPodExternalGW only for annotation updates

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Fixes #1997438, where any update to an EgressFirewall (including a cluster upgrade) causes an error as soon as more than one ACL UUID are retrieved and parsed, leading to the EgressFirewall eventually not being correctly set. This is easily reproducible in local gateway mode.
This patch proposes the following changes:
- Added "--format=table" to all "ovn-nbctl find" calls in order to have entries separated by a newline character and not by two newline characters, which is the default if "--format" is not specified;
-  Replaced calls to "Strings.Split" on "sep=\n" with a safer "Strings.Fields", which splits based on whitespace characters and trims them too.
(cherry picked from commit 024091e07410ee0981ec2e9a3888980a26e2d295)
=> Bug 1997438: egressfirewall not set after upgrade

go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/libovsdb/client.go
Under heavy load, monitor gets dropped silently and we stop receiving `update` messages from ovsdbserver. This leads to stale cache and inconsistency with what's in the DB leading to transaction errors. While this is originally a ovsdbserver bug, a workwround fix here would be to trigger reconnect to recreate the monitor and start receiving update messages, when a transaction error occurs.
Co-Authored-By: trozet@redhat.com
=> Bug 1998614: Ensure client handling of canceled/dropped OVSDB monitor

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go
Make Iptables rule for every ExternalIP or ingress IP, this will
result in shortcirciting of node -> ExternalIP service traffic
Remove code to manage host routes
Ensure we cleanup any stale routes on upgrade
=>  [release-4.7] Bug 1988495: Fix LocalGatway ExternalIP

go-controller/pkg/config/config.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/ovndbmanager/ovndbmanager_test.go
We may want to update the ovn election timers, and in order to do that
we need to act asynchronously because the election must be completed and
the change must be performed on the leader node. So, we add two optional
parameters for the desired election timer and we change that as part of
the db checker timer.
=> Bug 1976399: DBChecker: reconcile the election timeouts when specified

docs/design/external_traffic_policy.md, go-controller/pkg/factory/types.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/util/kube.go, test/e2e/e2e.go, test/e2e/util.go, test/scripts/e2e-cp.sh
This PR pulls in the code needed to land the externalTrafficPolicy feature. It adds a commit to deal with the fact that the smartnicv2 code has not made it downstream yet. That commit should be dropped before the next large merge of Upstream OVN-K into downstream.
=> Bug 1903408: Merge externalTrafficPolicy ONLY

go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/libovsdb/client.go
Under heavy load, monitor gets dropped silently and we stop receiving update messages from ovsdbserver. This leads to stale cache and inconsistency with what's in the DB leading to transaction errors. While this is originally a ovsdbserver bug, a workwround fix here would be to trigger reconnect to recreate the monitor and start receiving update messages, when a transaction error occurs.
=> Bug 2001363: [4.8z] Ensure client handling of canceled/dropped OVSDB monitor

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/config/config.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_smartnic_test.go, go-controller/pkg/ovn/pods.go
Fixes #1995335
Newly added option [1] allows to distinguish new vs old logical
ports for recreated pod with the same name, thus making "ovn-installed"
option reliable again [2].
1. Add "iface-id-ver" option to logical and OVS ports
[Upgrade][master] add iface-id-ver only for newly created Ports,
no ovn version check, since if iface-id-ver is not enabled in ovn, it will be just ignored
[Upgrade][node] no additional actions are needed, because existing Interfaces don't need
iface-id-set since it won't be set in master. Ovn support for iface-id-ver will be checked
during cni server creation
2. Add OvnKubeNodeConfig option "ovn-iface-id-ver-disabled" to manually
disable this feature for older ovn versions
3. Change test mock that checks ovs add-port command
4. Add common function to compose …
=> Bug 1995335: Add "iface-id-ver=${POD_UID}" tuple to the external-ids of logical and OVS ports

go-controller/pkg/ovn/ovn.go
In the update pod logic, we pass the current pod event to
addLogicalPort. In addLogicalPort we assume that if the annotations
exist for the pod mac/ifaddr, then we use those and do not update
annotations on the pod. This assumption is invalid, because this event
may not be the current state of the pod. In other words we could have a
situation where:
1. A pod add event comes we annotate with 10.0.0.2, assume OVN execute
failure
2. Before the annotate is done, the pod is modified in some other way
signaling another pod update event
3. A pod update event comes for 2, the pod is annotated with 10.0.0.3
because this was an update to the original pod, before it was
annotated with 10.0.0.2, assume OVN execute failure
4. A pod update event comes for 1, since annotations existed, nothing is …
=> Bug 2002372: Fixes misuse of pod annotations during update event

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
(backport of downstream PR 716 for master branch)
Fixes #2001641, which is a clone of #1997438, where any update to an EgressFirewall (including a cluster upgrade) causes an error as soon as more than one ACL UUID are retrieved and parsed, leading to the EgressFirewall eventually not being correctly set. This is easily reproducible in local gateway mode.
This patch proposes the following changes:
- Added "--format=table" to all "ovn-nbctl find" calls in order to have entries separated by a newline character and not by two newline characters, which is the default if "--format" is not specified;
- Replaced calls to "Strings.Split" on "sep=\n" with a safer "Strings.Fields", which splits based on whitespace characters and trims them too. …
=> [release-4.8] Bug 2001641: egressfirewall not set after upgrade

go-controller/pkg/cni/helper_linux.go
Due to https://bugzilla.redhat.com/show_bug.cgi?id=2003193 where crio
is not cleaning up leftover veths/netns...overtime OVS CPU climbs to
100% and performance degrades in the node. This ensures OVN CNI cleans
up the ports rather than relying on kublet/crio.
=> Bug 2003195: Ensure host interfaces are deleted by CNI

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_dns.go, test/e2e/e2e.go, test/e2e/unidling.go
(backport of upstream https://github.com/ovn-org/ovn-kubernetes/pull/2471)
- Add a new channel named "deleted" to the EgressDNS struct, so that the domain name (if any) of a newly deleted EgressFirewall can be passed over to the Run() loop, which keeps track of DNS records and updates them as soon as they expire. This prevents inconsistencies between current EgressFirewalls and corresponding DNS records, which eventually led to a panic in a customer case.
- The aforementioned panic is now avoided by checking for the presence of the given DNS domain to delete in a map, before proceeding to update its (pointer) value.
- Fix type assertion when deleting EgressFirewalls, which resulted in DNS records never being deleted from the Run() loop.
(- Make error messages start with lowercase letters …
=> Bug 2000057: panic after EgressFirewall deletion and DNS record expiration

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
(backport of downstream PR 716 from master branch)
Fixes #2001641, which is a clone of #1997438, where any update to an EgressFirewall (including a cluster upgrade) causes an error as soon as more than one ACL UUID are retrieved and parsed, leading to the EgressFirewall eventually not being correctly set. This is easily reproducible in local gateway mode.
This patch proposes the following changes:
- Added `--format=table` to all `ovn-nbctl find` calls in order to have entries separated by a newline character and not by two newline characters, which is the default if `--format` is not specified;
- Replaced calls to `Strings.Split` on `sep=\n` with a safer `Strings.Fields`, which splits based on whitespace characters and trims them too. …
=> [release-4.7] Bug 2001998: egressfirewall not set after upgrade

go-controller/pkg/ovn/ovn.go
The code was using the initially stored pod object to determine if the
pod was scheduled or not, rather than the current state of the pod.
=> Bug 2002010: Fixes skipping pods accidentally in retry

go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/libovsdb/client.go
Under heavy load, monitor gets dropped silently and we stop receiving update messages from ovsdbserver. This leads to stale cache and inconsistency with what's in the DB leading to transaction errors. While this is originally a ovsdbserver bug, a workwround fix here would be to trigger reconnect to recreate the monitor and start receiving update messages, when a transaction error occurs.
=> Bug 2001364: [4.7z] Ensure client handling of canceled/dropped OVSDB monitor

go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go
Background to this PR:
- #683 fixed a problem w.r.t syncing the join IP for each node upon a ovnkube-master restart
- it however introduced the regression: https://bugzilla.redhat.com/show_bug.cgi?id=1999896
- Hence #707 reverted it.
- Bug 1998423: kube master don't fail trying to cache same GW LRP IPs as already exist #705 fixed the regression on master
- Hence we now have to revert the revert (#707) and back-port the complete fix Bug 1998423: kube master don't fail trying to cache same GW LRP IPs as already exist #705
/assign @abhat @dcbw
=> [release-4.7] Bug 2001543: fix reserve joinSwitch LRP IPs

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go
Make Iptables rule for every ExternalIP or ingress IP, this will
result in shortcirciting of node -> ExternalIP service traffic
Remove code to manage host routes
Ensure we cleanup any stale routes on upgrade
=> Bug 1988512: [release-4.6] Fix LGW externalIP

go-controller/pkg/ovn/master.go
When the master is restarted, all the nodes are fed using
both a fetch of existing nodes and by the add node event.
In case the node already had subnet annotations, we were
updating the subnets allocated metric again. This commit
checks if new subnets were allocated and only then calls
the code to update metrics associated with allocated
subnets.
(cherry picked from commit 4de9fa6a60e4f103939a880f1a0c5a6beb5d8afe)
=> [release-4.8] Bug 1999638: Fix duplicate incrementing of subnet allocation metric

go-controller/pkg/ovn/egressfirewall_dns.go, test/e2e/unidling.go
(backport from https://github.com/openshift/ovn-kubernetes/pull/741)
- Added a new channel named "deleted" to the EgressDNS struct, so tha…t the domain name (if any) of a newly deleted EgressFirewall can be passed over to the Run() loop, which keeps track of DNS records and updates them as soon as they expire. This prevents inconsistencies between current EgressFirewalls and corresponding DNS records, which eventually led to a panic in a customer case.
- The aforementioned panic is now avoided by checking for the presence of the given DNS domain to delete in a map, before proceeding to update its (pointer) value.
(- Made error messages start with lowercase letters to comply with style guidelines, as a CI test was failing)
This patch fixes bug BZ 2004488.
Signed-off-by: Riccardo Ravaioli …
=> [release-4.8] Bug 2004488: panic after EgressFirewall deletion and DNS record expiration

go-controller/pkg/ovn/ovn.go
Fix ensurePod to call addPodExternalGW only for annotation updates
Currently we call addPodExternalGW from both ensurePod and
addLogicalPort. If ensurePod is called with addPort=false
from the UpdatePodHandler, it will keep trying to call
addPodExternalGW to add routes and policies repeatedly
for the same pod. During exgw pod creation, we see same routes
and policies getting added 3 times in a row.
Note that https://github.com/ovn-org/ovn-kubernetes/pull/2337
fixed this by adding a check into addGWRoutesForNamespace to
return if routes already exist for the pod, but this comes
later in the code flow. Its better to not call addPodExternalGW
at all unless needed. This would save time and help with
pod latency issues specially at scale.
Signed-off-by: Surya Seetharaman …
=> [release-4.8] Bug 1996739: Fix ensurePod to call addPodExternalGW only for annotation updates

go-controller/pkg/ovn/ovn.go
In the update pod logic, we pass the current pod event to
addLogicalPort. In addLogicalPort we assume that if the annotations
exist for the pod mac/ifaddr, then we use those and do not update
annotations on the pod. This assumption is invalid, because this event
may not be the current state of the pod. In other words we could have a
situation where:
1. A pod add event comes we annotate with 10.0.0.2, assume OVN execute
failure
2. Before the annotate is done, the pod is modified in some other way
signaling another pod update event
3. A pod update event comes for 2, the pod is annotated with 10.0.0.3
because this was an update to the original pod, before it was
annotated with 10.0.0.2, assume OVN execute failure
4. A pod update event comes for 1, since annotations existed, nothing is …
=> Bug 2005357: [4.8z] Fixes misuse of pod annotations during update event

go-controller/pkg/ovn/ovn.go
The code was using the initially stored pod object to determine if the
pod was scheduled or not, rather than the current state of the pod.
=> Bug 2005464: [4.8z] Fixes skipping pods accidentally in retry

go-controller/pkg/ovn/ovn.go
In the update pod logic, we pass the current pod event to
addLogicalPort. In addLogicalPort we assume that if the annotations
exist for the pod mac/ifaddr, then we use those and do not update
annotations on the pod. This assumption is invalid, because this event
may not be the current state of the pod. In other words we could have a
situation where:
1. A pod add event comes we annotate with 10.0.0.2, assume OVN execute
failure
2. Before the annotate is done, the pod is modified in some other way
signaling another pod update event
3. A pod update event comes for 2, the pod is annotated with 10.0.0.3
because this was an update to the original pod, before it was
annotated with 10.0.0.2, assume OVN execute failure
4. A pod update event comes for 1, since annotations existed, nothing is …
=> Bug 2005391: [4.7z] Fixes misuse of pod annotations during update event

go-controller/pkg/node/gateway_init.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
When node addresses are allocated through DHCPv6 IA_NA, they might get
a /128 prefix address. These node addresses are set on the gateway
router port as well. OVN routers infers on-link routes from subnet
information on the address itself. Since /128 addresses are not on a
subnet, cluster traffic is routed through the node gatway instead of
directly.
Note that OVN does not support learning routes from ICMPv6 route
advertisement and does not support adding on-link static routes.
This patch infers the subnet of the interface looking at the node
routing information and replaces the /128 prefix with the subnet
prefix.
(cherry picked from commit 1db8f65a29d7e917de4007a613dd1c21c6f10c19)
=> [release 4.8] Bug 1994624: Infer subnet for node /128 IPv6 addresses

go-controller/pkg/ovn/master.go
When the master is restarted, all the nodes are fed using
both a fetch of existing nodes and by the add node event.
In case the node already had subnet annotations, we were
updating the subnets allocated metric again. This commit
checks if new subnets were allocated and only then calls
the code to update metrics associated with allocated
subnets.
(cherry picked from commit 4de9fa6a60e4f103939a880f1a0c5a6beb5d8afe)
(cherry picked from commit 25f0783593797385eea0e6659ca24490169cca0d)
=> [release-4.7] Bug 2006159: Fix duplicate incrementing of subnet allocation metric

go-controller/pkg/ovn/egressgw.go
When adding routes to pod, we fail inside the inner loop returning an
error. What happens is that if the pod has two ip addresses, and the gw
is set only for the second address, the function will mistakenly return
an error.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
(cherry picked from commit d2e05937f75c067bee3de3b2cdbea9a554116da2)
=> Bug 1986708: Add routes for pod: fail only after checking all the gw addresses / ips

go-controller/pkg/ovn/ovn.go
The code was using the initially stored pod object to determine if the
pod was scheduled or not, rather than the current state of the pod.
=> Bug 2005468: [4.7z] Fixes skipping pods accidentally in retry

go-controller/pkg/ovn/pods.go, go-controller/pkg/util/net.go, go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/logical_switch_port.go, go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go, go-controller/vendor/github.com/ebay/go-ovn/port_group.go
LSPGet() already returns the LSP's Options so just copy them
instead of calling LSPGetOptions() which has to lock the go-ovn
cache and look up the LSP.
Second, change the after-OVN-execute LSPGet() to LSPGetUUID()
after reading the UUID from the OVN execute response. go-ovn
uses the UUID as a cache index, so LSPGetUUID() is much faster
than getting an LSP by name which requires walking the cache
row-by-row.
Third, eliminate the LSPGet() that GetPortAddresses() does.
We already know the addresses from the first LSPGet() so we
only need to parse them. If the port didn't exist in the
first place, we know there are no addresses to parse so
don't even bother.
Finally, don't repeatedly access two levels of maps to get the
cache row when building a LSP object. Micro-benchmarks
indicate that's …
=> pods: remove unnecessary LSPGet() calls

Dockerfile
- [[ICNI 2.0] Loadbalancer pods do not establish BFD sessions with all workers that host pods for the routed namespace](https://bugzilla.redhat.com/show_bug.cgi?id=2007443)
- [BFD sessions are not created correctly from the parameters of lr-route-add](https://bugzilla.redhat.com/show_bug.cgi?id=2007549)
- [[scale] northd: precompute router load balancer IPs](https://bugzilla.redhat.com/show_bug.cgi?id=1962338)
- [[OVN-SCALE] ovn-controller: OF rule explosion for ACLs with conjunctive matches applied on multiple datapaths](https://bugzilla.redhat.com/show_bug.cgi?id=1944098)
- [[OVN SCALE][ovn-controller] Load_Balancer changes trigger unnecessary additional flow computations](https://bugzilla.redhat.com/show_bug.cgi?id=1978605)
- lflow: Refactor OpenFlow snat hairpin …
=> Bug 2011391: [4.8] bump OVN to 20.12.0-183.el8fdp

Dockerfile
- [ICNI 2.0] Loadbalancer pods do not establish BFD sessions with all workers that host pods for the routed namespace
https://bugzilla.redhat.com/show_bug.cgi?id=2007443
- BFD sessions are not created correctly from the parameters of lr-route-add
https://bugzilla.redhat.com/show_bug.cgi?id=2007549
- [scale] northd: precompute router load balancer IPs
https://bugzilla.redhat.com/show_bug.cgi?id=1962338
- [OVN-SCALE] ovn-controller: OF rule explosion for ACLs with conjunctive matches applied on multiple datapaths
https://bugzilla.redhat.com/show_bug.cgi?id=1944098
- [OVN SCALE][ovn-controller] Load_Balancer changes trigger unnecessary additional flow computations
https://bugzilla.redhat.com/show_bug.cgi?id=1978605
- lflow: Refactor OpenFlow snat hairpin flows [large …
=> Bug 2011402: [4.7] bump OVN to 20.12.0-183.el8fdp

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Performance and scale fixes with pods and multiple external gateways.
=> Bug 2014332: [4.8z] Scale fixes for pods/exgws

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Also includes missing exgw fixes.
=> Bug 2014360: [4.7z] Scale fixes for pods/exgws

go-controller/pkg/ovn/egressgw.go
If a single routeInfo had multiple external routes that matched the
same gateway IP, that routeInfo could be added to the returned list
multiple times. It was only locked once, however.
But deletePodGWRoutesForNamespace() iterates over the list returned
by getRouteInfosForGateway() and calls Unlock() on each element in
the list, which can create an unbalanced locking situation (multiple
Unlocks for a single Lock) in the above situation where a routeInfo
has multiple external routes matching the same gatewayIP.
(cherry picked from commit b5bb0d46d28d742b0e388cdefe0116b70048e432)
=> Bug 2017909: EgressGW: only return unique elements from getRouteInfosForGateway()

go-controller/pkg/ovn/controller/services/utils.go
This is a small fix for the changes done in https://github.com/ovn-org/ovn-kubernetes/pull/2294.
When upgrading to a codebase where there is a per-service load balancer, the
cleanup needs to also account for idling load balancers in the regex.
Co-Authored-By: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit 727e162812bc7daafad899f925299f72883c5961)
=> Bug 2018398: [4.9z] findLegacyLBs to also include idling LBs

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/cni/cnismartnic.go, go-controller/pkg/cni/cnismartnic_test.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/kube/annotator.go, go-controller/pkg/kube/annotator_test.go, go-controller/pkg/kube/kube.go, go-controller/pkg/kube/kube_test.go, go-controller/pkg/kube/mocks/Interface.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/node/node_smartnic.go, go-controller/pkg/node/node_smartnic_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/pod_annotation.go, go-controller/pkg/util/pod_annotation_unit_test.go, go-controller/pkg/util/subnet_annotations_unit_test.go
This PR includes the fixed needed for bug 2022042, including its dependencies.
Needed commits were cherry picked from trozet:fix_downstream_merge.
=> Bug 2022042: [4.9z] Avoid stale annotations by re-subscribing to netlink

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/node_ip_handler_linux.go
This PR includes the fixed needed for bug 2009873, including its dependencies.
Needed commits from trozet https://github.com/openshift/ovn-kubernetes/pull/834
=> Bug 2009873: [4.10.0] Avoid stale annotations by re-subscribing to netlink

go-controller/pkg/node/node_ip_handler_linux.go
Should ErrorCallback from addressManager take place after
stopChan is closed, it is not safe to call sync() because
c.watchFactory is no longer useable [1].
Fortunately, sync() is already called via subScribeFcn as
well as periodically, so removing it from ErrorCallback
is a simple way of resolving this case.
Also fixing a trivial formatting issue in sync() when doing
isValidNodeIP().
Fixes: https://github.com/ovn-org/ovn-kubernetes/pull/2657
[1]: https://github.com/ovn-org/ovn-kubernetes/runs/4267007250?check_suite_focus=true
I1119 17:12:47.755099   18058 node_ip_handler_linux.go:213] Skipping invalid IP address found on host: %s::1
I1119 17:12:47.755140   18058 node_ip_handler_linux.go:213] Skipping invalid IP address found on host: %sfe80::20d:3aff:fe8e:860c
panic: runtime error: …
=> Bug 2027487: [4.8z] addressManager should not call sync() from ErrorCallback

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Cherry-pick 43928573792934eac131b3c175970519a42e309f into 4.9
=> Bug 2027983: [4.9.z] Make config parsing more resilient for unknown fields

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go
With ovnkube-master start, we start up the node handler and then the pod
handler. When the pod sync is running, it attempts to pre-allocate all
of the already reserved IP addresses for pods. However, the IP
allocation in the sync depends on the logical switch manager being setup
for the node via the node add handler. There is no guarantee that the
node has been added by the time we pod sync, and thus we may up in a
situation where IP reservation for a pod in sync fails, and another pod
ends up getting that IP in a subsequent pod add event.
This commit adds a wait to ensure the node is in the cache before we try
to sync the pod and reserve its IP.
(cherry picked from commit 2f8b9c1c3a4788aaba28d1abc4af43456c783086)
=> Bug 2027864: [4.9z] Fixes race between node handler and pod sync

Dockerfile
Pick up support for LoadBalancer Groups:
http://patchwork.ozlabs.org/project/ovn/list/?series=265023&archive=both&state=*
which can greatly improve performance/scale with large numbers of Kube Services, once ovnkube picks up the support.
=> ovn: bump to ovn21.12-21.12.0-24.el8fdp

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go
With ovnkube-master start, we start up the node handler and then the pod
handler. When the pod sync is running, it attempts to pre-allocate all
of the already reserved IP addresses for pods. However, the IP
allocation in the sync depends on the logical switch manager being setup
for the node via the node add handler. There is no guarantee that the
node has been added by the time we pod sync, and thus we may up in a
situation where IP reservation for a pod in sync fails, and another pod
ends up getting that IP in a subsequent pod add event.
This commit adds a wait to ensure the node is in the cache before we try
to sync the pod and reserve its IP.
(cherry picked from commit 2f8b9c1c3a4788aaba28d1abc4af43456c783086) …
=> Bug 2027873: [4.8z] Fixes race between node handler and pod sync

go-controller/pkg/node/gateway_init.go
During SDN migration, there is an intermediate phase, ovn-kube runs with '--gateway-interface none' before br-ex is not created. This PR allows ovn-kube to run in such a scenario.
Fix the regression introduced by https://github.com/openshift/ovn-kubernetes/commit/1c28b968f1b0fb6252e7f4d3061b107d5cc498e0. 
Trigger SDN migration
=> Bug 2019093: Not exit when ovnkube runs with '--gateway-interface none'

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go
With ovnkube-master start, we start up the node handler and then the pod
handler. When the pod sync is running, it attempts to pre-allocate all
of the already reserved IP addresses for pods. However, the IP
allocation in the sync depends on the logical switch manager being setup
for the node via the node add handler. There is no guarantee that the
node has been added by the time we pod sync, and thus we may up in a
situation where IP reservation for a pod in sync fails, and another pod
ends up getting that IP in a subsequent pod add event.
This commit adds a wait to ensure the node is in the cache before we try
to sync the pod and reserve its IP.
(cherry picked from commit 2f8b9c1c3a4788aaba28d1abc4af43456c783086) …
=> Bug 2027874: [4.7z] Fixes race between node handler and pod sync

Dockerfile
Picks up fixes for:
- Use column diffs for weak reference counting during transaction precommit
http://patchwork.ozlabs.org/project/openvswitch/list/?series=267416&archive=both&state=*
https://bugzilla.redhat.com/show_bug.cgi?id=2005958
- ovsdb: Don't let transaction history grow larger than the database.
https://bugzilla.redhat.com/2012949
- flow: Consider dataofs when parsing TCP packets. (Security fix in OVS)
- ofproto: Fix resource usage explosion due to removal of large number of flows.
- ofproto: Fix resource usage explosion while processing bundled FLOW_MOD.
=> Bug 2033728: Dockerfile: bump OVS to 2.16.0-33.el8fdp

go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go
When the traffic directed to a service of type loadbalancer reaches the nodes, it's not redirected to the service's cluster ips. This is implemented for services of externalip / nodeport, but not for loadbalancer services. All the other logic is in place.
This will enable the integration with metallb when the traffic reaches the node from an interface different from breth0.
Also, adjust unit tests related to loadbalancer to look only at LoadBalancer IPs. In that scenario, externalIPs are not set.
=> Bug 2031012: Create iptables NAT rules also for loadbalancer services

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
1. Cache is now tracked with keys composed of namespace + pod name (rather than just pod name). This allows 2 exgws with the same name to serve the same namespace.
2. Validates user provided annotations do not have duplicate IPs.
3. Validates cache on pod create, so if there are duplicate IPs an error is logged.
=> Bug 2022536: Validate ExGW Cache and fix cache keys

Dockerfile
Add the following relevant changes:
- ovn-controller: Add command debug/dump-lflow-conj-ids
- controller/pinctrl: improve packet-in debuggability
- ovn-trace: honor ct state in execute_ct_lb
- ovn-ctl: use user-provided control socket paths
- ovn-ctl: allow overriding the database pidfile path
- ovn-ctl: add RAFT election timer argument and pass to ovsdb-tool
=> Bug 2039516: Dockerfile: bump OVN to ovn21.12-21.12.0-25

go-controller/pkg/ovn/egressgw.go
Ensures we use --may-exist on 501 policies as it is fixed in OVN. Also ensures that hybrid policies are cleaned up correctly in the sync method.
=> Bug 2033672: Multiple exgw - Use --may-exist on hybrid policy and correct hybrid policy cleanup

go-controller/pkg/ovn/policy.go
Fix a race found with network policy and stateful sets,
an issue described in:
https://bugzilla.redhat.com/show_bug.cgi?id=2016446
ensuring we try and refetch an LSP from the cache for a pod
if the get fails or if the LSP is maked for deletion
(cherry picked from commit 34f1c74ac9d7f9734624cc75c44d2f80b50bb4a4)
=> Bug 2035336: [4.9-backport] Fix Netpol retry mechanisms

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/ovn/egressip.go
When performing delete/mutation in ovn tables using modelClient.Delete(),
any rows returned by predicate will be removed.
Using doAfter is too late to decide the row's fate.
Also fixed issue in FindNatsUsingPredicate so that creating a slice of
NAT pointers uses the right address values.
=> Bug 2029742: egressip: fix usage of clientModel doAfter

go-controller/pkg/node/gateway.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
The "mode" field in the l3gw annotation
actually denotes if there is a gateway
or not, and it means "have we created
an interface that we share with the node".
The value for this is always "shared" for
both local and shared modes and this is
confusing. Let's just update this with
the right mode.
We can also remove the check for modes
when checking vlan-id since both modes
support this.
(cherry picked from commit 7922e0687bae1d2c7ee869b88e08e520f36d11b8)
=> Bug 2034577: Set l3GWConfig.mode correctly

go-controller/pkg/ovn/policy.go
Fix a race found with network policy and stateful sets,
an issue described in:
https://bugzilla.redhat.com/show_bug.cgi?id=2016446
ensuring we try and refetch an LSP from the cache for a pod
if the get fails or if the LSP is maked for deletion
(cherry picked from commit 34f1c74ac9d7f9734624cc75c44d2f80b50bb4a4)
(cherry picked from commit 8c2ad8b4a23f4d76ffae6ed850bab465a253a8e8)
=> Bug 2037884: [4.8-backport] Fix nepol statefulset 4.8

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Legacy commit using ovn-nbctl for the implementation. This commit will
be used for backports to older versions.
The host network couldn't connect to services backed by egress IP
matching pods since the return packets would get forwarded to the egress
nodes for these pods because of the routing policies specified for the
egress matching pods. This would in turn break the connection. Hence
what we need is to specify routing policies which forces the packet to
go to the originating GR instead of getting routed to the egress node
GR.
(cherry picked from commit 993e7d21250c7f0c2c9836c61daba40873e42a9d)
cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2580
**- What this PR does and why is it …
=> Bug 2034669:  Fix node connectivity to service backed by egress IP pods

dist/templates/ovn-setup.yaml.j2, go-controller/pkg/kube/kube.go, go-controller/pkg/kube/mocks/Interface.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/cloudprivateipconfig_annotations.go
/hold 
until https://github.com/openshift/ovn-kubernetes/pull/915 and https://github.com/openshift/cluster-network-operator/pull/1285 gets in 
=> Bug 2039099: EgressIP fixes for 4.10

go-controller/pkg/metrics/master.go
Increasing log level to decrease log noise.
Pods maybe created and deleted before port binding
events hit the libovsdb cache causing unwanted
log noise.
(cherry picked from commit f59ce3e1f4adca6f04ce6fc324ce25c98cbc3515)
=> Bug 2039880: Metrics: Increase log level for CP recorder

OWNERS
I keep getting assigned to review ovn-kubernetes PRs but I never actually review any of them, so I'm removing me from `reviewers`. Also, removing people who are no longer on the team...
=> Clean up OWNERS a bit

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
This commit fixes addRetryPods to correctly
construct the retryPods cache. Currently
since we assign pointer as value in
retryPods cache in a loop, the values
get overwritten and this causes a nasty
bug in the retry pod logic. Some pods
get retried while others don't.
This PR also fixes addLogicalPort to
fail hard if the node.l3gateway annotation
is not set in disableSNATGWMode.
(cherry picked from commit c63ddd62103314d8014ba2d68c596182e5b78f12)
=> Bug 2043961: Fix pod-creation-retry

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go
While creating ACLs, we are using the
nodeNames as the switch names on which
the ACLs need to be created on. This
will break on hybrid-overlay mode
since not all nodes have the OVN
switches. Let's use the libovsdb cache.
(cherry picked from commit 649883e42ea31db907f013736eb8ca8cdcfaa94a)
=> Bug 2017650: EF: Pull up switch names from cache

go-controller/pkg/libovsdb/libovsdb.go
At larger scale a reconnect may need to download and parse a bunch of
database data. This (especially the JSON parsing in cenkalti/rpc2) can
take longer than we expect a normal ovsdb transaction to take, because
it's a lot more data.
If the reconnect takes too long our timeout will cancel the Monitor
call and attempt to reconnect, perhaps timing out again, etc.
=> Bug 2046297: libovsdb: give connects more time to process than normal transactions

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/libovsdbops/transact.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/types/const.go, go-controller/pkg/util/util.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/notation.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/transact.go, go-controller/vendor/modules.txt
Due to a bug in OVSDB server where a single txn may become duplicated and cause multiple DB entries or txn failures, we add a wait method to every create operation where the resource has a unique name. This guards against OVSDB server from creating the duplicate db entry.
=> Bug 2042001: Adds wait method for ovsdb operations that created named objects

go-controller/pkg/node/gateway_shared_intf.go
When switching a service from SingleStack to DualStack, its
ClusterIPs are updated. This change to ClusterIPs will now be detected
and ovnkube will write IPv6 DNAT rules to the host.
(cherry picked from commit aa63b983474f7f7d3a1d086198ba83b4404b2ca3)
=> Bug 2031926: Shared gateway: Modification of ClusterIPs shall trigger svc update

go-controller/pkg/config/utils.go, go-controller/pkg/config/utils_test.go
Cherry-picking patch from the upstream repository: https://github.com/ovn-org/ovn-kubernetes/pull/2745
The ovnkube-node pod will fail if it receives a duplicate host:ip
for the Flow collector addresses. This commit removes the duplicate
flow collectors before forwarding to the ovs-vsctl command.
fixes #2039253
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=2039253
=> Bug 2039253: avoid passing duplicate Flow endpoints to ovs-vsctl

Dockerfile
Switches over to the ovn-2021 stream which will stay on
OVN 21.12 forever and be shared with other layered products.
(ovn21.12 was only a temporary stream for OCP 4.10 until
ovn-2021 jumped to OVN 21.12)
This update includes UBSan sanitizer fixes:
http://patchwork.ozlabs.org/project/ovn/list/?series=277507&archive=both&state=*
```
[ovs-dev,6/6] pinctrl: Avoid misaligned access to ovs_ra_msg
[ovs-dev,5/6] pinctrl: Avoid misaligned access to controller_event_opt_header
[ovs-dev,4/6] pinctrl: Ensure packet headers are properly aligned for ICMP errors
[ovs-dev,3/6] pinctrl: Ensure aligned accesses when processing DNS
[ovs-dev,2/6] pinctrl: Ensure no misaligned accesses for SCTP packets
[ovs-dev,1/6] pinctrl: Ensure proper alignment when using pinctrl_compose_ipv*()
```
=> Bug 2040357: Dockerfile: bump OVN to ovn-2021-21.12.0-11.el8fdp

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/node_smartnic_test.go
Set the ovs port as transient rather than the
interface. This along with configuring
systemd with `DELETE_TRANSIENT_PORTS = yes`
will result in the dedicated systemd service
`Delete Transient Ports` to remove stale
ovs ports and accompanying interfaces following
a hard reboot.
(cherry picked from commit 0a4ab4713ba69f6cae73ab7b7013c2627388861a)
=> Bug 2042494: [4.9] Set the OVS port as transient

go-controller/pkg/node/gateway_shared_intf.go
When switching a service from SingleStack to DualStack, its ClusterIPs are updated. This change to ClusterIPs will now be detected and ovnkube will write IPv6 DNAT rules to the host. Before this fix, upgrading IPv4 only services to DualStack via a patch or oc edit would not trigger a service update. In 4.9, this affects both connections from outside the cluster as well as connections which are initialized from the node itself. 
In 4.10, we have a very similar upstream bug, but due to changes in the code, one can actually curl the node port from the outside and hit the service through the OVN flows.
However, in both 4.9 and 4.10 alike, the ip6tables rules are not created. Thus, even in 4.10 it is not possible to …
=> [release-4.9] Bug 2028812: Modification of ClusterIPs shall trigger svc update

Dockerfile
Fixes  [ovn-northd] Failure to reconcile duplicate SB Load Balancer entries.
https://bugzilla.redhat.com/show_bug.cgi?id=2046274
=> Bug 2045577: Bump OVN to ovn-2021-21.12.0-15.el8fdp

Dockerfile
OVN team is no longer QE'ing the 21.09 branch, and 21.12 has some needed
fixes we are going to backport.
=> Bug 1996751: Bump OVN to 21.12

go-controller/pkg/ovn/egressgw.go
(cherry picked from commit 4c47ef946f07c25f9db272e076de003782e0e703)
=> [release-4.9] Bug 2054139: Don't return err when annotation cannot be unmarshalled

go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Backport of the first 2 out of this series of patches: https://github.com/openshift/ovn-kubernetes/pull/793/commits
See https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/external-ip-and-loadbalancer-ingress.md
Commit [Shared GW: Remove code duplication in updateServiceFlowCache](https://github.com/openshift/ovn-kubernetes/pull/793/commits/a9a784d224b330db5d7a84a8ddb7a3b866f20a34) was for readability only, to remove code duplication. It has no impact on the functionality and does not merge cleanly, thus I did not backport it.
This PR backports 2 commits:
a) Output address resolution requests to LOCAL port (clean)
b) Neighbor solicitations and ARP requests used to hit all 3 OVN (conflict)
For a): Clean …
=> [release-4.9] Bug 2014003: Fix gateway routers answer ARP/NDP requests for LoadBalancer/ExternalIP services

go-controller/pkg/node/gateway_iptables.go
When the traffic directed to a service of type loadbalancer reaches the
nodes, it's not redirected to the service's cluster ips. This is
implemented for services of externalip / nodeport, but not for
loadbalancer services. All the other logic is in place.
This will enable the integration with metallb when the traffic reaches
the node from an interface different from breth0.
Also, adjust unit tests related to loadbalancer to look only at
LoadBalancer IPs. In that scenario, externalIPs are not set.
=> Bug 2040594: Create iptables NAT rules also for loadbalancer services

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
This is a cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/886
Legacy commit using ovn-nbctl for the implementation. This commit will
be used for backports to older versions.
The host network couldn't connect to services backed by egress IP
matching pods since the return packets would get forwarded to the egress
nodes for these pods because of the routing policies specified for the
egress matching pods. This would in turn break the connection. Hence
what we need is to specify routing policies which forces the packet to
go to the originating GR instead of getting routed to the egress node
GR.
Conflicts:
go-controller/pkg/ovn/egressip_test.go
Co-authored-by: Alexander Constantinescu <aconstan@redhat.com>
(cherry picked from …
=> [release-4.7] Bug 2047325: Fix node connectivity to service backed by egress IP pods

go-controller/pkg/ovn/egressip.go
Fix podHandlerCache key  to allow a scenario where multiple egress IPs match the same namespace
With podHandlerCache key being the namespace name it meant that there can be only one egress IP that matches a particular namespace.
Reproducer I used in kind:
```
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
name: egressip-1
spec:
egressIPs:
- 172.18.0.33
namespaceSelector:
matchLabels:
name: test
podSelector:
matchLabels:
name: test-1
---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
name: egressip-2
spec:
egressIPs:
- 172.18.0.44
namespaceSelector:
matchLabels:
name: test
podSelector:
matchLabels:
name: test-2
```
=> [release-4.9] Bug 2055549: Fix podHandlerCache key

go-controller/pkg/ovn/loadbalancer/loadbalancer.go
This reverts commit f30307618c4f7bf0a6797b7288647ab8543d499f.
This is no longer needed, now that https://bugzilla.redhat.com/show_bug.cgi?id=1995326 has landed.
=> Bug 2056883: Revert "HACK: disable skip_snat for load balancers."

go-controller/pkg/ovn/egressip.go
`deleteEgressNode` takes care of reassigning egress IPs that are hosted on that node when it gets deleted, becomes unreachable, the label `k8s.ovn.org/egress-assignable` gets removed.
It is possible that when `deleteEgressNode` takes a long time to reassign the egress ips another one is called(e.g node becomes unreachable and then `NotReady`).
Best case scenario the egressIP is reassigned twice, worst case the status doesn't get updated properly or the egress IP is not correctly assigned.
**I do not think that this change brings any deadlock potential as this approach is already used in `addEgressNode`, nevertheless it would be good to focus on that while reviewing the change.**
I was able to reproduce the bug and verify the fix by creating 400 pods that match the egress IP assigned to …
=> [release-4.9] Bug 2054299: Lock the reassignment procedure during node deletion to avoid races

go-controller/pkg/ovn/controller/services/OCP_HACKS.go, go-controller/pkg/ovn/controller/services/services_controller.go
In kube 1.21 and 1.22 (OCP 4.8 and 4.9), the apiserver will default
the value of ipFamilyPolicy to RequireDualStack if you create a
Service with two ipFamilies or two clusterIPs but no explicitly
specified ipFamilyPolicy. In 1.23/4.10, you must explicitly specify
either PreferDualStack or RequireDualStack for DualStack services.
Emit a warning in 4.8 and 4.9 to raise awareness about the upcoming
API changes. See BZ2045576 for a thorough discussion.
=> Bug 2045576: [CARRY][Downstream-only] Give warning when ipFamilyPolicy implicitly set

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go
This commit fixes addRetryPods to correctly
construct the retryPods cache. Currently
since we assign pointer as value in
retryPods cache in a loop, the values
get overwritten and this causes a nasty
bug in the retry pod logic. Some pods
get retried while others don't.
Cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/926
=> Bug 2053310: [release-4.9] Fix pod-creation-retry

Dockerfile
Pulls in the following relevant ovsdb-server and IDL fixes:
ovsdb: transaction: Keep one entry in the transaction history.
ovsdb-cs: Fix ignoring of the last id from the initial monitor reply. (#2044624)
ovsdb: storage: Randomize should_snapshot checks when the minimum time passed.
raft: Only allow followers to snapshot.
The ovsdb and raft patches should improve database snapshot behavior
and reliability, and fix some corner cases of downloading the whole DB
on reconnect when a large transaction occurs.
=> Bump OVS to 2.16.0-53.el8fdp

go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go
This PR does the equivalent of https://github.com/openshift/sdn/pull/261
for OVN-K. We can remove this hack when we support
ITP:preferLocal in the future.
(cherry picked from commit bfe85db278e75b89da01657630cd718ffa1310c3)
Conflicts:
go-controller/pkg/ovn/controller/services/load_balancer.go
just a minor comment conflict since ETP=local and LGW refactor
don't exist in 4.9
=> [release-4.9] Bug 2055317: Hack ITP:preferLocal for DNS service

Dockerfile
Note: We still need https://github.com/ovn-org/ovn-kubernetes/pull/2835 to fix the bug, but at least this BUMP will prepare the floor for the future downstream merge that will pick that fix.
=> Bug 2052975: Bump OVN to ovn-2021-21.12.0-30.el8fdp

go-controller/pkg/ovn/egressip.go
EgressIP: fix egress node allocation sync 
This is a smaller mistake that probably needs to get back-ported to
earlier versions. When syncing egress IPs we never added the assigned
and valid egress IPs to the allocator used to track assignments, this
could mean that we might have future assignments being made to nodes
which do not respect all assignment constraints because the allocator is
out of sync.
(cherry picked from commit 65e5a2f46501f9796fbe42e6162e6bdf3a47db09)
=> [release-4.8] Bug 2057152: Fix egress IP allocator sync

dist/images/Dockerfile.fedora, go-controller/pkg/kube/kube.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_cleanup.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go
In cases where OVN database for logical router policies or NATs
used by EgressIPs have stale nexthops or wrong external_ips, the
sync function should remove them, so the proper row/column gets set.
In order to cleanly apply these changes from 4.11, the following commits were also added:
- https://github.com/openshift/ovn-kubernetes/pull/940 (pulled in upstream  https://github.com/ovn-org/ovn-kubernetes/pull/2773)
-  https://github.com/openshift/ovn-kubernetes/pull/947 (pulled in upstream https://github.com/ovn-org/ovn-kubernetes/pull/2783)
Signed-off-by: Flavio Fernandes [flaviof@redhat.com](mailto:flaviof@redhat.com)
=> Bug 2059354: [4.10z] After reboot egress node, lr-policy-list was not correct

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressip.go
Use pod IPs from annotation in sync
We cannot rely on pod.Status.PodIPs for obtaining the IPs, since that is unset in between the restart and the moment it retrieves that information. Use annotation instead.
In cases where OVN database for logical router policies or NATs used by EgressIPs have stale nexthops or wrong external_ips, the sync function should remove them, so the proper row/column gets set.
Signed-off-by: Flavio Fernandes [flaviof@redhat.com](mailto:flaviof@redhat.com)
=> Bug 2059700: [4.9z] After reboot egress node, lr-policy-list was not correct, some duplicate records or missed internal IPs

go-controller/pkg/ovn/controller/services/OCP_HACKS.go, go-controller/pkg/ovn/controller/services/services_controller.go
In kube 1.21 and 1.22 (OCP 4.8 and 4.9), the apiserver will default
the value of ipFamilyPolicy to RequireDualStack if you create a
Service with two ipFamilies or two clusterIPs but no explicitly
specified ipFamilyPolicy. In 1.23/4.10, you must explicitly specify
either PreferDualStack or RequireDualStack for DualStack services.
Emit a warning in 4.8 and 4.9 to raise awareness about the upcoming
API changes. See BZ2045576 for a thorough discussion.
Minor conflict in services_controller.go (rearrangement of a couple
of lines only affecting the comments).
(cherry picked from commit 06338af79912421be4ec760101b85841d111978e)
Conflicts:
go-controller/pkg/ovn/controller/services/services_controller.go
**- How to …
=> [release-4.8] Bug 2065303: [CARRY][Downstream-only] Give warning when ipFamilyPolicy implicitly set

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go, test/e2e/e2e.go
Use pod IPs from annotation in sync
We cannot rely on pod.Status.PodIPs for obtaining the IPs, since that is unset in between the restart and the moment it retrieves that information. Use annotation instead.
In cases where OVN database for logical router policies or NATs used by EgressIPs have stale nexthops or wrong external_ips, the sync function should remove them, so the proper row/column gets set.
Backport from 4.9: Egress IP with ECMP routing (https://github.com/openshift/ovn-kubernetes/pull/981)
Signed-off-by: Flavio Fernandes [flaviof@redhat.com](mailto:flaviof@redhat.com)
=> Bug 2062842: [4.8z] After reboot egress node, lr-policy-list was not correct, some duplicate records or missed internal IPs

go-controller/pkg/cni/OCP_HACKS.go, go-controller/pkg/node/OCP_HACKS.go
Adds go:build tag for OCP_HACKS files.
=> Fix gofmt for downstream files

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_retry.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go
When a pod gets deleted, a number of things could fail. But we used to just log warnings and proceed to releasing the IP of the pod which means two LSP's could now have the same IP in corner cases where let's say a LSP deletion wasn't successful. This PR adds the mechanism for retrying a deletion of pod if it fails.
Note to reviewers: One commit had conflict:
Add retry logic for pod deletion
Idea-Credit: Timothy Rozet<trozet@redhat.com>
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/51a4b092bff26df6685034c6fad8fcdd0d9ed8ac)
Conflicts:
Small conflict in go-controller/pkg/ovn/ovn.go because
https://github.com/ovn-org/ovn-kubernetes/commit/b885431979443cd2a864fe045be21a00867fb600
is missing.
/cc …
=> [release-4.10] Bug 2052017: Retry Pod Deletions on Failure

go-controller/pkg/ovn/policy.go
without adding the exemption for neighbor detection on network policies
the network policy will deny all attempts for ipv6 to send traffic
=> Bug 2074839: [release-4.10] fix ipv6 network policy 

docs/design/service_traffic_policy.md, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go
This commit does two things:
1) No need to steer service traffic for LGW via breth0 into OVN.
Let's pass it into the host where user can apply custom routes
and modulate the traffic as needed.
Flow: external->br-ex->host->iptables->br-ex->GR->pod
reply will follow the same path (check docs for details)
2) Cleanup some ETP=local code since this simplifies things on
br-ex for LGW.
(cherry picked from commit dbd824057551a2aea3cfef61c346ee50fe66e036)
clean cherry pick from master
=> [release-4.10] Bug 2073137: Fix lgw flows for ingress-svc traffic

go-controller/pkg/ovn/policy.go
without adding the exemption for neighbor detection on network policies
the network policy will deny all attempts for ipv6 to send traffic
=> Bug 2077369: [release-4.9] fix ipv6 network policy 

go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/healthcheck_test.go
(cherry picked from commit 77678fbe280a701351decded0a16017f4e7a18aa)
fixes #2065780
(the bug was found in 4.9 in SNO https://bugzilla.redhat.com/show_bug.cgi?id=2016115)
=> Bug 2065780: [release-4.10][backport] Fix cleaning VF representor ports

go-controller/pkg/ovn/ovn.go
a correctly configured noHostSubnet node will never become avalible on
GCP because the unavailable condition will never be cleared.
slight changes required to make this work on 4.10
=> Bug 2079546: [release-4.10] call clearInitialNodeNetworkUnavailableCondition for noHostSubnet nodes

go-controller/pkg/ovn/policy.go
without adding the exemption for neighbor detection on network policies
the network policy will deny all attempts for ipv6 to send traffic
=> Bug 2077370: [release-4.8] fix ipv6 network policy

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Use a queue instead of spawning go routines to add events.
=> Bug 2080925: Don't spawn go routines for adding metric events

go-controller/pkg/metrics/ovn_northd.go
Before registering OVN northd metrics, we check to see if ovnkube
master is co-located on the same node and repeatedly check if it
is present because ovnkube node may start before ovnkube master.
This repeated checking only causes one error mode to occur which
is a timeout error and this is incorrectly logged as an error
confusing the user.
The only failure path to occur within 'checkPodRunsOnGivenNode' can
be seen with increased log level.
(cherry picked from commit 1ef9add179ecf74cab8f819cb416fbe254c7745a)
To verify this:
1. Grep the logs of the ovnkube-node container that isn't on a control plane node for the Error message 'Timed out while checking if OVNKube Master Pod runs'. You should not get a result.
2. Grep the logs of the …
=> Bug 2080882: Fix incorrectly logged error when searching for ovnkube master pod

go-controller/pkg/metrics/ovn.go, go-controller/pkg/metrics/ovn_db.go
We are using labelled (vector) metrics to export
info and if the label values change, we still
export the old labels values which confuses users
because they have no way of determining which labelled
metric is the latest.
We must reset each vector metric prior to using it to
ensure we are only exporting the current state and not
old states which should have been scraped previously due
to our usage of labels that can be dynamically updated
during runtime.
This is occurring in the OVN metrics exported by
ovnkube-node.
Follow on work is needed to fix OVS metrics that are
used by ovs-exporter.
Steps to reproduce:
1. Get OVN Northbound database leader (use cluster/status command from ovn-nbctl)
2. Login to the ovnkube-node container on that node.
3. Curl the metrics endpoint and grep for …
=> Bug 2080895: Ensure stale information is not present in metrics with labels when they change

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
Cleanup conntrack entries when clusterIPs are deleted
This PR does two things:
1) cleanup conntrack entries irrespective of protocolstack
for service deletion
2) cleanup conntrack entries only for UDP during endpoint
deletion.
See https://github.com/kubernetes/kubernetes/issues/108523#issuecomment-1074044415
for details.
(cherry picked from commit 8f46895a9fb05f05047ddd61936db89ffddeca38)
NOTE to Reviewers:
I had to add an extra commit :
Author: Surya Seetharaman <suryaseetharaman.9@gmail.com>
Date:   Fri Apr 29 00:12:53 2022 +0200
Add ListAddresses() utility
Had to take this from
https://github.com/openshift/ovn-kubernetes/pull/1040/commits/bfb5ac17a2ddb350bee956e16af7d69c4af6046b#diff-9eaecf6cd5a03cd786e33bc636507897362732e6 …
=> Bug 2080069: Cleanup conntrack entries when services are deleted

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, test/e2e/e2e.go
We should be deleting the snat towards nodeIP before
adding snat towards egressIP only from the node
where the pod lives if that same node is serving
as the egressIPnode for the pod.
A second problem that was fixed was in deleteEgressIPAssignments
we were re-adding the setup for SNAT towards nodeIP only if
pod had no egressIPs attached to it, which is wrong since depending
on the location of the pod, we'd need to re-add the SNAT towards
nodeIP even if the pod is being served by another egressIP.
(cherry picked from commit 044ead332e4e26cbc141afc0739b37b68bdb76c7)
Clean cherry-pick from master
**- Description for the …
=> [release-4.10] Bug 2083116: delete SNAT2NIP if pod.node == egressNodeServingPod

go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/healthcheck_test.go
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/77678fbe280a701351decded0a16017f4e7a18aa)
fixes #2065782
(the bug was found in 4.9 in SNO https://bugzilla.redhat.com/show_bug.cgi?id=2016115)
=> Bug 2065782: [release-4.9][backport] Fix cleaning VF representor ports

go-controller/pkg/metrics/ovn_db.go
Backport bugfix from https://github.com/openshift/ovn-kubernetes/pull/1049/commits/76699afae1229cacb178c369ea5916d35e7a2788. Explained here https://github.com/ovn-org/ovn-kubernetes/pull/2890
=> [release-4.10] Bug 2082467: Fix cluster/status parsing for single-member db cluster (SNO)

Dockerfile
Includes a fix for ovn-controller to not flush conntrack entries in zone
0 on restart.
=> Bug 2081069: Bumps OVN to 22.03.0-37.el8fdp

go-controller/pkg/ovn/egressfirewall.go
Recreate Egress Firewall ACL rules including their priority always.
This affects 4.9 only because:
In 4.8, we use individual transactions. In 4.10, we use libovsdb. In
4.9, we are in the odd situation that we use a single transaction for
the delete/add EgressFirewall, however during the add we readd a not
yet deleted rule (due to the pending transaction) and thus delete and
then immediately add the same rule with the same UUID, leading to rules
with duplicated priority.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2083239
For more details, see: https://bugzilla.redhat.com/show_bug.cgi?id=2083239#c8
=> [release-4.9] Bug 2083239: [Downstream-only][4.9-only] Always add complete efw ACL rules

go-controller/pkg/ovn/egressip.go
While deleting EgressIP nats from a logical router find the router that has the nat instead of relying on the node name.
(cherry picked from commit 2f8ec3310ea608b7e0b3e905f8ad3fdcd5d057e3)
=> Bug 2088627: EgressIP NATs are not being cleared correctly from the logical router 

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
Cherry-pick the following upstream PRs to improve performance in scale tests by batching GRSNAT operations and not doing redundant LSP lookups:
https://github.com/ovn-org/ovn-kubernetes/pull/2999
https://github.com/ovn-org/ovn-kubernetes/pull/2769
=> Bug 2090843: addLogicalPort() optimization cherry-picks

Dockerfile
Brings performance and bug fixes. Most notable are:
- northd: add configuration option for enabling parallelization (#2078552)
- ovn-controller: Consider zone 0 as a valid zone when restoring. (#2087194)
- northd: optimize build_gw_lrouter_nat_flows_for_lb code (#2079834)
- ovn-controller: Avoid recompute triggered by external_ids:ovn-installed update.
- northd: Add generic port security logical flows. (#2078927)
=> Bug 2089930: Dockerfile: bump OVN to ovn22.06

go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go
Carry a couple upstream libovsdb performance/scale patches
https://github.com/ovn-org/libovsdb/pull/312
https://github.com/ovn-org/libovsdb/pull/311
https://github.com/ovn-org/libovsdb/pull/308
And one bug fix that makes 308 apply cleanly:
https://github.com/ovn-org/libovsdb/pull/307
=> Bug 2092473: libovsdb perf backports

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
(cherry picked from commit bb014893878d36e3c955ad706d99fe0262e6f4b9)
=> Bug 2091990: fix lflow-cache-limit-kb ovs external-id

go-controller/pkg/metrics/ovs.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Using ovs-dpctl can cause severe issues when there is a version mismatch between ovs-dpctl and ovs-vswitchd.
To address that use ovs-appctl dpctl/* since it provides the same data that is in the same format.
Upstream PR: https://github.com/ovn-org/ovn-kubernetes/pull/3007/commits/a221bb9888252c684f93c4afafa5f3309ab5e280
(cherry picked from commit a221bb9888252c684f93c4afafa5f3309ab5e280)
=> Bug 2091634: Use ovs-appctl dpctl/* instead of ovs-dpctl

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, test/e2e/e2e.go
The "MTU is too small" case never happens in normal operation, and
it required nodes patch access.
Get rid of tainting and just return an error which will prevent
node from becomig ready.
(cherry picked from commit 32d930197dbc65206d640a7b065889ad06e8f5e3)
=> Bug 2093396: Remove node-tainting for too-small MTU

go-controller/pkg/ovn/policy.go
There was a typo for multicast ingress allow policies causing their ACLs
to be turned into "from-lport" ACLs that would never be matched.
Closes #2926: Multicast flaking in CI.
Fixes: f68d302664e6 ("libovsdb: Use libovsdb for ACLs and port groups")
Signed-off-by: Dumitru Ceara <dceara@redhat.com>
(cherry picked from commit 288cf591f09b18a14c6fa1a3935480a578024f7e)
=> Bug 2086891: policy: Fix multicast allow policy type.

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/obj_retry.go
Fixes panic seen during checkEgressNodesReachability
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]
goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00)
/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-cont …
=> Bug 2094039: egressIP: node retrieval failure is not respected, causes panic

Dockerfile
Most important fixes are:
- ovsdb: raft: Fix transaction double commit due to lost leadership. (#2046340)
- UBSan and undefined behavior fixes
=> Bug 2095113: Dockerfile: bump to openvswitch2.17-2.17.0-22.el8fdp

go-controller/cmd/ovn-kube-util/app/ovs-exporter.go, go-controller/cmd/ovnkube/ovnkube.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/mocks/gauge.go, go-controller/pkg/metrics/ovn.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/metrics/ovn_northd.go, go-controller/pkg/metrics/ovs.go, go-controller/pkg/metrics/ovs_test.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/ovn/egressfirewall_dns.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go
Needed to `cherry-pick -x` two further commits (https://github.com/openshift/ovn-kubernetes/commit/cc7aa383362006017e727b19b8e09dfc43613542, https://github.com/openshift/ovn-kubernetes/commit/f92dcbe10f4d4aa49c270b8b2411bf19e83b7cb2) that are needed because the fix was developed & tested on said commits.
Commits were cleanly cherry-picked. No changes versus upstream commits was needed.
=> Bug 2089716: Downstream fix for OVN-Kube node cardinality

Dockerfile
Includes fix for OVN flushing all conntrack entries in zone 0 on
ovn-controller restart.
=> Bug 2088582: Bumps OVN to 21.12.0-58.el8fdp

go-controller/pkg/ovn/policy.go
clean cherry-pick of upstream commit bc941c289d6e8ddfd6fcee4e31fb85100ae97cf8
Direction of the ACLs built for multicast egress policy was always
"from-lport", so we cannot determine if we need to update egress ACL
direction based on the first egress ACL that found.
Signed-off-by: Yun Zhou <yunz@nvidia.com>
=> Bug 2092889: update all egress ACLs' direction to "from-lport"

go-controller/pkg/ovn/policy.go
Cherry-picked from ovn-org/ovn-kubernetes#3011
All the namespace policies ACLs were being updated when adding a single
policy to make sure that the ACL logging levels were current on the
policies in case it changed while the policy was being created. This is
unnecessary and has performance issues.
When creating a policy, only update the ACL logging of that policy, and
only if it changed from the value we created it with. The other
namespace policies will be handled through the namespace update handler.
=> Bug 2089392: Update logging for specific policy when creating it

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/util/net.go
Clean cherry-pick from https://github.com/ovn-org/ovn-kubernetes/pull/3008.
NO conflicts
=> Bug 2079012: Fix egressIP object deletion if the node is deleted first

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
This commit is is not a clean cherry-pick of
12848e73062711e67d04bd676d2a7eb84fc7cad2.
Half of the original commit is not relevent to 4.10 because retry
logic is not developed.
When addNode() failed in addNodeAnnotations(), the node's IPAM can be
overwritten by subsequent addNode() retry attempts. As the result, the
same IP can be allocated to multiple pods.
All credit to Yun Zhou (yunz@nvidia.com).
=> [release-4.10] Bug 2095193: duplicated IPs can be assigned to multiple Pods

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/helper_linux.go
The code for determining the default gateway was not taking into
consideration if the gateway interfaces was provided via config and
would return any default gateway found on the host. This is an issue
when a system has more than 1 default gateway, as well as if a user
provided an interface other than the real default gateway interface.
If the gateway interface is provided via config, the code now scopes
default routes found to only that interface.
(cherry picked from commit 87db93dadb434057fa05c2094bf2bf8e34e547f2)
=> Bug 2092501: Fixes finding default gateway for configured GW interface

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
Users can change node's reachability total timeout from 1sec "default"
to different values using this new option.
Also it can be used to disable reachability check if users specify a value
of 0.
(cherry picked from commit 9e4358d1001febbaf440644484fd4335e0660911)
=> Bug 2099755: Add new EgressIP config option "egressip-reachability-total-timeout"

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Fix panic in NP deletion
Fixes panic observed during NP deletion:
2022-05-27T15:48:27.957882179Z I0527 15:48:27.957839       1
policy.go:1251] Deleting network policy XXXXX in namespace XXXXX
2022-05-27T15:48:27.957950868Z E0527 15:48:27.957928       1
runtime.go:78] Observed a panic: "invalid memory address or nil pointer
dereference" (runtime error: invalid memory address or nil pointer
dereference)
2022-05-27T15:48:27.957950868Z goroutine 132 [running]:
2022-05-27T15:48:27.957950868Z
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1930dc0, 0x2907f50)
2022-05-27T15:48:27.957950868Z
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74
+0x95
2022-05-27T15:48:27.957950868Z
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, …
=> Bug 2091238: Fix Panic in Network Policy deletion

Dockerfile
Upgrade to a final/released version of OVN 22.06 which includes
the following relevant fixes:
- [OVN HWOL] Avoid masked access to ct_label to allow offloading of ECMP symmetric reply and load balanced traffic
https://bugzilla.redhat.com/show_bug.cgi?id=2097221
Which is already in 22.06 but needs the following fixups:
- controller: Use ct_mark by default for load balancer hairpin flows.
- northd: Use ct_mark.blocked and ecmp_reply_port only when all chassis support it. (#2091565)
- northd: ovn-controller: Use ct_mark.natted only when ct_lb_mark is used.
- northd: Use ct_lb_mark only when all chassis support it. (#2091565)
- binding.c: Make sure that localport is removed from local datapath (#2076604)
- physical.c: Move localport remote output flow definition (#2076604)
- physical.c: Avoid …
=> Bug 2097221: Dockerfile: bump to ovn22.06-22.06.0-7.el8fdp

go-controller/pkg/ovn/obj_retry.go
clean cherry pick
Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>
(cherry picked from commit 8df383b243c66022cdc48400fc14fea451a8a9b5)
fixes #2100507
=> Bug 2100507: Remove redundant log lines in obj_retry.go

go-controller/pkg/ovn/policy.go
NOTE to reviewers: Code changed considerably in these parts between 4.12 and all the way here. I have outlined conflicts in each commit but mainly, **this PR needs careful review** because I couldn't really port any unit tests since I ran into issues with the goovn test framework build.
=> [release-4.9] Bug 2105277: Fix panics in DestroyNetworkPolicy if policy is nil

go-controller/pkg/ovn/policy.go
@trozet Good news, clean cherry-pick from the 4.9 one https://github.com/openshift/ovn-kubernetes/pull/1183 no conflicts.
=> [release-4.8] Bug 2106089: Fix panics in DestroyNetworkPolicy if policy is nil

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Auth scheme is retrieved from sock address in libovsdb.
Empty sock address results in "unknown network protocol"
error when connecting in unix mode.
(cherry picked from commit 876a864a7d17d182e9595bec643f135de579d4f7)
=> Bug 2106298: populate sock address for ovndb connection in unix mode

Dockerfile
Includes fix for OVN flushing all conntrack entries in zone 0 on
ovn-controller restart.
(cherry picked from commit ab91b0f7f2d7c5f453040f94b253fe5525df36bb)
Backport of https://github.com/openshift/ovn-kubernetes/pull/1101
=> Bug 2097157: Bumps OVN to 21.12.0-58.el8fdp

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/iptables.go
On startup we are flushing all the rules in ovnk
chains. The MGTM chain particularly gets flushed
from `createPlatformManagementPort` which calls
`tearDownManagementPortConfig` before `setupManagementPortConfig`
that readds these rules back. This PR doesn't
fix the flushing bug, but fixes the ovn-k8s-mp0 SNAT
rule to be always added last in the chain (append)
on startup. The other rules in the chain are inserted
or prepend-ed so we should be good.
(cherry picked from commit 023fb7aa0133695091c8703e2593bb2176759972)
CLEAN PICK
=> Bug 2106862: Append the SNAT rule in management chain

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/iptables.go
On startup we are flushing all the rules in ovnk
chains. The MGTM chain particularly gets flushed
from `createPlatformManagementPort` which calls
`tearDownManagementPortConfig` before `setupManagementPortConfig`
that readds these rules back. This PR doesn't
fix the flushing bug, but fixes the ovn-k8s-mp0 SNAT
rule to be always added last in the chain (append)
on startup. The other rules in the chain are inserted
or prepend-ed so we should be good.
(cherry picked from commit 023fb7aa0133695091c8703e2593bb2176759972)
(cherry picked from commit e394194fe70f013f8e7b77b205aef4b8137d5d7b)
(cherry picked from commit be27fa05cd4ddf5a4181add6de3e95487a85410c)
CLEAN PICK
=> [release-4.10] Bug 2107903: Append the SNAT rule in management chain

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/ovn.go
Fixes panic seen during checkEgressNodesReachability
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]
goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00)
/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-cont …
=> [release-4.10] Bug 2105653: egressIP: node retrieval failure is not respected, causes panic

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/node_smartnic_test.go
Set the ovs port as transient rather than the
interface. This along with configuring
systemd with `DELETE_TRANSIENT_PORTS = yes`
will result in the dedicated systemd service
`Delete Transient Ports` to remove stale
ovs ports and accompanying interfaces following
a hard reboot.
(cherry picked from commit 0a4ab4713ba69f6cae73ab7b7013c2627388861a)
(cherry picked from commit 24944637f1aee42156efde53894fa436155857ca)
=> Bug 2107645: Set the OVS port as transient

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/ovn.go
Fixes panic seen during checkEgressNodesReachability
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]
goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00)
/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-cont …
=> [release-4.9] Bug 2105654: egressIP: node retrieval failure is not respected, causes panic

dist/images/Dockerfile.fedora, go-controller/hack/build-go.sh, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go, test/e2e/external_gateways.go
/cc @zshi-redhat @dceara @msherif1234 @numansiddique tagging because each one has a commit in the merge
/assign @trozet for approve
/assign @dcbw for approve
Fixes bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=2095852 (@anuragthehatter)
https://bugzilla.redhat.com/show_bug.cgi?id=2078691 (@huiran0826)
https://bugzilla.redhat.com/show_bug.cgi?id=2106444
=> OCPBUGSM-45393: Bug 2078691: [Downstream Merge] 22-07-2022

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/ovn.go
Fixes panic seen during checkEgressNodesReachability
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]
goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00)
/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-cont …
=> [release-4.8] Bug 2105655: egressIP: node retrieval failure is not respected, causes panic

Dockerfile
Bump OVN to 22.06.0-27 to get https://patchwork.ozlabs.org/project/ovn/patch/20220727221505.1673659-1-hzhou@ovn.org/ in.
=> Bug 2111733: Bump OVN to 22.06.0-27

Dockerfile
Bump OVN to 22.06.0-27 to get https://patchwork.ozlabs.org/project/ovn/patch/20220727221505.1673659-1-hzhou@ovn.org/ in. This will fix https://bugzilla.redhat.com/show_bug.cgi?id=2112111
=> Bug 2111619: Bump OVN to 22.06.0-27

go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/model_client_test.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/util.go
This is a backport of #1110, containing:
* CARRY: cf3a846a3535fe85b6d6aae9d46fbd3d4a5a04d6 libovsdb: passthrough ops in ModelClient
* CARRY: 73e491c00f430d50a3418f44a825e0b26a7c723b libovsdb: refactor duplicate detection in modelClient
* 1aaad50f0cba45967444c88a623c5b97b926d60a libovsdbops: only one wait per txn
* 0573fe590a6f307200dc61a9cd0a6409db754c3d Don't lookup LBs that don't exist in cache
Conflicts:
* [go-controller/pkg/libovsdbops/loadbalancer.go](https://github.com/openshift/ovn-kubernetes/compare/release-4.10...jcaamano:ovn-kubernetes-downstream:release-4.10?expand=1#diff-685368ea628f10afd438349e793caa717e04ec15ae38a15ac0be406686f0ae5b)
* [go-controller/pkg/libovsdbops/model_client.go](https://github.com/openshift/ovn-kubernetes/compare/release-4.10...jcaamano:ovn-kubernetes-dow …
=> [release-4.10] Bug 2104454: improve performance of service sync

go-controller/pkg/factory/factory.go
Previously only MatchLabels was used to create a label selector and MatchExpressions was ignored
=> [release-4.10] Bug 2109442: Fix GetPodsBySelector/GetNamespacesBySelector so MatchExpressions is respected

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/util/ovn.go
tagging @pliurh @zshi-redhat @andreaskaris
=> Bug 2109945: [Downstream Merge: 04-08-2022]

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
This commit is is not a clean cherry-pick of
12848e73062711e67d04bd676d2a7eb84fc7cad2.
This patch ensures that retry logic for pods is after syncPods
is executed. This is accomplished serially with the AddPodHandler
func's parameter 'processExisting' which we pass the syncPods func.
This ensures we exec 'syncPods' once before calling the retry funcs.
However, we need to fix the case where 'syncPods' fails in future
patches.
Also, when addNode() failed in addNodeAnnotations(), the node's IPAM can be
overwritten by subsequent addNode() retry attempts. As the result, the
same IP can be allocated to multiple pods.
All credit to Yun Zhou (yunz@nvidia.com).
/cc @trozet
=> [release-4.9] Bug 2096802: duplicated IPs can be assigned to multiple Pods

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Cherry picked from https://github.com/openshift/ovn-kubernetes/pull/1210/commits/944b5c2f606b06c0a82624a9dea5a9fc4e7d4124 NOT CLEAN, conflict mentioned in commit message
```
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.br-ex.rp_filter = 0
net.ipv4.conf.br-int.rp_filter = 0
net.ipv4.conf.c1798a1ec76c1f4.rp_filter = 0
net.ipv4.conf.d1517e738ed8391.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.ebc08262035b15d.rp_filter = 0
net.ipv4.conf.ens5.rp_filter = 0
net.ipv4.conf.fa15be590ac0579.rp_filter = 0
net.ipv4.conf.genev_sys_6081.rp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.ovn-k8s-mp0.rp_filter = 2
net.ipv4.conf.ovs-system.rp_filter = 0
```
works!
=> Bug 2105444: ITP=local, host->svc case failure

go-controller/pkg/node/gateway_iptables.go
We call getGatewayIPTRules from both LGW and SGW. This adds
iptable rules for services to EXTERNALIPs chain. We already
add iptable rules for services of type LB.ingress.ip to
NODEPORT chain for LGW. So we need to add the LB ingress rules
to EXTERNALIPs chain only for SGW mode.
/assign @flavio-fernandes @trozet
=> Bug 2115845: [release-4.9] OCP CARRY: Add the rules to EXTERNALIPs only for SGW mode

go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Adding and removing a pod on changing nodes back to back can end up in a race where
corresponding logical switch port remains in the wrong logical switch and never gets
properly removed. In order for this to happen, the logical switch port has to have
the same name, which is the `<namespace>_<podName>`.
This PR includes the back-porting of 2 fixes needed to address this race.
They were merged to D/S master via PR https://github.com/openshift/ovn-kubernetes/pull/1237
- https://github.com/openshift/ovn-kubernetes/pull/1237/commits/f1be8d298bfe7b087af009a4093a863ebb7804fb
- https://github.com/openshift/ovn-kubernetes/pull/1237/commits/be8786a89546effe2de121fce9c05907fae4c1ce
=> Bug 2118717: [release-4.11] Fix race when adding and removing pod with same name 

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Clean backport of two commits from: https://github.com/ovn-org/ovn-kubernetes/pull/2897 which got into 4.11 here: https://github.com/openshift/ovn-kubernetes/pull/1040
The last commit was already backported here: https://github.com/openshift/ovn-kubernetes/pull/1098
=> [release-4.10] Bug 2070392: Fix egress IP reassignment on cloud

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_retry.go, go-controller/pkg/ovn/pods_test.go
Adding and removing a pod on changing nodes back to back can end up in a race where
corresponding logical switch port remains in the wrong logical switch and never gets
properly removed. In order for this to happen, the logical switch port has to have
the same name, which is the <namespace>_<podName>.
This PR includes the back-porting of 2 fixes needed to address this race.
They were merged to D/S master via PR https://github.com/openshift/ovn-kubernetes/pull/1237
https://github.com/openshift/ovn-kubernetes/commit/f1be8d298bfe7b087af009a4093a863ebb7804fb
https://github.com/openshift/ovn-kubernetes/commit/be8786a89546effe2de121fce9c05907fae4c1ce
=> OCPBUGS-174: [release-4.10] Fix race when adding and removing pod with same name

go-controller/pkg/node/gateway_iptables.go
We call getGatewayIPTRules from both LGW and SGW. This adds
iptable rules for services to EXTERNALIPs chain. We already
add iptable rules for services of type LB.ingress.ip to
NODEPORT chain for LGW. So we need to add the LB ingress rules
to EXTERNALIPs chain only for SGW mode.
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/pull/1233/commits)
=> Bug 2115039: [release-4.8] OCP CARRY: Add the rules to EXTERNALIPs only for SGW mode

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3063 from upstream.
A missing comma before an "action=" meant that those OVS flows weren't getting added due to a parsing error.
Second, the `k8s.ovn.org/node-gateway-router-lrp-ifaddr` annotation added by https://github.com/ovn-org/ovn-kubernetes/pull/2862 was only evaluated on node add, but we can't always rely on that. It might be added slightly later in an Update event.
=> [release-4.11] Bug 2109642: two hybrid overlay fixes

go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller_test.go
services controller: reconcile on node deletion
A node load balancer is a load balancer associated to any of the following
services:
- service with NodePort set
- service with host-network endpoints
- service with ExternalTrafficPolicy=Local
- service with InternalTrafficPolicy=Local
This commit forces the reconciliation of the load balancers upon node
deletion. Since the node was deleted, the newly generated list of load
balancers will not feature the deleted node's load balancers, which will
lead to their deletion.
Leaking these load balancers causes an issue when the deleted node is re-added
(as part of a remediation procedure, for instance) since the newly created node
logical switch does not point to these node load balancers, thus …
=> [release-4.10] Bug 2113861: reconcile-node-lbs

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Minor conflicts in the 2nd and 3rd commit
=> Bug 2117078: [release-4.7] Multiple ExGW cache validation/improvements

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
When the logical port is already deleted, deleteLogicalPort should
not return an error. Otherwise, delete will be retried up for
maxFailedAttempts (currently set to 15).
This issue introduced in commit be8786a89546effe2de121fce9c05907fae4c1ce
Co-authored-by: Tim Rozet <trozet@redhat.com>
Reported-at: https://issues.redhat.com/browse/OCPBUGS-469
(cherry picked from commit f7fe67d846ba15dddfc23a94b47f6aba46e04fa9)
=> OCPBUGS-658: [release-4.11] pods: deleteLogicalPort should not fail when port is already gone

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
When the logical port is already deleted, deleteLogicalPort should
not return an error. Otherwise, delete will be retried up for
maxFailedAttempts (currently set to 15).
This issue introduced in commit be8786a89546effe2de121fce9c05907fae4c1ce
Co-authored-by: Tim Rozet <trozet@redhat.com>
Reported-at: https://issues.redhat.com/browse/OCPBUGS-469
(cherry picked from commit f7fe67d846ba15dddfc23a94b47f6aba46e04fa9)
=> OCPBUGS-660: [release-4.10] pods: deleteLogicalPort should not fail when port is already gone

go-controller/pkg/node/gateway_shared_intf.go
When service is deleted, we were removing the conntrack
entries before removing the flows/iptable rules. It's
safer to do the reverse so that in the nano second interim
the conntrack entries don't get recreated before the rules/flows
get deleted.
(cherry picked from commit 58b23eaf049e2e1b38dee8f29ee990a181dfa463)
CLEAN PICK from https://github.com/openshift/ovn-kubernetes/pull/1214/commits/58b23eaf049e2e1b38dee8f29ee990a181dfa463
=> [release-4.11] Bug 2111548: Remove conntrack entries after rules

go-controller/pkg/node/gateway_shared_intf.go
When service is deleted, we were removing the conntrack
entries before removing the flows/iptable rules. It's
safer to do the reverse so that in the nano second interim
the conntrack entries don't get recreated before the rules/flows
get deleted.
(cherry picked from commit 58b23eaf049e2e1b38dee8f29ee990a181dfa463)
(cherry picked from commit 525e7f14818e02a913426a1fcdcbec456d8caf75)
CLEAN PICK from https://github.com/openshift/ovn-kubernetes/pull/1218
=> [release-4.10] Bug 2111552: Remove conntrack entries after rules

go-controller/pkg/node/gateway_shared_intf.go
When service is deleted, we were removing the conntrack
entries before removing the flows/iptable rules. It's
safer to do the reverse so that in the nano second interim
the conntrack entries don't get recreated before the rules/flows
get deleted.
(cherry picked from commit 58b23ea)
(cherry picked from commit 525e7f1)
(cherry picked from commit bedef57)
Conflicts from 4.10 since ETP isn't present in 4.9
=> [release-4.9] Bug 2090315: Remove conntrack entries after rules

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Minor conflict in commit 1 on the e2e file since https://github.com/openshift/ovn-kubernetes/commit/e1f7da0fe5072ca8574f0aa98fa0c80ff2c95a92 is missing in 4.11
=> [reelase-4.11] OCPBUGS-772: Fix NP upgrade bug: unexpectedly found multiple equivalent ACLs (arp v/s arp||nd)

Dockerfile
In particular, this bump includes fixes for AVX512 runtime checks:
- dpif-netdev: Refactor AVX512 runtime checks. (#2100393)
- dpif-netdev: Fix leak of AVX512 DPIF scratch pad
- dpif-netdev-extract-avx512: Protect GCC builtin usage
All other changes can be obtained here:
https://access.redhat.com/downloads/content/rhel---8/x86_64/7816/openvswitch2.17/2.17.0-37.4.el8fdp/x86_64/fd431d51/package-changelog
=> OCPBUGS-1553: Dockerfile: bump to openvswitch2.17.0-37.4.el8fdp

go-controller/pkg/ovn/egressgw.go
When the SPK is added and is serving an ICNI namespace, we will search all of the pods in the served namespace to update their routes to point to this new SPK.
If for some reason one of the pods in the namespace has no IPs, we error out trying to add the SPK.
The correct behavior should just be to warn that the pod IPs are missing and continue with adding the SPK.
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
This is fixed in 4.10+ by https://github.com/openshift/ovn-kubernetes/commit/b94351d79ce9770a726678d26be5d67b549be83f
=> Bug OCPBUGS-574: EgressGW: don't error out trying to add SPK when a pod without ip exists

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
We didn't consider this tiny hack that we do
https://github.com/openshift/ovn-kubernetes/blob/44ad75466e486cce605e39513a3ecd9e0b306e7d/go-controller/pkg/libovsdbops/acl.go#L60 there when we wrote https://github.com/openshift/ovn-kubernetes/pull/1259 and unit tests don't actually scream loudly for longer names.
Without this PR we break users who have namespace names longer than 45 characters.
Co-authored-by: Patryk Diak <pdiak@redhat.com>
(cherry picked from commit b10ed7bcc2fe486e6cb8b1a06024227b06abaa71)
/cc @trozet and @jcaamano
=> OCPBUGS-1705: Trim ACL names according to RFC1123

go-controller/pkg/ovn/egressfirewall.go
commit 1: 
revert https://github.com/openshift/ovn-kubernetes/commit/02d349323c254c4c106ff65520835946d75f29ce
which causes new egressfirewall ACLs to be created everytime a new master is elected 
commit 2:
correct the way that egressFirewalls are updated. When updating an
egressfirewall rule we need to check the previous rules priority to
figure out if we actually need to delete it.
=> OCPBUGS-811: [Release 4.9] correct creation and update of egressFirewall 

Dockerfile
In particular, this bump includes fixes for AVX512 runtime checks:
- dpif-netdev: Refactor AVX512 runtime checks. (#2100393)
- dpif-netdev: Fix leak of AVX512 DPIF scratch pad
- dpif-netdev-extract-avx512: Protect GCC builtin usage
All other changes can be obtained here:
https://access.redhat.com/downloads/content/rhel---8/x86_64/7816/openvswitch2.17/2.17.0-37.4.el8fdp/x86_64/fd431d51/package-changelog
=> OCPBUGS-1552: Dockerfile: bump to openvswitch2.17.0-37.4.el8fdp

go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
This is a manual cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3074  from upstream.
=> [release-4.11] Bug 2112100: Forward routes for link-local addresses to vNIC in Windows

Dockerfile
Includes significant performance fixes for load-balancers, northd, and data plane latency. The following links to the specific patches document their performance gains:
https://mail.openvswitch.org/pipermail/ovs-dev/2022-September/397541.html
http://patchwork.ozlabs.org/project/ovn/patch/20220908154620.681323-1-i.maximets@ovn.org/
http://patchwork.ozlabs.org/project/ovn/patch/20220913113329.7576-1-i.maximets@ovn.org/
http://patchwork.ozlabs.org/project/ovn/patch/20220824064051.2525214-1-hzhou@ovn.org/
=> Dockerfile: bump to ovn22.09-22.09.0-5.el8fdp

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Cherry picks https://github.com/openshift/ovn-kubernetes/pull/1281 and https://github.com/openshift/ovn-kubernetes/commit/c20451998bcc62ef5281d1316110ed44219386b9
First cherry-pick had to be modified to use `libovsdbops.BuildACL` instead of `ovn.BuildACL` since we are missing https://github.com/openshift/ovn-kubernetes/commit/44ad75466e486cce605e39513a3ecd9e0b306e7d in 4.11
Second cherry-pick had a very minor conflict outlined in the commit message.
=> OCPBUGS-1750: Trim ACL names according to RFC1123

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
This commit is is not a clean cherry-pick of
https://github.com/openshift/ovn-kubernetes/commit/12848e73062711e67d04bd676d2a7eb84fc7cad2.
This patch ensures that retry logic for pods is after syncPods
is executed. This is accomplished serially with the AddPodHandler
func's parameter 'processExisting' which we pass the syncPods func.
This ensures we exec 'syncPods' once before calling the retry funcs.
However, we need to fix the case where 'syncPods' fails in future
patches.
Also, when addNode() failed in addNodeAnnotations(), the node's IPAM can be
overwritten by subsequent addNode() retry attempts. As the result, the
same IP can be allocated to multiple pods.
All credit to Yun Zhou (yunz@nvidia.com).
=> [release-4.8] Bug 2097018: Duplicated IPs can be assigned to multiple Pods

Dockerfile.base
This is a continuation of commit
https://github.com/openshift/ovn-kubernetes/pull/1273/commits/2c797c4c791a0a0c11a612d4d0103a349ad64ea5
In particular, this bump includes fixes for AVX512 runtime checks:
- dpif-netdev: Refactor AVX512 runtime checks. (#2100393)
- dpif-netdev: Fix leak of AVX512 DPIF scratch pad
- dpif-netdev-extract-avx512: Protect GCC builtin usage
All other changes can be obtained here:
https://access.redhat.com/downloads/content/rhel---8/x86_64/7816/openvswitch2.17/2.17.0-37.4.el8fdp/x86_64/fd431d51/package-changelog
=> OCPBUGS-2085: CARRY: Dockerfile.base: bump to openvswitch2.17.0-37.4.el8fdp

Dockerfile
In particular, this bump includes fixes for AVX512 runtime checks:
- dpif-netdev: Refactor AVX512 runtime checks. (#2100393)
- dpif-netdev: Fix leak of AVX512 DPIF scratch pad
- dpif-netdev-extract-avx512: Protect GCC builtin usage
All other changes can be obtained here:
https://access.redhat.com/downloads/content/rhel---8/x86_64/7816/openvswitch2.16/2.16.0-89.3.el8fdp/x86_64/fd431d51/package-changelog
====
Also [Bumps OVN to 21.12.0-84.el8fdp](https://github.com/openshift/ovn-kubernetes/pull/1271/commits/4ddc9f58e069ac5615f65052e542eeccc17a6d8c), to pull in vendoring changes in ovs sub-module.
=> OCPBUGS-1024: Dockerfile: bump to 2.16.0-89.3.el8fdp

go-controller/pkg/factory/factory.go
In MicroShift, ovnkube-master and ovnkube-node run in a single process/container
which acts as both master and node roles. The NewMasterWatchFactory needs to
initialize a new watch factory for both, otherwise it results in panic watching
endpointSlice which only existed in node watch factory.
This PR creates endpointSlices in master watch factory even it is not used when
master and node are deployed separately, this will be fixed by upstream PR:
https://github.com/ovn-org/ovn-kubernetes/pull/3193.
(cherry picked from commit b6c1b081fb670423a53febc1e62ea9db89abdb63)
=> OCPBUGS-2176: add endpointSlice informer in master process

go-controller/Makefile, go-controller/go.mod, go-controller/hack/test-go.sh, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/cni/OCP_HACKS.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/management-port_test.go, go-controller/pkg/testing/testing.go
Fix unit-test golang image and gofmt.
=> OCPBUGS-2464: Fix the golang image used for unit-tests

go-controller/pkg/ovn/healthcheck/egressip_healthcheck.go
Connecting logic iterates through all the management addresses that egress IP can use to reach its egress nodes. The log, however, was only providing the last one it tried.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-2004
=> OCPBUGS-2004: egress IP: fix log when gRPC connection fails

go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/helper_linux_test.go
Due to the way how IPv6 multipath is implemented, it is not possible to filter by ifindex as the ifindex for multihop routes will always be 0. Instead, implement a custom filter.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1318
(cherry picked from commit 980694d38b56b73b5ffe821d3521061a55e600a2)
=> [release-4.11] OCPBUGS-1955: 4.11 multihop

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
deleteLogicalPort should not fail when its logical switch is already gone. This is needed when handling situations where node has been removed from cluster, but a completed pod remained present after ovnkube master restarts.
https://github.com/ovn-org/ovn-kubernetes/issues/3168
Conflicts:
go-controller/pkg/ovn/pods_test.go
Closes #3168: ovnkube fails to restart after node deletion Reported-at: https://issues.redhat.com/browse/OCPBUGS-1568
(cherry picked from commit b328345fe57f6310550202664d87e2a4317879d5)
=> OCPBUGS-1739: pods: deleteLogicalPort should not fail when ls is gone

go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/helper_linux_test.go
Due to the way how IPv6 multipath is implemented, it is not possible to filter by ifindex as the ifindex for multihop routes will always be 0. Instead, implement a custom filter.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1318
(cherry picked from commit 980694d38b56b73b5ffe821d3521061a55e600a2) (cherry picked from commit 9353ff60cd9abe7cf8de78629ecf892e0981de21)
=> [release-4.10] OCPBUGS-2208: getDefaultGatewayInterfaceByFamily: custom filter for MultiHop

go-controller/pkg/libovsdbops/transact.go
When updating a large number of address_set, logs get flooded with "Configuring OVN" which cannot be reduced.
Also klog shows up in the profiling data as a source of CPU consumption of ovnkube-master.
We make it configurable and assign it a verbosity of 5. Default on OpenShift is 4, however this log is redundant with the "transacting operations" that is already logged with level 4.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1643
Signed-off-by: François Rigault <frigo@amadeus.com>
Signed-off-by: Jamo Luhrsen <jluhrsen@redhat.com>
=> OCPBUGS-1643: Add logging verbosity to configuring OVN logs

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go
Prioritize adding events to handlers for shared resources
When handlers share the informer for the same type of objects - example
egressIP feature also watches for Pods and creates a handler to receive
events for any pod-related activities - it is better to prioritize the
order in which a specific event for a pod will be processed. Pod
creation should happen first, so addLogicalPort should go first before
egressIP Pod handler. Similarly for network policies and other
controllers.
Today OVNK already handles the events serially, the only problem is we
don't control which handler gets the event first, so this PR adds a
priority system for the handlers where by we say all critical handlers
get priority 0 - this is the highest priority and it applies to
pods/namespaces/nodes and all the CRD …
=> OCPBUGS-1520: Prioritize adding events to handlers for shared resources

go-controller/pkg/libovsdbops/transact.go
When updating a large number of address_set, logs get flooded with "Configuring OVN" which cannot be reduced.
Also klog shows up in the profiling data as a source of CPU consumption of ovnkube-master.
We make it configurable and assign it a verbosity of 5. Default on OpenShift is 4, however this log is redundant with the "transacting operations" that is already logged with level 4.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1643
Signed-off-by: François Rigault <frigo@amadeus.com>
Signed-off-by: Jamo Luhrsen <jluhrsen@redhat.com>
=> OCPBUGS-2659: Add logging verbosity to configuring OVN logs

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Cherry-picked from https://github.com/openshift/ovn-kubernetes/pull/1259.
Conflicts are outlined in commit message for each commit.
=> [release-4.10] OCPBUGS-1454: Fix NP upgrade bug: unexpectedly found multiple equivalent ACLs (arp v/s arp||nd)

go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go
Ignore non-ready endpoints when processing endpointslices
In ovn-k node we introduced a regression when replacing endpoints with endpointslices, causing 10x higher disruption times in ingress-to-console/oauth/image-registry new connections in CI upgrade jobs, as reported in #OCPBUGS-1427
Previously we were processing Endpoints from `k8s.io/api/core/v1`, where we get the current list of _ready_ endpoint addresses from  `EndpointSubset.Addresses` and the list of non-ready addresses from `EndpointSubset.NotReadyAddresses`:  https://github.com/openshift/ovn-kubernetes/blob/da6ac5b78ff34d10201edbadb37e7b658b3ea991/go-controller/vendor/k8s.io/api/core/v1/types.go#L4711-L4724
However, endpointslices are defined differently and offer a more fine-grained view of each endpoint, reporting its status …
=> OCPBUGS-1427: Ignore non-ready endpoints when processing endpointslices

go-controller/pkg/libovsdbops/transact.go
When updating a large number of address_set, logs get flooded with "Configuring OVN" which cannot be reduced.
Also klog shows up in the profiling data as a source of CPU consumption of ovnkube-master.
We make it configurable and assign it a verbosity of 5. Default on OpenShift is 4, however this log is redundant with the "transacting operations" that is already logged with level 4.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1643
Signed-off-by: François Rigault <frigo@amadeus.com>
Signed-off-by: Jamo Luhrsen <jluhrsen@redhat.com>
=> OCPBUGS-2660: Add logging verbosity to configuring OVN logs

go-controller/pkg/ovn/acl.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/port_cache.go, go-controller/pkg/syncmap/syncmap.go
This a downstream cherry-pick for network policy fixes, some of the bugs that are fixed listed in the linked bug
https://github.com/ovn-org/ovn-kubernetes/pull/3146
https://github.com/ovn-org/ovn-kubernetes/pull/3161
https://github.com/ovn-org/ovn-kubernetes/pull/3191
https://github.com/ovn-org/ovn-kubernetes/pull/3205
There were 2 merge conflicts:
1. downstream-only fields https://github.com/openshift/ovn-kubernetes/blob/master/go-controller/pkg/ovn/ovn.go#L80-L81 were moved together with `namespaceInfo` struct to namespace
2. https://github.com/openshift/ovn-kubernetes/pull/1300 is merged between commits in this PR upstream, but was cherry-picked downstream before. Therefore some changes for `policy_test.go` were reapplied in correct order, see commit messages for more info on conflict …
=> OCPBUGS-2569: Fix netpol races

go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
These two commits are cherry-picked from upstream https://github.com/openshift/ovn-kubernetes/commit/f9f4ba4b6502d6829fb35048e178106d87ed4dcd and https://github.com/openshift/ovn-kubernetes/commit/a593d57ab5705c66902bae32d887330c0cecb35c
to fix the issue that L3GatewayConfig node annotation
cannot be parsed correctly in the case of no default route.
=> OCPBUGS-2770: Allow empty nexthop in L3GatewayConfig node annotation

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/util/net.go
Brings in https://github.com/openshift/ovn-kubernetes/pull/1143 from 4.11 into 4.10. Conflicts are outlined in each PR. Extra commit (partially, needed parts) picked up from the libovsdb cleanup code to facilitate the backport: https://github.com/openshift/ovn-kubernetes/pull/1049/commits/4e3c26a301830d573bfb7690a2b2cafb3f32a63f
/assign @jcaamano
=> [release-4.10] Bug 2105657: Fix egressIP object deletion if the node is deleted first

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, go-controller/go.mod, go-controller/go.sum, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go, go-controller/vendor/modules.txt
Pulls in the following commits, for which we really just care about the client logging one for performance.
```
64a1543b16 client: don't construct transaction log string when it's not needed
14b9f5b67b Make table name a const above generated model
```
(cherry picked from commit 3b56eb09a6a0fca6ad7e9d2361adf77f2b468120)
=> [release-4.12] OCPBUGS-3346: vendor: bump libovsdb to 8f21d188c3a50d0ce378bd66ec68215967aaad77

Dockerfile, Dockerfile.base, Dockerfile.microshift
Bump base image to Go 1.19, and make sure Microshift uses the same OVN version as the regular image.
We'll use this as the 4.13 change that will unblock:
https://github.com/openshift/ovn-kubernetes/pull/1286
https://github.com/openshift/ovn-kubernetes/pull/1288
https://github.com/openshift/ovn-kubernetes/pull/1287
=> [release-4.13] Update images to be consistent with ART

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/util/ovs.go
This is a OVS dependent work around fix. If we detect that OVS HW Offload is enabled, we are aware that the offloading of packet MTU check support in OVS is not supported. This support will not be available until the offload support for sFlow is added.
In order to have the most optimal performance, the packet MTU check support should be disabled when OVS HW Offload is enabled on the node.
Backport of upstream https://github.com/ovn-org/ovn-kubernetes/pull/3227
(cherry picked from commit 70e0e13bb1bf15a6c5d2b2ca36988ddf74bd5d13)
=> OCPBUGS-3468: Disable packet MTU check when OVS HW Offload is enabled

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
with complex ACL configration ovn-controller
needs additional time to finish its computation
it was recommended by OVN team to set bundle timeout to match flowprobe setting since its default is 10s.
(cherry picked from commit 49ab185eed4db7e88abd189b241a65926bc2b105)
=> OCPBUGS-3773: Adjust ovs bundle timeout

Dockerfile, Dockerfile.base
Mainly to get:
"ovsdb/transaction.c: Refactor assess_weak_refs."
http://patchwork.ozlabs.org/project/openvswitch/list/?series=325800&state=%2A&archive=both
which fixes a memory leak in ovsdb-server.
=> OCPBUGS-3797: [4.13] Dockerfile: bump OVS to 2.17.0-62.el8fdp

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
with complex ACL configration ovn-controller
needs additional time to finish its computation
it was recommended by OVN team to set bundle timeout to match flowprobe setting since its default is 10s.
(cherry picked from commit 49ab185eed4db7e88abd189b241a65926bc2b105) (cherry picked from commit d245a090b323dd0cb8e074d7c9e6710633df3f30)
=> [release-4.10]  OCPBUGS-3858: Adjust ovs bundle timeout

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/healthcheck.go
We were not creating healthchecks for service updates when the etp changed from local to cluster or back. This PR fixes this.
(cherry picked from commit 4c7add6a642689b7429babf1761c13942c3a9577)
=> [release-4.11] OCPBUGS-2554: Fix UpdateService healthport checks

go-controller/pkg/ovn/egressfirewall_dns.go
When nextQueryTime for dns entry is already expired and update goroutine is trying to use negative duration to reset ticker. This causes process crash on the ovnk master. This change avoids proces crash and ensures to trigger ticker in shortest possible time (1 ms) so that update happens immediately on expired dns entry.
(cherry picked from commit 378425472307e08f238deef8eb72ea498852d287)
=> [release-4.12] OCPBUGS-3977: Handle expired entry while handling dns update

Dockerfile, Dockerfile.base
This is being done to get:
* Tue Nov 15 2022 Mark Michelson <mmichels@redhat.com> - 22.09.0-13
- ovn-controller: Fix some issues with CT zone assignment. (#2126406) [Upstream: 0fc041667031da20cd03c0b76de8de3dbe502d50]
for the corresponding bug I have in OVNK. Side effect is I also get the lb session affinity fixes from OVN which are cherry-picked downstream only even if its not yet release for main OVN upstream rpms.
Other changes coming in are: 
https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2282903
```
* Tue Nov 29 2022 Lorenzo Bianconi <lorenzo.bianconi@redhat.com> - 22.09.0-22 
* - northd: rely on new actions for lb affinity [Upstream: 5b6223dcb6060205c6e9d4e8c092e96134bb032a]  
* Tue Nov 29 2022 Lorenzo Bianconi <lorenzo.bianconi@redhat.com> - 22.09.0-21 
* - actions: …
```
=> OCPBUGS-799: Bump OVN to 22.09.0-22

Dockerfile.base, Dockerfile.microshift
Mainly to get:
"ovsdb/transaction.c: Refactor assess_weak_refs."
http://patchwork.ozlabs.org/project/openvswitch/list/?series=325800&state=%2A&archive=both
which fixes a memory leak in ovsdb-server.
4.12 cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1362
=> OCPBUGS-3798: [4.12] Dockerfile: bump OVS to 2.17.0-62.el8fdp

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/pod_annotation.go
Cherry picked from commit b0efc6b31d72437cd576a8f60eb6e13e3195ca85
Merge conflicts:
- cmd/ovnkube-trace/ovnkube-race.go
- pkg/node/gateway_iptables.go
- pkg/node/gateway_shared_intf_linux.go (resolving merge conflict resulted in no change)
- pkg/node/gateway_shared_intf.go
- pkg/node/healthcheck.go
- pkg/node/node.go
- pkg/ovn/controller/egress_services/egress_services_service.go (not present in 4.11)
=> OCPBUGS-3908: [release-4.11] Support proper parsing of IPs with leading zeros

Dockerfile
https://github.com/openshift/ovn-kubernetes/pull/1387 was supposed to do this but due to some refactors/rebases, ended up only doing it for microshift.
Mainly to get:
"ovsdb/transaction.c: Refactor assess_weak_refs."
http://patchwork.ozlabs.org/project/openvswitch/list/?series=325800&state=%2A&archive=both
which fixes a memory leak in ovsdb-server.
4.12 cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1362
=> OCPBUGS-3798: [4.12] Dockerfile: bump regular image to OVS 2.17.0-62

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/informer/informer.go, go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go
Sometimes k8s watcher getting restarted and for this condition update events are sent for all updated resources. If the object was recreated with same namespace and name while the watcher was off, ovnk gets update event where old and new objects have different UIDs.
Hence this commit handles such scenario by comparing object UIDs, deleting resources for old object followed by adding resources for new object.
(cherry picked from commit bcd6124549e2e9ced9a397dc21c02f26f651bedd)
=> [release-4.12] OCPBUGS-3390: Handle k8s watcher restart scenario

go-controller/pkg/ovn/pods.go
Issue: When a new ovnkube master starts, or gains leadership through leaderelection, addLogicalPort is called for all existing pods to ensure they are set up correctly, which means we recollect the podCreated metrics on pods that may not need it, and we will set an incorrect creation latency for pods.
Solution: Do not record pod creation latency metric for pods with annotations or pods with existing logical switch ports when addLogicalPort is ran
Signed-off-by: Ben Pickard <bpickard@redhat.com>
(cherry picked from commit b481ef0cbd240eb3abd767c706f76f4727c5a44a)
=> [Release 4.12] OCPBUGS-3397: Avoid Remetric pods

go-controller/pkg/ovn/egressip.go
Missing backports, clean cherry-picks without conflicts
=> [release-4.11] OCPBUGS-4167: EgressIP: Merge ops into pendingCloudPrivateIPConfigsOps on add

Dockerfile, Dockerfile.base, Dockerfile.microshift
Use ovn-kubernetes-base as base image when building
OpenShift ovn-kubernetes image
Co-authored-by: Dan Williams <dcbw@redhat.com>
=> Update base image of Dockerfile

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/kube.go
deleteLogicalPort should not fail when node is already deleted from lsManager's cache.
Cherry pick from DS merge: https://github.com/openshift/ovn-kubernetes/pull/1410
https://github.com/openshift/ovn-kubernetes/pull/1410/commits/b489b145a7bf794a8c256483e8a1e284c12d3c64
Also back porting fixes from the following jiras here, which are all related to similar issues:
-  https://github.com/openshift/ovn-kubernetes/pull/1400/commits/a1b961d5ee5b544c138fad9c863ef56933bf0515 -- tracked via [OCPBUGS-4554](https://issues.redhat.com/browse/OCPBUGS-4554)
-  https://github.com/openshift/ovn-kubernetes/pull/1410/commits/719fe895c2fad9509f208b2813847e432ad4ddac -- tracked via [OCPBUGS-4553](https://issues.redhat.com/browse/OCPBUGS-4553)
=> [release-4.12] OCPBUGS-4505: pods: deleteLogicalPort should not fail when node is gone

Dockerfile.base
* Tue Dec 06 2022 Dumitru Ceara <dceara@redhat.com> - 22.09.0-24
- northd: Include VIP port in LB affinity learn flow matches. (#2150533)
[Upstream: cc037c7538d635e7d014e98935a83bc15140674f]
@tssurya
=> OCBUGS-4502: Dockerfile: bump OVN to 22.09.0-25

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
BP 4.13 changes to 4.12
There's only a minor remaining difference:
~~~
[akaris@linux go-controller (bp-ovnkube-trace)]$ git diff HEAD downstream/master -- cmd/ovnkube-trace/ovnkube-trace.go
diff --git a/go-controller/cmd/ovnkube-trace/ovnkube-trace.go b/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
index 5a247ae3a..4fe3643d7 100644
--- a/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
+++ b/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
@@ -252,7 +252,7 @@ func getPodMAC(client *corev1client.CoreV1Client, pod *kapi.Pod) (podMAC string,
podMAC = nodeMAC.String()
}
} else {
-               podAnnotation, err := util.UnmarshalPodAnnotation(pod.ObjectMeta.Annotations)
+               podAnnotation, err := util.UnmarshalPodAnnotation(pod.ObjectMeta.Annotations, types.DefaultNetworkName) …
=> [release-4.12] OCPBUGS-4361: Bp ovnkube trace changes

Dockerfile, Dockerfile.base
* Tue Dec 06 2022 Dumitru Ceara <dceara@redhat.com> - 22.09.0-24
- northd: Include VIP port in LB affinity learn flow matches. (#2150533)
[Upstream: cc037c7538d635e7d014e98935a83bc15140674f]
=> OCPBUGS-4503: [release-4.12] Dockerfile: bump OVN to 22.09.0-25

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/mutate.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/transact.go, go-controller/vendor/modules.txt
panic: reflect: call of reflect.Value.Len on ptr Value
ovn-org/libovsdb@75c4d77
(cherry picked from commit 8d63443)
=> OCPBUGS-4598: Bumps libovsdb to pick up fixes for optional values

go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/types.go, test/scripts/e2e-kind.sh
This PR adds support for session affinity
timeout which is required for OVNK plugin to
become CNCF complaint and pass the conformance
tests around this feature.
NOTE: Most of the work has been done in OVN,
only bit OVNK does is to enable this in the
right manner as an option on the load balancer
if a service with session affinity is created.
OVN version bump is being done in the fedora
image used to the build.
NOTE2: We used to use the selectionFields option
before, this is no longer needed because there can never be a session affinity without a timeout set
(defaults to 3hrs), so if affinity-timeout is set
then OVN does the rest of the logic to determin
stickyness.
NOTE3: Is the stickness timeout calculated for
packets or sessions? (can't remember what IPVS
does and OVN does) :( so do we …
=> OCPBUGS-4503: Support LB Session Affinity TimeOut

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/kube.go
deleteLogicalPort should not fail when node is already deleted from lsManager's cache.
Cherry pick from https://github.com/openshift/ovn-kubernetes/pull/1419
Also back porting fixes from the following jiras here, which are all related to similar issues:
[OCPBUGS-4617](https://issues.redhat.com/browse/OCPBUGS-4617)
[OCPBUGS-4618](https://issues.redhat.com/browse/OCPBUGS-4618)
=> [release-4.11] OCPBUGS-4564: pods: deleteLogicalPort should not fail when node is gone

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/ovn.go
This is a cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3267.
There were conflicts caused by https://github.com/ovn-org/ovn-kubernetes/pull/3258 not being in 4.12.
/cc @flavio-fernandes @tssurya 
/assign @jcaamano 
(cherry picked from commit 2cf92683cc3d307d055ff17d93b90408cbf17c78)
=> [release-4.12] OCPBUGS-3378: Set the node as reachable only when it is being added as an egressip node

go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/network-controller-manager/network_controller_manager.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_cleanup.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/topology_version.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go, go-controller/pkg/util/node_annotations.go
Heavy conflicts in between pods.go and base_network_controller_pods.go. Due to the restructuring of code for secondary controllers, the controllers have been divided up into default network controller (oc) and base network controller (bnc). The add logical port functionality was also split between  the two. However, the split doesn't work for our downstream carry. The new split does this:
1. oc.addLogicalPort -> bnc.addLogicalPortToNetwork
2. bnc.addLogicalPortToNetwork takes care of assigning IPs, addRoutesGatewayIP
3. oc.addLogicalPort -> routingExternalGWs, routingPodGWs, addOps, err := oc.addPodToNamespace(pod.Namespace, podAnnotation.IPs)
For our ICNIv1 we have a modified version of addRoutesGatewayIP which needs to know the routingExternalGWs, routingPodGWs, hybridOverlayExternalGW …
=> OCPBUGS-4659: [DownstreamMerge] - 12-12-22

go-controller/pkg/ovn/egressfirewall_dns.go
When nextQueryTime for dns entry is already expired and update goroutine is trying to use negative duration to reset ticker. This causes process crash on the ovnk master. This change avoids proces crash and ensures to trigger ticker in shortest possible time (1 ms) so that update happens immediately on expired dns entry.
(cherry picked from commit 378425472307e08f238deef8eb72ea498852d287) (cherry picked from commit c68ba05fcc6b45300b67cdced86e71553c0105c5)
=> [release-4.11] OCPBUGS-4475: Handle expired entry while handling dns update

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go
The problems that are fixed, and perf improvement:
1. don't retry unscheduled pod, wait for update event instead. 
2.  Cleanup pod handler for namespaceAndPod handler on namespace delete
event.
3. Only update localPods after successful db transaction, 
return fast from localPod handlers based on `np.localPods`
4. Don't retry fetching lsp from the lspCache, that "stops" the handler for 1 second
5.  Use stored portUUID to delete local pods instead of getting that info
from lspCache
=> OCPBUGS-3778: [release-4.10] Netpol races partial fixes

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/kube.go
deleteLogicalPort should not fail when node is already deleted from lsManager's cache.
Cherry pick from https://github.com/openshift/ovn-kubernetes/pull/1422
Also back porting fixes from the following jiras here, which are all related to similar issues:
[OCPBUGS-4622](https://issues.redhat.com/browse/OCPBUGS-4622)
[OCPBUGS-4623](https://issues.redhat.com/browse/OCPBUGS-4623)
=> [release-4.10] OCPBUGS-1568: pods: deleteLogicalPort should not fail when node is gone

go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/policy.go
Small changes that should have a big impact on perf/scale with network policies:
1. Avoid sending address_set txns when they are not needed
2. Avoid sending port_group txns when they are not needed for network policies
3. If a network policy has a namespace and pod selector, where the namespace selector matches on all namespaces, only add a single handler rather than number of namespaces handlers.
=> OCPBUGS-4760: [4.12] Avoid duplicate transactions and minimize handlers with empty namespace selectors

go-controller/pkg/ovn/master.go
Commit 16ea40be changed the logical switch other-config to be overwriten this needs to be changed so that the hostsubnet values are appended.
=> [release-4.11] OCPBUGS-3116: append instead of overwrite logicalSwitch other-config

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/metrics.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go, go-controller/vendor/modules.txt
Backport of https://github.com/ovn-org/libovsdb/pull/342 (see also 4.12 version https://github.com/openshift/ovn-kubernetes/pull/1348)
fmt.Sprintf() will be evaluated before the logging function is called, which means that even if the logging level is less than V(4) we'll still construct the whole string for the operation, just to discard it. That can be pretty expensive.
=> OCPBUGS-3614: [4.11] CARRY: client: don't construct transaction log string when it's not needed

go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/policy.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1439
=> OCPBUGS-4860, OCPBUGS-4838: [release-4.11] Avoid duplicate transactions and minimize handlers with empty namespace selectors

go-controller/pkg/retry/obj_retry.go
Previously delete events were being ignored for completed pods. This would end up leaking the pod and IP if for some reason we never got an update event signalling the pod was completed.
=> OCPBUGS-4884: [release-4.12] Fixes scenario where deleted + completed pods may leak

go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/policy.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1447
Conflict: update GetPortGroup to use CreateOrUpdate with empty
update fields, since older version of modelClient doesn't have
Lookup method.
=> OCPBUGS-4861, OCPBUGS-4839: [release-4.10] Avoid duplicate transactions and minimize handlers with empty namespace selectors

go-controller/pkg/ovn/obj_retry.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1451
stashed 2 first commits into one.
=> OCPBUGS-4887: [release-4.11] Fixes scenario where deleted + completed pods may leak

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_cleanup.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1446
Merge conflicts:
- added egressFirewallACLExtIdKey constant and replaced old string usages
- go-controller/pkg/ovn/policy_test.go: use old method newNetworkPolicy
to create network policy for the test
=> OCPBUGS-4863: [release-4.11] Fix address set cleanup: only delete address sets owned by given object

go-controller/pkg/ovn/ovn.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1455
changes were moved from `retryObjs` to `Controller`
=> OCPBUGS-4888: [release-4.10] Fixes scenario where deleted + completed pods may leak

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_cleanup.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1448
Conflicts:
Use old methods to get acls from the db.
Remove EgressQos address set check, since it is not present on 4.10
=> OCPBUGS-4864: [release-4.10] Fix address set cleanup: only delete address sets owned by given object

go-controller/hybrid-overlay/pkg/controller/master.go
commit 711237766b25e0728006eacb8dc1478b1ce359bb introduced the issue where we do not add the Hybrid overlay Cluster subnets to the allocator
fix that issue by adding the HYbrid Overlay Cluster subnets so that they can be allocated.
=> OCPBUGS-4992:  [release-4.11] fixing hybrid subnet allocator

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1406 (only the last commit, which is the fix)
=> OCPBUGS-4655: [release-4.11] Don't delete equivalent ACLs by predicate, since it will fail if

go-controller/pkg/retry/obj_retry.go
Don't log in iterateRetryResources when there are no retry entries
Original upstream PR: https://github.com/ovn-org/ovn-kubernetes/pull/3270
Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>
(cherry picked from commit 3ca6336a0e0c749568ba22ad8e6a8a80f25baf87)
Closes #OCPBUGS-4383
=> [release-4.12] Bug OCPBUGS-4383: Don't log in iterateRetryResources when there are no retry entries

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go
egressip node update: set the node as reachable only when it is being added as an egressip node
there are three places where ovnkube marks an egress node as reachable:
- node add event handler
- node update even handler
- periodic connectivity checker
In a scenario where the egressip node becomes reachable at the same time as the node object is updated
the node is set as reachable but because there was no label/readiness change it is never added as an egressip node.
The periodic check will then ignore the node because it considers it as already reachable.
To address the issue only set the node as reachable if it is actually getting added as an egressip node.
Conflicts:
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/obj_retry_master.go --> go-controller/pkg/ovn/obj_retry.go …
=> [release-4.11] OCPBUGS-4829: Set the node as reachable only when it is being added as an egressip node

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go
cherry-pick: 82dcb005b966c1f71792a464bab038f54f991c8c, dabaf9fb8e024d8a52fbb1dc470fdce596caf505 the former did not apply cleanly but only needed a minor revision in AllocateHybridOverlay() the ladder did apply cleanly. 
This fixes allocation of the hybrid overlay DRIP by insuring that it will not collide with the IP of a new pod. 
=> OCPBUGS-3651: [release-4.12] cherry-pick hybrid overlay fixes from master branch 

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, test/scripts/test-ovnkube-trace.sh
Minimal conflicts in a couple of cherry-picks due to b0efc6b31 landing out of order.
ovnkube-trace is exactly the same now as for 4.12:
~~~
[akaris@linux ovnkube-trace (OCPBUGS-1720b)]$ pwd
/home/akaris/development/ovn-kubernetes/go-controller/cmd/ovnkube-trace
[akaris@linux ovnkube-trace (OCPBUGS-1720b)]$ ll
total 48
-rw-r--r--. 1 akaris akaris 48971 Dec 12 21:33 ovnkube-trace.go
[akaris@linux ovnkube-trace (OCPBUGS-1720b)]$ git diff downstream/release-4.12 -- ovnkube-trace.go
[akaris@linux ovnkube-trace (OCPBUGS-1720b)]$ 
~~~
=> [release-4.11] OCPBUGS-1720: Backport changes to ovnkube-trace

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/hybrid_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go, test/e2e/service.go
A series of patches around 947e8d450ebaa8ce4ab81cb480a419618f1508c7
in the ovn-org/ovn repository now enable check_pkt_larger for gateway
router ports. Take advantage of this new feature to solve https://issues.redhat.com/browse/OCPBUGS-2827
Also see: http://patchwork.ozlabs.org/project/ovn/cover/cover.1627405420.git.lorenzo.bianconi@redhat.com/
Conflicts:
* go-controller/pkg/ovn/default_network_controller.go
File only exists in master, not in 4.12. 
Move change from default_network_controller.go (https://github.com/openshift/ovn-kubernetes/commit/b240dbac9146f00b1895231087b283f7791aa3fe#diff-3f6ed978237c56cacb91eb947304ed9e429edf24d8d358be806093b0f061e154)  to obj_retry_master.go  (https://github.com/ovn-org/ovn-kubernetes/commit/b96cd9fd7469bafc7de3a03613c37afea0b142a1 [this is from an …
=> [release-4.12] OCPBUGS-4533: Move check_pkt_larger to gateway router ports

Dockerfile
Mainly to get:
"ovsdb/transaction.c: Refactor assess_weak_refs."
http://patchwork.ozlabs.org/project/openvswitch/list/?series=325800&state=%2A&archive=both
which fixes a memory leak in ovsdb-server.
Cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1387
=> OCPBUGS-4761: [4.11] Dockerfile: bump OVS to 2.17.0-62.el8fdp

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
egressip node update: set the node as reachable only when it is being added as an egressip node
there are three places where ovnkube marks an egress node as reachable:
- node add event handler
- node update even handler
- periodic connectivity checker
In a scenario where the egressip node becomes reachable at the same time as the node object is updated
the node is set as reachable but because there was no label/readiness change it is never added as an egressip node.
The periodic check will then ignore the node because it considers it as already reachable.
To address the issue only set the node as reachable if it is actually getting added as an egressip node.
=> [release-4.10] OCPBUGS-5299: Set the node as reachable only when it is being added as an egressip node

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
The tests were copying the podAssignment cache under the cache's lock, but unfortunately it was just a shallow-copy of element of that cache. Maps within structs are copied by reference, not by value (eg deep-copy), so neither the 'egressStatuses' nor the 'standbyEgressIPNames' members of each podAssignmentState element were deep-copied.
This led to data races in the tests like:
```
2022-10-27T13:00:36.6560710Z WARNING: DATA RACE
2022-10-27T13:00:36.6560988Z Write at 0x00c01c6480c0 by goroutine 1527:
2022-10-27T13:00:36.6561275Z   runtime.mapdelete_faststr()
2022-10-27T13:00:36.6561762Z       /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/map_faststr.go:301 +0x0
2022-10-27T13:00:36.6562144Z   k8s.io/apimachinery/pkg/util/sets.String.Delete()
2022-10-27T13:00:36.6563012Z …
```
=> OCPBUGS-5046: [release-4.12] egressip: fix test data race accessing podAssignment cache

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
The tests were copying the podAssignment cache under the cache's lock, but unfortunately it was just a shallow-copy of element of that cache. Maps within structs are copied by reference, not by value (eg deep-copy), so neither the 'egressStatuses' nor the 'standbyEgressIPNames' members of each podAssignmentState element were deep-copied.
This led to data races in the tests like:
```
2022-10-27T13:00:36.6560710Z WARNING: DATA RACE
2022-10-27T13:00:36.6560988Z Write at 0x00c01c6480c0 by goroutine 1527:
2022-10-27T13:00:36.6561275Z   runtime.mapdelete_faststr()
2022-10-27T13:00:36.6561762Z       /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/map_faststr.go:301 +0x0
2022-10-27T13:00:36.6562144Z   k8s.io/apimachinery/pkg/util/sets.String.Delete()
2022-10-27T13:00:36.6563012Z …
```
=> OCPBUGS-5766: egressip: fix test data race accessing podAssignment cache

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_dns.go, go-controller/pkg/ovn/egressfirewall_dns_test.go, go-controller/pkg/ovn/egressfirewall_test.go, test/e2e/e2e.go
backport of https://github.com/ovn-org/ovn-kubernetes/pull/3338
which was merged https://github.com/openshift/ovn-kubernetes/pull/1474
Conflicts: rename DefaultNetworkController to Controller.
=> OCPBUGS-5923: [release-4.12] Fix egress firewall to allow inbound connections in both gw modes 

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/healthcheck.go
Clean backport of fixes that fix locking around healthchecks and handle updates correctly.
=> OCPBUGS-5077: [release-4.10] Fix load balancer health check locking and update

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_dns.go, go-controller/pkg/ovn/egressfirewall_dns_test.go, go-controller/pkg/ovn/egressfirewall_test.go, test/e2e/e2e.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1477
Minor conflicts in the test files
Conflicts:
go-controller/pkg/ovn/egressfirewall_dns_test.go -
TestifyMockHelper doesn't allow to set exact call args in that version,
update to only check types.
go-controller/pkg/ovn/egressfirewall_test.go -
add acls that are not garbage-collected.
=> OCPBUGS-5928: [release-4.11] Fix egress firewall to allow inbound connections in both gw modes

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/pods_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1471
=> [release-4.10] OCPBUGS-5990: egressip: fix test data race accessing podAssignment cache

Dockerfile.base
Bumped OVN to latest available for 22.09.
Bring in a fix allowing ovn-trace to connect to SB followers.
All additional changes listed in the commit message.
=> [release-4.12] OCPBUGS-298: Bump OVN to 22.09.0-54

go-controller/pkg/libovsdbops/lbgroup.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go
use ErrNotFound=false for operations that delete loadbalancer from swtich, router, and port group. If a given object is not found, it's noop and not error.
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
(cherry picked from commit 9757ba8020e5921824123d32e3efa36b97d0d4d6)
DownstreamMerge https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream https://github.com/ovn-org/ovn-kubernetes/pull/3388
=> OCPBUGS-6812: [release-4.12] Ensure loadbalancer cleanup doesn't fail

go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go
https://github.com/ovn-org/libovsdb/pull/342 (see also 4.12 version https://github.com/openshift/ovn-kubernetes/pull/1348 and 4.11 version https://github.com/openshift/ovn-kubernetes/pull/1374)
fmt.Sprintf() will be evaluated before the logging function is called, which means that even if the logging level is less than V(4) we'll still construct the whole string for the operation, just to discard it. That can be pretty expensive.
=> OCPBUGS-3615: [4.10] CARRY: client: don't construct transaction log string when it's not needed

go-controller/pkg/node/management-port-dpu.go, go-controller/pkg/node/management-port.go, go-controller/pkg/node/management-port_dpu_test.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/util/mocks/NetLinkOps.go, go-controller/pkg/util/net_linux.go
When ovnkube-node configures management port interface it may fail if host already have it configured but it is different interface. To handle that do the following:
- verify that port exists on the integrational bridge and it represents provided management port netdevice or OVS internal port, if no netdevice were provided;
- verify that no interface exists with the name of the management port;
If any of the checks had failed then need to remove port from the bridge, unless it is OVS internal port and we expect it; flush IP addresses, routes, tables from management netdevice interface. Both representor and netdevice interfaces renamed to original names, if latter stored in OVS database, or to generic names: {net|rep} + ddmmyyHHMMSS
Because ovnkube doesn't have unload sequence, port check …
=> OCPBUGS-5841: ovnkube-node: Existing management port check

Dockerfile.base
OVN Load Balancers should allow all "related" ICMP error messages to pass through
https://bugzilla.redhat.com/show_bug.cgi?id=2126083
apply-after-lb ACL breaks hairpinning
https://bugzilla.redhat.com/show_bug.cgi?id=2103086
the first ping from pod to external would fail
https://bugzilla.redhat.com/show_bug.cgi?id=2129283
Lack of udp conntrack entries in ovn lb hairpin testing while no port specified
https://bugzilla.redhat.com/show_bug.cgi?id=2157846
ovn-controller: Fix initial requested SNAT zone assignment
https://bugzilla.redhat.com/show_bug.cgi?id=2160403
northd: Add logical flows to allow rpl/rel traffic in acl_after_lb stage
https://bugzilla.redhat.com/show_bug.cgi?id=1947807
=> OCPBUGS-4909: Dockerfile: bump OVN to 22.12.0-18

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
There is no need to access the leader.
Additionally SBDB is exposed as a single openshift route in HyperShift, even if running in clustered mode.
(cherry picked from commit 539b5e723a4eb2b05bd4a610f487df1bea7a58bc)
=> [release-4.12] OCPBUGS-298: ovnkube-trace: run ovn-sbctl and ovn-trace with --no-leader-only

go-controller/pkg/ovn/master.go
Unclean backport of: e1cb4f0af669d020fa4b78e3a01256773761b75e
upstream changed the DeleteNode() to DeleteSwitch() and act on the switch name. Since I am not backporting that I had to change the name of the function call used 
Currently when deleting a noHostSubnet node the operation always fails because we are trying to delete ovn constructs that only get created for typical nodes.
Change the deletion of noHostSubnet nodes to only delete the logical switch and in the case of hybrid overlay the allocated subnet
=> [release-4.12] OCPBUGS-4862: Correct the deletion of noHostSubnet nodes

Dockerfile, Dockerfile.base, Dockerfile.microshift
this change moves ovn/ovs versions to dockerfile.base that's shared between microshift and openshift.
future version update only needs to be done once in the dockerfile.base
=> [release-4.12] OCPBUGS-6961: update base image of Dockerfile

go-controller/pkg/libovsdbops/lbgroup.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1498
Conflicts: handle libovsdbclient.ErrNotFound as no error instead of
using ErrNotFound=false
=> OCPBUGS-6814: [release-4.10] Ensure loadbalancer cleanup doesn't fail

go-controller/pkg/node/gateway_shared_intf.go
This PR fixes two traffic flows:
1) podCIDR to svcCIDR:unexposedPort. This flow currently sends the packets towards br-ex in both gateway modes since OVN LB's won't DNAT and OVN doesn't know what to do then other than to send these packets out. However the argument here is svcCIDR is a private range, these packets shouldn't be sent outside. Hence like SDN let's drop them.
2) nodeCIDR to svcCIDR:unexposedPort. Same as above.
Fix: Add a new flow at 105 priority right above the default 100 priority flow (that sends the pkt out to primary interface if coming from OVN) which will drop it instead of sending it out the primary interface.
cookie=0xdeff105, duration=7804.947s, table=0, n_packets=18, n_bytes=1332, idle_age=6984, priority=105,ip,in_port=2,nw_dst=10.96.0.0/16 actions=drop …
=> [release-4.12] OCPBUGS-3399: Drop in-cluster traffic towards svcCIDR at wrong port

go-controller/pkg/ovn/policy.go
This is not a clean application of https://github.com/openshift/ovn-kubernetes/commit/bc941c289d6e8ddfd6fcee4e31fb85100ae97cf8 but it gets the functionality. There would have been many more patches to backport if we wanted a clean application of the upstream patch. 
Direction of the ACLs built for multicast egress policy was always
"from-lport", so we cannot determine if we need to update egress ACL
direction based on the first egress ACL that found.
=> [release-4.10] Bug 2092895: update all egress ACLs' direction to "from-lport"

Dockerfile.rhel9
We're installing from RPMs so we don't need the copy anymore, plus the 'cli' image doesn't exist in RHEL9 streams.
=> rhel9: remove stray `oc` install

Dockerfile, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go, go-controller/pkg/util/ovs.go, test/e2e/service.go
A series of patches around 947e8d450ebaa8ce4ab81cb480a419618f1508c7
in the ovn-org/ovn repository now enable check_pkt_larger for gateway
router ports. Take advantage of this new feature to solve https://issues.redhat.com/browse/OCPBUGS-2827
Also see: http://patchwork.ozlabs.org/project/ovn/cover/cover.1627405420.git.lorenzo.bianconi@redhat.com/
For release 4.11, this means that OVN 22.06.0-101 or newer would be required. Bumping release 4.11 to pick up
that change is being done by @martinkennelly and I cherry picked it to this PR.
Conflicts:
- go-controller/pkg/node/gateway.go
- Logic for SetGatewayMTUSupport needed to account for missing DPU changes that are not part of 4.11. In other words, work w/out  https://github.com/openshift/ovn-kubernetes/pull/1368
- …
=> [release-4.11] OCPBUGS-5245: Move check_pkt_larger to gateway router ports

Dockerfile.rhel9
The python script bits of OVS that used this switch to Python's built-in SSL implementation in 3.0+.
=> rhel9: no longer need python3-pyOpenSSL

Dockerfile.rhel9
=> rhel9: oc RPM does the kubectl symlink

Dockerfile, Dockerfile.base
Using the host's iptables was necessary when the container image might have been running on RHEL7 BYOH, but given that's no longer possible, we can clean this up and just use the container's iptables (since both it and the host will be iptables-nft).
=> iptables: use container iptables, not the host's

Dockerfile, Dockerfile.rhel9
They're already installed by the base Dockerfiles.
=> cleanup: drop redundant selinux-policy install in onvkube dockerfiles

Dockerfile.base.rhel9, Dockerfile.rhel9
Make the same change for rhel9 as https://github.com/openshift/ovn-kubernetes/pull/1481 did for rhel8.
Also install procps-ng to get sysctl, which ovnkube wants.
=> rhel9: no longer need to use iptables wrappers

Dockerfile, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/types.go, test/scripts/e2e-kind.sh
See individual commits for more details.
/cc @dcbw @trozet : for help with risk analysis.
=> [release-4.11] OCPBUGS-7319: Bump OVN to 22.09, enable session affinity timeout

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/net.go
There might be circumstances where the node status internal IPs are not current (in our case, a dual-stack conversion procedure in which kubelet is not configured with the newly acquired IPv6 address and restarted, which in itself is a problem that would need to be fixed).
While node status IPs are preferred to avoid issues with IPs that the user or other components might arbitrarily add to the gateway interface, fallback to an interface IP if we are missing it from the node status.
Also fix DPU. Masquerading should not be needed in the DPU (when newSharedGateway is called with mode NodeModeDPU), only in the host (where initGatewayDPUHost is use instead for NodeModeDPUHost). Ref: https://github.com/openshift/ovn-kubernetes/blob/master/docs/design/dpu_support.md
Signed-off-by: Jaime …
=> [release-4.12] OCPBUGS-6040: addMasqueradeRoute: fallback to gateway interface IPs

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go
clean cherry-pick of: 1ff6e794c0597d72ff7576722e7fb4016383bfb6
=> OCPBUGS-3656: Fixes dualstack clusterIPs for network policy svc handler

go-controller/pkg/node/gateway_shared_intf.go
This PR fixes two traffic flows:
1) podCIDR to svcCIDR:unexposedPort. This flow currently sends the packets towards br-ex in both gateway modes since OVN LB's won't DNAT and OVN doesn't know what to do then other than to send these packets out. However the argument here is svcCIDR is a private range, these packets shouldn't be sent outside. Hence like SDN let's drop them.
2) nodeCIDR to svcCIDR:unexposedPort. Same as above.
Fix: Add a new flow at 105 priority right above the default 100 priority flow (that sends the pkt out to primary interface if coming from OVN) which will drop it instead of sending it out the primary interface.
cookie=0xdeff105, duration=7804.947s, table=0, n_packets=18, n_bytes=1332, idle_age=6984, priority=105,ip,in_port=2,nw_dst=10.96.0.0/16 actions=drop …
=> [release-4.11] OCPBUGS-6640: Drop in-cluster traffic towards svcCIDR at wrong port

Dockerfile.base, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go
See
https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2343944
for details.
NOTE: This is mainly being done to bring in 4.12 to latest plus
to avoid having to maintain the downstream specific commits
around session affinity timeout on the OVN side.
=> [release-4.12] OCPBUGS-7026: Bump OVN to 22.12 and turn off neighbour response in router options.

Dockerfile, Dockerfile.base, Dockerfile.base.rhel9, Dockerfile.rhel9
We're already using DNF instead of yum through DNF's yum compat CLI. Just switch to DNF. Use `--nodocs` to prevent installing documentation dependencies. Remove the
`skip_missing_names_on_install=False` option because that's the default DNF behavior already.
=> Dockerfiles: switch to dnf

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3371 merged in downstream https://github.com/openshift/ovn-kubernetes/commit/87fb483e211cc0e3cd409af5a5d5916e87200539.
Conflicts: go-controller/pkg/ovn/egressip_test.go (on the new test with `logicalPortCache.add`, `logicalPortCache.get` and `util.GetAllPodIPs`)
(cherry picked from commit 87fb483e211cc0e3cd409af5a5d5916e87200539)
=> OCPBUGS-7317: [release-4.12] Delete stale egress ip snat entries by node

Dockerfile.base.rhel9
New OpenFlow extension NXT_CT_FLUSH to flush connections matching the specified fields. Used by OVN 22.03 to automatically flush conntrack on load balancer changes. (rhbz#1839103)
"ovs-appctl ofproto/trace" command can now display port names with the "--names" option.
=> rhel9: bump to openvswitch3.1-3.1.0-2.el9fdp

Dockerfile.base.rhel9
Brings performance improvements and some new features, most notable are:
- controller: Flush CT for removed LB backends https://bugzilla.redhat.com/1839103
- northd: 30%+ performance and memory improvement in LB heavy scenarios https://patchwork.ozlabs.org/project/ovn/list/?series=341076&archive=both&state=*
- northd: automatically trim memory when idle
=> rhel9: bump to ovn23.03-23.03.0-preview.4

go-controller/pkg/ovn/base_network_controller_pods.go
the function call CreateOrUpdateLogicalSwitchPortsOnSwitchOps in pkg/ovn/base_network_controller_pods.go was changed from 
libovsdbops.CreateOrUpdateLogicalSwitchPortsOnSwitchOps(bnc.nbClient, nil, ls, lsp) 
to
libovsdbops.CreateOrUpdateLogicalSwitchPortsOnSwitchOps(bnc.nbClient, ops, ls, lsp) 
during downstream merge
e2acc11f7d6c879fa24f0b047bad235267fe5359
correcting to remove the upstream delta
=> Removal of small code delta from upstream

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Manual backport of https://github.com/openshift/ovn-kubernetes/commit/4ba7fefe8b6b35e4230069f068bc21209680b840,  Resolved conflicts in [router.go](https://github.com/openshift/ovn-kubernetes/pull/1542/files#diff-5d62dde13a2856ea3d4b324968dbaeed261fcb74cb3b81909edf40a6634fa1f4R602-R626), egressip.go's [1](https://github.com/openshift/ovn-kubernetes/pull/1542/files#diff-0f91bbc7bdb15165a9fc2e1cf7492425cbf1cbd35bf3daa22a000fc4027c9b9eR1314-R1320) and [2](https://github.com/openshift/ovn-kubernetes/pull/1542/files#diff-0f91bbc7bdb15165a9fc2e1cf7492425cbf1cbd35bf3daa22a000fc4027c9b9eR2233), [egressip_test.go](https://github.com/openshift/ovn-kubernetes/pull/1542/files#diff-56e7d797e8b9524f28eb9baa440e18600a173007ec0850958b3e1c30da4bb4baR5009-R5013).
=> [release-4.10] OCPBUGS-7990, OCPBUGS-7021: Delete stale egress ip snat entries by node

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/metrics/master.go, go-controller/pkg/node/base_node_network_controller_dpu_test.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, test/e2e/multihoming.go, test/e2e/static_pods.go
=> OCPBUGS-8464,OCPBUGS-8222,OCPBUGS-8397: [DownstreamMerge] 7 Mar 2023

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/master.go
even when the acl name is cropped. That happens when namespace name is longer than 43 symbols.
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1556
upstream https://github.com/ovn-org/ovn-kubernetes/pull/3464, https://github.com/ovn-org/ovn-kubernetes/pull/3466
no conflicts
=> OCPBUGS-8504,OCPBUGS-8505,OCPBUGS-8471: [release-4.13] Fix EFW's name truncation logic & make EFW ACLs unique using extIDs

go-controller/pkg/config/utils.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/hybrid.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Some minor unit test conflicts in backport. Added them as a 3rd commit to make reviewing easier.
There can be a case where multiple routes exist on ovn_cluster_router
matching on the same IP prefix. For example:
10.130.0.0/23                100.64.0.4 src-ip ecmp
10.130.0.0/23                100.64.0.6 src-ip ecmp
10.130.0.0/23                100.64.0.9 src-ip ecmp
In this case stale routes exist for old join subnet nexthops matching on
the same host subnet. OVN allows for these extra routes to be added and
considers them ecmp.
This commit modifies our behavior to ensure only a single route exists.
If more than one route for a predicate are found, the additional routes
are removed and then the leftover route is updated with the correct
fields.
A route is considered unique when it has the …
=> OCPBUGS-6957: [release-4.12] Ensure routes are not duplicated

docs/design/host_to_services_OpenFlow.md, go-controller/pkg/ovn/gateway/gateway.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/hybrid_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
There remained a dependency for return service traffic from OVN->Host where OVN would need to think it was routing towards the default gw. Once this traffic made it into the shared gw bridge, it would be hijacked and redirected back to the Host. This only applied to clusters where a default gateway exists. In a cluster with no default gateway, the default route for OVN pointed to a fake gw (169.254.169.4) with a static MAC binding for this address.
However, in a cluster where there is a default gateway, but we are unable to ARP and create a MAC binding, return service traffic will fail to be routed. This commit changes the behavior so that:
1. Dummy GW MAC bindings are always created
2. Always add a route destined to the dummy masquerade subnet via dummy GW. Like "169.254.169.0/29 via …
=> OCPBUGS-7346: [release-4.12] Fully remove dependency on default gateway for services

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/healthcheck_node.go, go-controller/pkg/node/healthcheck_node_test.go, go-controller/pkg/node/healthcheck_service.go, go-controller/pkg/node/node.go, go-controller/pkg/node/openflow_manager.go
4.12 backport of https://github.com/openshift/ovn-kubernetes/commit/c8489e3ff9c321e77f265dc9d484ed2549df4a6b and https://github.com/openshift/ovn-kubernetes/commit/9a836e3a547f3464d433ce8b9eef336624d51858
Not a clean backport, because 4.13 changes were against secondary network controller code in ovnk node, which we don't have in 4.12.
Also, in the backport of https://github.com/openshift/ovn-kubernetes/commit/c8489e3ff9c321e77f265dc9d484ed2549df4a6b, I moved to the new source file `pkg/node/openflow_manager.go` the relevant bits of https://github.com/openshift/ovn-kubernetes/blob/release-4.12/go-controller/pkg/node/healthcheck.go instead of what we had in 4.13, where a few functions  (`checkForStaleOVSInternalPorts`, `checkForStaleOVSRepresentorInterfaces`, `checkForStaleOVSInterfaces`) …
=> OCPBUGS-10318: [release-4.12] node: add node healthz server for cloud load balancers

Dockerfile.base.rhel9
See https://bugzilla.redhat.com/show_bug.cgi?id=2178962#c0 for details.
/cc @jcaamano @dcbw
=> OCPBUGS-10395: Bump OVN to disable CT flush

Dockerfile.base.rhel9
(cherry picked from commit 59686902ae40fa904d4354e9e7b4b19d698a44bb)
=> [release-4.13] OCPBUGS-10396: Bump OVN to disable CT flush

go-controller/pkg/ovn/master.go
In SetupMaster, we always call CreateOrUpdatePortGroupsOps with empty ACLs and PGs for the cluster-wide port group and cluster-wide-router-PG. This is disruptive during upgrades since momentarily all efw ACLs and multicast ACLs will be wiped out.
This commit changes this to first check if the PG already exists, if then no need to do anything.
Each of those features are responsible for ensuring ACLs, Ports are good on those PGs they own.
NOTE: This bug was an issue for multicast and started being an issue for egf from https://github.com/ovn-org/ovn-kubernetes/pull/3338/commits/bd29f417b43c257897f27badc64af38df78b99bd Before that we didn't have ACLs on cluster wide PG. …
=> [release-4.10] OCPBUGS-8513: Don't recreate clusterPGs and clusterRtrPGs unless needed

Dockerfile, Dockerfile.base, Dockerfile.microshift
Step 2 to get back to using regular names (eg without "-rhel-9" suffix). This is posssible without breaking CI because
https://github.com/openshift/release/pull/36772 merged which stops using these Dockerfiles.
Next steps:
- flip the dockerfile_paths in openshift/release back to the non-.rhel9 names since this PR makes the normal names RHEL9 now.
- finally 'git rm' the old .rhel9 Dockefiles in ovnkube.
=> Dockerfiles: copy RHEL-9 bits over top of unused RHEL8 bits

go-controller/pkg/ovn/controller/services/services_controller.go
This is a partial backport of https://issues.redhat.com/browse/OCPBUGS-6739 commit https://github.com/openshift/ovn-kubernetes/pull/1533/commits/2000f2e057267414d5c639326e31f5472cb39f06
When services are deleted, the controller cache should also remove the service from its top level cache to avoid growing forever.
=> [release-4.12] OCPBUGS-7732: Fix leak in service controller cache

go-controller/pkg/ovn/obj_retry_master.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3331 that merged downstream here: https://github.com/openshift/ovn-kubernetes/pull/1474/commits/0bb7c19be33ce4ed5966e8444404f6739b3e6fa8
Conflicts:
go-controller/pkg/ovn/default_network_controller.go - doesn't exist in 4.12
(cherry picked from commit 0bb7c19be33ce4ed5966e8444404f6739b3e6fa8)
=> [release-4.12] OCPBUGS-6034: Update egress node assignability on every egress node update

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
=> OCPBUGS-2303: [4.11] Stale chassis are not removed

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/db_object_types.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/base_event_handler.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pod_selector_address_set.go, go-controller/pkg/ovn/pod_selector_address_set_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Bring required changes to 4.13
perf metrics  https://github.com/ovn-org/ovn-kubernetes/pull/3450
downstream https://github.com/openshift/ovn-kubernetes/pull/1556
shared address sets https://github.com/ovn-org/ovn-kubernetes/pull/3329
downstream https://github.com/openshift/ovn-kubernetes/pull/1574
No conflicts, last commit fixes a "conflic" because k8s 1.26 bump is not yet merged to 4.13
=> OCPBUGS-10799: [release-4.13] Netpol performance: shared peer address sets, add metrics

go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of:
- https://github.com/openshift/ovn-kubernetes/pull/1567
Optimization about skipping pods on different nodes while search colliding IP has been removed, as nodeName is not present in `handlePeerPodSelectorDelete`
See [pkg/ovn/pods.go#L256](https://github.com/openshift/ovn-kubernetes/blob/f65d02b84f7acf787f53f11710916d871e8f2d5b/go-controller/pkg/ovn/pods.go#L256)
```
if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) || p.Spec.NodeName != nodeName {
continue
}
```
=> OCPBUGS-10314: [release-4.12] Handle Completed pods deletion

go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
Consolidate some MCS blocking code that's the same between local and shared gateway modes.
=> node: small downstream CARRY patch cleanup

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/batching/batch.go, go-controller/pkg/util/batching/batch_test.go
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1604
Conflict: egressfirewall.go - update apimachinery.sets to the previous
version
=> OCPBUGS-11109: [release-4.12] Batch potentially big transaction on egress firewall ACLs migration

go-controller/pkg/ovn/controller/services/lb_config.go, go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go
Openshift-only hack:
The router service is annotated with "traffic-policy.network.alpha.openshift.io/local-with-fallback" because, while it is defined with externalTrafficPolicy=Local, it expects the CNI to switch to externalTrafficPolicy=Cluster as soon as there are no local endpoints on any given node. 
SDN does this already, let's do it in OVNK as well to further reduce disruption time to openshift ingress during upgrades.
Closes #OCPBUGS-6947
=> OCPBUGS-6947: CARRY: use "prefer local" for annotated services

Dockerfile, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go
Cherry-pick/backport of https://github.com/openshift/ovn-kubernetes/pull/1521
We don't want to stay on a bespoke downstream version of 22.09 with the session affinity timeout patches; we want to move to a fully supported/tested/etc 22.12 that 4.12 is also using.
=> [release-4.11] OCPBUGS-10734: Bump OVN to 22.12 and turn off neighbour response in router options.

Dockerfile
We should move off the dead-end 2.16 stream to 2.17 which has multiple performance improvements, is used by other layered products, and is fully supported by FDP.
RHCOS side PR: https://github.com/openshift/os/pull/1147
=> OCPBUGS-4762: [4.10] Dockerfile: bump to OVS 2.17.0-62

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/batching/batch.go, go-controller/pkg/util/batching/batch_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1617
Includes error wrapping fix from https://github.com/openshift/ovn-kubernetes/pull/1610
Conflicts:
go-controller/pkg/ovn/egressfirewall.go -
egressFirewallACLPriorityKey is not used in 4.11, because logging
for egress firewall is not implemented
=> OCPBUGS-11110: [release-4.11] Batch potentially big transaction on egress firewall ACLs migration

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Backport of:
- https://github.com/openshift/ovn-kubernetes/pull/1616
Solved conflicts around `handlePeerPodSelectorDelete(...)` as there is no retry framework for network policies in release-4.10.
=> OCPBUGS-11423: [release-4.10] Handle Completed pods deletion

go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1630  for 4.12.
Clean backport for the hack itself in `go-controller/pkg/ovn/controller/services/load_balancer.go`, not a clean backport of the unit tests just because:
-  the renaming in the service controller code (https://github.com/openshift/ovn-kubernetes/commit/c7fd02c133233cf940fc7537e481a95700e060a3#diff-78b8ad08a198fcc889bf29d85c44763617fd5320ca9ff10f88fe107a0d968c29) was not backported to 4.12. The result is simply that `LBRule`, `LB`, `LBOpts`, `Addr` had to be prefixed with `ovnlb`.
-  we don't have
`go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go` in 4.12, so I moved the unit tests to the existing `go-controller/pkg/ovn/controller/services/load_balancer_test.go` right after the other ocp …
=> OCPBUGS-11701: [release-4.12] CARRY: use "prefer local" for annotated services

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Simple fix where I was parsing the node address incorrectly.
(cherry picked from commit 3a72af93f2e5c1a874e9a888e7f28920c2cc63df)
clean backport
=> OCPBUGS-10982: [release-4.13] Fixes Egress Firewall node selector for ipv6

go-controller/pkg/clustermanager/network_cluster_controller.go, go-controller/pkg/clustermanager/network_cluster_controller_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Clean backport of https://github.com/ovn-org/ovn-kubernetes/pull/3524 
@dcbw
=> OCPBUGS-11534:Stack migration

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/util/batching/batch.go, go-controller/pkg/util/batching/batch_test.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1629
Had to make some changes, this one requires a proper review
=> OCPBUGS-11453: [release-4.10] Batch potentially big transaction on egress firewall ACLs migration

go-controller/pkg/clustermanager/network_cluster_controller.go, go-controller/pkg/clustermanager/network_cluster_controller_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/multi_network.go
Clean backport of @dcbw  stack migration commits. Had to pull in https://github.com/ovn-org/ovn-kubernetes/pull/3510, which also was clean and is already in 4.14 as the migration work is based on top of some of the changes there
=> OCPBUGS-12212:[release-4.13]4.13 stack migration

go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/ovn/controller/services/loadbalancer.go
Revert predicate search optimization
3369d387417ede05033c002b782b0279b201ea76 as predicate search should not bee needed anymore
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
(cherry picked from commit ad052c1c0061f9734d78c93cb2454557238dac25)
Conflicts:
go-controller/pkg/libovsdb/libovsdb.go: acl client index is not
merged downstream yet
go-controller/pkg/ovn/controller/services/loadbalancer.go:
loadbalancer cache removal is not merged downstream yet
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3533
=> OCPBUGS-11716: [release-4.14] Use loadbalancer.Name as client index

dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/network-controller-manager/network_controller_manager.go, go-controller/pkg/network-controller-manager/node_network_controller_manager.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/healthcheck_node.go, go-controller/pkg/node/healthcheck_node_test.go
In the node healthz server, leveraged by cloud load balancers to check the node health for services with ExternalTrafficPolicy=Cluster, respond negatively to health checks as soon as the ovnk node pod is to be deleted, by inspecting the pod DeletionTimestamp. This allows cloud load balancers to have a little more time to update their list of healthy nodes before the node actually stops altogether forwarding traffic.
Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>
(cherry picked from commit b0e72e3828a2b0ba1a7a4add236ae64a43110731)
Depends on these PRs:
- CNO fix: https://github.com/openshift/cluster-network-operator/pull/1750
- some network controller patches necessary for the additional fix below: https://github.com/openshift/ovn-kubernetes/pull/1606
Once …
=> OCPBUGS-10914: [release-4.13] Node healthz server: return unhealthy when ovnk node pod is to be deleted

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/acl_test.go, go-controller/pkg/libovsdbops/portgroup.go
backport of https://github.com/openshift/ovn-kubernetes/pull/1631
Conflicts:
go-controller/pkg/libovsdbops/acl.go - just less
function that can return duplicate acl error
=> OCPBUGS-12768: : [release-4.12] Delete equivalent ACLs when searching by predicate.

Dockerfile.base
This PR proposes to add a build argument to drive the proper openvswitch package to install from the RPM repositories.
This will ease the versions bump and will be helpful for some OKD-related builds when the RPM repositories are not in sync, and some packages version might miss.
cc @vrutkovs @LorbusChris
=> OCPBUGS-13716: Use ovsver and ovnver to infer the short version numbers for ovs and ovn

docs/egress-ip.md, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
Clean backport of https://github.com/openshift/ovn-kubernetes/commit/39b55de034c7291122b3c9be7df0bf4323abe74d
(cherry picked from commit 39b55de034c7291122b3c9be7df0bf4323abe74d)
=> [release-4.13] OCPBUGS-12864: Drop packets were not properly SNATed

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/acl_test.go, go-controller/pkg/libovsdbops/portgroup.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1666
I had to rewrite almost everything in this PR, needs proper review
=> Bug OCPBUGS-12792: [release-4.10] Delete equivalent ACLs when searching by predicate.

go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/1660
Simple conflicts on `ovn/controller/services/loadbalancer.go`
=> OCPBUGS-13953: [release-4.12] Use loadbalancer.Name as client index

.ci-operator.yaml
Updating ovn-kubernetes-base images to be consistent with ART
TLDR:
Component owners, please ensure that this PR merges as it impacts the fidelity
of your CI signal. Patch-manager / leads, this PR is a no-op from a product
perspective -- feel free to manually apply any labels (e.g. jira/valid-bug) to help the
PR merge as long as tests are passing. If the PR is labeled "needs-ok-to-test", this is
to limit costs for re-testing these PRs while they wait for review. Issue /ok-to-test
to remove this tag and help the PR to merge.
Detail:
This repository is out of sync with the downstream product builds for this component.
One or more images differ from those being used by ART to create product builds. This
should be addressed to ensure that the component's CI testing is accurately
reflecting …
=> OCPBUGS-12352: Updating ovn-kubernetes-base images to be consistent with ART

Dockerfile, Dockerfile.base, Dockerfile.microshift
Then we can retarget the openshift/release tests to the regular dockerfiles, and eventually remove our .rhel9 variants.
=> OCPBUGS-14482: Dockerfiles: sync RHEL9 dockerfiles to regular unused ones

.github/workflows/test.yml, contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/helper_linux.go, go-controller/pkg/util/net_linux.go
This brings in two critical fixes:
https://issues.redhat.com/browse/SDN-3885 cc @pliurh 
and a high priority bug fix: https://issues.redhat.com/browse/OCPBUGS-14769
NO CONFLICTS, CLEAN CHERRY-PICKs
/cc @trozet @pliurh @andreaskaris
=> OCPBUGS-14769,SDN-3885: Downstream Merge 13th June 2023

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/util/kube.go
In case of completed pod case, egress ip module is handling pod add, egressip events as usual and when logical port is found, it proceeds with programming SNAT and LRP for pod ip address which is not required. Also when pod is done or completed, then it's not required to recreate SNAT entry referring to node ip address. Hence this commit addresses these two issues so that no stale or duplicate SNAT entries present for a pod.
Manually resolved conflicts:
go-controller/pkg/ovn/namespace.go
(cherry picked from commit 7b88e0acbfa7041ad056d32f7b0169565b44f874)
=> [release-4.13] OCPBUGS-15140: Fix stale SNAT entries for completed pods

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/net_linux.go
For services and endpoints, make sure that the protocol and port are valid before deleting conntrack flows.
Under certain circumstances, the port may be the default value (meaning 0), indicating that all conntrack flows for a given IP shall be deleted. However, for endpoints and services, only ever delete exact matches. Otherwise, ovnkube-node might remove conntrack flows inserted by unrelated components (such as iptables rules). If for any reason protocol is invalid, skip conntrack deletion instead.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-14769
(cherry picked from commit eacdaa721dc3d4bd7a1b5b248aa94ac22a6d5da6)
=> OCPBUGS-14979: Validate port before deleting conntrack flow

go-controller/pkg/clustermanager/egressip_controller.go
(cherry picked from commit 4759e64a6f29b18f99cd58a103d0981f8b391e23)
=> OCPBUGS-15226: EgressIP: do not patch the status if the object no longer exists

go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/node.go, go-controller/pkg/util/net_linux.go
For services and endpoints, make sure that the protocol and port are valid before deleting conntrack flows.
Under certain circumstances, the port may be the default value (meaning 0), indicating that all conntrack flows for a given IP shall be deleted. However, for endpoints and services, only ever delete exact matches. Otherwise, ovnkube-node might remove conntrack flows inserted by unrelated components (such as iptables rules). If for any reason protocol is invalid, skip conntrack deletion instead.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-14769
(cherry picked from commit eacdaa721dc3d4bd7a1b5b248aa94ac22a6d5da6)
=> OCPBUGS-14982: Validate port before deleting conntrack flow

go-controller/pkg/ovn/multicast.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Add default deny acl externalID to avoid duplicate acls for namespaces with long names.
every namespace has 4 default deny acls: ingress/egress and deny/allow. Direction was in the ExternalIDs before, but action was a suffix in acl name, that gets truncated for long namespace names, therefore deny and allow acls for the same direction would have the same name and ExternalIDs. New ExternalID should fix this case.
Multicast acls don't need extra ID, therefore I renamed the old function to `getDirectionPolicyACLExternalIDs` and multicast still uses that.
To check the difference on restart, you can run the new test on the old implementation and see duplicate acls error in the logs. Also create namespace with long name + networkpolicy and restart ovn-k master can be used as reproducer
=> OCPBUGS-15372: [release-4.13] Fix network policy to work with long namespace names

go-controller/pkg/ovn/multicast.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Add default deny acl externalID to avoid duplicate acls for namespaces with long names.
every namespace has 4 default deny acls: ingress/egress and deny/allow. Direction was in the ExternalIDs before, but action was a suffix in acl name, that gets truncated for long namespace names, therefore deny and allow acls for the same direction would have the same name and ExternalIDs. New ExternalID should fix this case.
Multicast acls don't need extra ID, therefore I renamed the old function to getDirectionPolicyACLExternalIDs and multicast still uses that.
To check the difference on restart, you can run the new test on the old implementation and see duplicate acls error in the logs. Also create namespace with long name + networkpolicy and restart ovn-k master can be used as reproducer
Backport …
=> OCPBUGS-15424: [release-4.12] Fix network policy to work with long namespace names

go-controller/pkg/libovsdb/libovsdb.go
When the cert/key files got removed during cert/key update, With current code, libovsdb will only works for once with first remove event. To fix this issue, watcher need remove the old file and add new file back to watcher.
Signed-off-by: Zhen Wang <zhewang@nvidia.com>
(cherry picked from commit 702c7e3e39abc6a1f17af04f27bdf6f40cd11e9a)
=> OCPBUGS-13745: [release-4.13] ovnkube-master pod failed to reconnect to ovn db due to ssl expire

Dockerfile.base
```
OVN changes 49 -> 69:
- Implement MTU Path Discovery for multichassis ports
- northd: Add logical flow to skip GARP with LLA (#2211240)
- northd: match only on supported protocols to handle_svc_check (#1913162)
- northd: Fix address set incremental processing (#2196885)
- controller: Ignore DNS queries with RRs
- controller: Handle OpenFlow errors. (#2134880)
- northd: fix ls_in_hairpin l3dgw flow generation
- ovn-controller.c: Fix assertion failure during address set update.
OVS changes 10 -> 32:
859071224c ovsdb: monitor: Destroy initial change set when new columns added.
54e45e3fee ovsdb: Monitor: Keep and maintain the initial change set.
9529e9aa96 ovsdb: Allow conversion records with no data in a clustered storage.
7006bb112b ovsdb: Check for ephemeral columns before writing a …
```
=> OCPBUGS-15127: Dockerfile: bump to ovn 23.03.0-69 (for LB templates) and ovs 3.1.0-32 (upgrade perf)

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL9-built shim on a RHEL8 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL8 shim into a special location …
=> Dockerfile: build both RHEL8 and RHEL9 shims

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/util/kube.go
Manual cherrypick of https://github.com/openshift/ovn-kubernetes/pull/1715/commits/cd99b41e441a917e51f983f69d34578167293395.
Resolved conflicts:
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go
go-controller/pkg/ovn/namespace.go
go-controller/pkg/util/kube.go
(cherry picked from commit 7b88e0acbfa7041ad056d32f7b0169565b44f874)
(cherry picked from commit cd99b41e441a917e51f983f69d34578167293395)
=> [release-4.12] OCPBUGS-15388: Fix stale SNAT entries for completed pods

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/hybrid.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
Manual backport of https://github.com/openshift/ovn-kubernetes/pull/1662 and https://github.com/ovn-org/ovn-kubernetes/pull/3349.
There were conflicts in all but the [second commit](20ba6175664b11fb8130cab982b75e522b7fb438) due to the general differences between 4.12 and 4.13 releases.
=> OCPBUGS-13885: [release-4.12] Drop packets that were not properly SNATed

go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
backport of https://github.com/ovn-org/ovn-kubernetes/pull/3669/commits/5e3dc65eb432b5fea7fc91aaea48758a64ccbd76
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1729
includes unit test fix for egressfirewall introduced here https://github.com/openshift/ovn-kubernetes/pull/1733
=> OCPBUGS-15586: [release-4.13]: Allow hostNetwork ingress for network policies with empty namespace selector

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/net.go
Partial removal of nodes can leave OVN database with the gateway logical router and external logical switch of the removed node. This commit improves syncNode functionality, so these cases are also taken into consideration.
When deleting a port from a logical switch or router, it is possible that the logical switch or router themselves have been deleted. This commit changes the behavior of delete so it is not an error when if that happens.
Conflicts:
go-controller/pkg/ovn/master.go - cleanupNodeResources => deleteNode
Reported-at: https://issues.redhat.com/browse/OCPBUGS-13744
(cherry picked from commit 487bba32a5f6256e53b77f8f43808c74763507cf)
=> [release-4.13] OCPBUGS-15651: Improve syncNodes to remove stale data

go-controller/hybrid-overlay/pkg/controller/node.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/types/types.go
When toggling hybrid overlay the linux nodes can miss wiring the pods on start-up if allocating the hybrid overlay DRIP and DRMAC takes too long.
Fix this issue by passing a podLister to the node controller and running the AddPods() command on all local pods once on startup after DRIP and DRMAC are set.
(cherry picked from commit 61541cfcaa5f5a111b93f0234440d18e778969df)
=> OCPBUGS-15368: [release-4.13]: initial pods are not wired for hybrid overlay

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/net.go
Cherry pick from https://github.com/openshift/ovn-kubernetes/pull/1731
Partial removal of nodes can leave OVN database with the gateway logical router and external logical switch of the removed node. This commit improves syncNode functionality, so these cases are also taken into consideration.
When deleting a port from a logical switch or router, it is possible that the logical switch or router themselves have been deleted. This commit changes the behavior of delete so it is not an error when if that happens.
Conflicts:
- go-controller/pkg/ovn/base_network_controller.go 
- deleteNodeLogicalNetwork located in .../pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
(cherry picked from commit 9fc87b22dad9919fd432d8dd20ed87f1605184e2)
=> [release-4.12] OCPBUGS-13744: Improve syncNodes to remove stale data

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/net.go
Cherry pick of: https://github.com/openshift/ovn-kubernetes/pull/1732
Partial removal of nodes can leave OVN database with the gateway logical router and external logical switch of the removed node. This commit improves syncNode functionality, so these cases are also taken into consideration.
When deleting a port from a logical switch or router, it is possible that the logical switch or router themselves have been deleted. This commit changes the behavior of delete so it is not an error when if that happens.
Conflicts:
- go-controller/pkg/ovn/master_test.go
=> [release-4.11] OCPBUGS-15731,OCPBUGS-15745: Improve syncNodes to remove stale data

Dockerfile
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.
So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL7 shim into a special location …
=> [release-4.8] OCPBUGS-16208: Dockerfile: build both RHEL7 and RHEL8 shims

go-controller/pkg/ovn/policy.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3766
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1757
tiny conflict: rename bnc to oc
=> OCPBUGS-16121: [release-4.13]: Delete address sets after acls that reference them

Dockerfile.base
Includes fix for
https://issues.redhat.com/browse/OCPBUGS-16866
https://bugzilla.redhat.com/show_bug.cgi?id=2177197
=> [release-4.13] OCPBUGS-17120: Bump OVN to 23.06-23.06.0-51

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/util/kube.go
Manual cherry-pick of 56c68141134451cff2af24a4ca62ad2742ddc421.
Resolved Conflicts:
- `go-controller/pkg/ovn/egressip_test.go` [1](https://github.com/openshift/ovn-kubernetes/pull/1758/files#diff-56e7d797e8b9524f28eb9baa440e18600a173007ec0850958b3e1c30da4bb4baR4994-R4998).
- `go-controller/pkg/ovn/egressip_test.go` [2](https://github.com/openshift/ovn-kubernetes/pull/1758/files#diff-56e7d797e8b9524f28eb9baa440e18600a173007ec0850958b3e1c30da4bb4baR5154-R5158).
- `go-controller/pkg/ovn/egressip_test.go` [3](https://github.com/openshift/ovn-kubernetes/pull/1758/files#diff-56e7d797e8b9524f28eb9baa440e18600a173007ec0850958b3e1c30da4bb4baR5242-R5251).
- `go-controller/pkg/ovn/egressip_test.go` [4](https://github.com/openshift/ovn-kubernetes/pull/1758/files#diff-56e7d797e8b9524f28eb9baa440e18600a …
=> [release-4.10] OCPBUGS-16206: Fix stale SNAT entries for completed pods

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/helper_linux_test.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3570
There were conflicts in `go-controller/pkg/node/helper_linux.go`
=> [release-4.13] OCPBUGS-15496: Fix default GW IPs retrieval

go-controller/pkg/libovsdb/libovsdb.go
clean backport of https://github.com/openshift/ovn-kubernetes/pull/1807
image `quay.io/npinaeva/ovn-k:db-timer-workaround` is based on this PR
=> OCPBUGS-17522: [release-4.12] libovsdb: give monitor setup time to process than normal transactions

go-controller/pkg/node/linkmanager/link_network_manager.go
We suspect this is what is causing hypershift to fail.
=> OCPBUGS-17867: CARRY: Removes restriction for ip scope universe on node ips

go-controller/pkg/ovn/policy.go
Besides unneeded logging it may cause update event that was received after delete event to be never handled, since retry framework will not proceed to the update handler until delete handler succeeds. Was fixed in newer versions with 120140fd670d8358959e6ea062564edd9d7d8841 (pod_selector_address_set)
Merged downstream here https://github.com/openshift/ovn-kubernetes/pull/1603 (4.13), https://github.com/openshift/ovn-kubernetes/pull/1603/files#diff-7375899468809f8394c8c50f436167aa32368e3dac1eb0c25d05e6b9b0e2cbe3R354-R359 
loglevel was updated to warning here https://github.com/ovn-org/ovn-kubernetes/commit/8e95a642698a763fb885fe318d3e9b20d8502205
=> OCPBUGS-17675: Don't return error on delete event that doesn't ave a chance to succeed.

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/informer/informer.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go
Backport of 4.12 commit 63330f2220ff88256db076adfd93886591618889.
Resolved conflict:
`go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go`
(removed this file as this is not valid for 4.11)
=> [release-4.11] OCPBUGS-12819: Handle k8s watcher restart scenario

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_dns_test.go, go-controller/pkg/ovn/egressfirewall_test.go
backport of https://github.com/ovn-org/ovn-kubernetes/pull/3847
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1833
Conflicts:
go-controller/pkg/ovn/egressfirewall.go - different func signatures
go-controller/pkg/ovn/egressfirewall_test.go - uses fakeAddressSetFactory,
check address sets in asf instead of db
=> OCPBUGS-18057: [release-4.13] Create egress firewall with one db transaction

go-controller/pkg/clustermanager/network_cluster_controller.go, go-controller/pkg/ovn/master.go
clean backport of upstream commit: [87a8c3fa112570ab9c3a20446923cfb908256f18](https://github.com/ovn-org/ovn-kubernetes/commit/87a8c3fa112570ab9c3a20446923cfb908256f18)
clearInitialNodeNetworkUnavailableCondition needs to be run on every node for GCP. Since we have some nodes that are not running ovn-kubernetes, notably windows, it should be run in the clustermanager
=> OCPBUGS-17731: move clearInitialNodeNetworkUnavailableCondition to clustermanager

Dockerfile.base, go-controller/pkg/ovn/copp.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/types/const.go
OCP-relevant changes in 23.09 include:
- significant performance optimizations (IP for LSPs, PGs, Meters, and soon LBs)
- fix for skip_snat and affinity timeouts ( https://bugzilla.redhat.com/show_bug.cgi?id=2224260 )
- dynamic updating of MAC binding timestamps ( https://bugzilla.redhat.com/show_bug.cgi?id=2189924 )
- COPP for Service Monitors to fix CVE-2023-3153
=> OCPBUGS-16617, OCPBUGS-14709, OCPBUGS-18603: Bump to OVN 23.09

go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn_test.go
Manual cherry-pick of 152ae1e4b3f80f299899de99c12c7ba55402f994 8dd5d2e3b109bfe328e6d5cecf3050860c70fbba c08382b8167732ca29b47045dc8e3ff99de4edc9 and 712978def57809d7dd73e23fb4e2e16f55bb998f.
Conflicts due to complete redesign of egress ip module. 
Needed to squash first 3 commits manually and did manual commit for the last one.
=> [release-4.13] OCPBUGS-17123: Remove stale egressip status entry

Dockerfile.base
- LoadBalancer incremental processing to reduce CPU usage in Service-heavy scenarios
https://issues.redhat.com/browse/OCPBUGS-19004
- Always CT commit ECMP traffic in original direction to reduce OVS CPU usage in benchmark testing
https://issues.redhat.com/browse/OCPBUGS-19010
=> OCPBUGS-19004,OCPBUGS-19010: Dockerfile: bump OVN to ovn23.09-23.09.0-beta.31.el9fdp

Dockerfile.base
- LoadBalancer incremental processing to reduce CPU usage in Service-heavy scenarios
https://issues.redhat.com/browse/OCPBUGS-19004
- Always CT commit ECMP traffic in original direction to reduce OVS CPU usage in benchmark testing
https://issues.redhat.com/browse/OCPBUGS-19010
=> [release-4.14] OCPBUGS-19087: Dockerfile: bump OVN to ovn23.09-23.09.0-beta.31.el9fdp

go-controller/pkg/libovsdb/ops/model_client.go, go-controller/pkg/libovsdb/ops/router.go, go-controller/pkg/libovsdb/ops/router_test.go, go-controller/pkg/libovsdb/util/switch.go, go-controller/pkg/metrics/ovnkube_controller.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go
Instead of looking explicitly for libovsdbclient.ErrNotFound, checking logic should account for cases when error has been wrapped.
In particular, this change addresses the logic in: func DeleteNATsOps()
https://github.com/ovn-org/ovn-kubernetes/blob/247483c8d1167072e04cf63e1c6e45264a25310e/go-controller/pkg/libovsdb/ops/router.go#L1078
when the error began to be wrapped as follows:
https://github.com/ovn-org/ovn-kubernetes/pull/3646/commits/25d892cc9e318d19738d9519e0e20fbab28f7eae#r1317615944
=> [release-4.14] OCPBUGS-18584: Check libovsdbclient.ErrNotFound on wrapped errors

go-controller/pkg/node/node_ip_handler_linux.go
When the addressManager detects changes in the node's address, it will update the node address annotations, but it was not reflecting the address changes in the OpenFlow rules within the node via openflowManager.updateBridgeFlowCache(). This could result in nodes having stale rules that affect functionalities such as hairpin.
=> [release-4.14] OCPBUGS-18977: Update bridge flow cache when the host address changes

go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/pod_selector_address_set.go, go-controller/pkg/util/pod_annotation.go
Do not return error if pod IP cannot be retrieved for `podSelectorPodNeedsDelete` and perf improvements for retrieving the pod IPs.
=> OCPBUGS-19449: Do not return error if pod IP cannot be retrieved for `podSelectorPodNeedsDelete` and perf improvements

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/ovn_test.go
Manual cherrypick of https://github.com/openshift/ovn-kubernetes/pull/1793 commits 22908f651e8c3176c621d27c2ed1aed6452e17ae and e1903314c12671ade8b7fd31139961b251800784.
Resolved conflicts:
`go-controller/pkg/ovn/egressip.go`
`go-controller/pkg/ovn/default_network_controller.go` -> `go-controller/pkg/ovn/obj_retry_master.go`
=> [release-4.12] OCPBUGS-19432: Remove stale egressip status entry

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/chassis.go, go-controller/pkg/libovsdbops/chassis_test.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/vendor/github.com/Microsoft/go-winio/README.md, go-controller/vendor/github.com/Microsoft/go-winio/file.go, go-controller/vendor/github.com/Microsoft/go-winio/hvsock.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go, go-controller/vendor/github.com/Microsoft/go-winio/vhd/vhd.go, go-controller/vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go, go-controller/vendor/github.com/cenkalti/backoff/v4/exponential.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/uuidset.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/monitor.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/database.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/errors.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/mutate.go, go-controller/vendor/github.com/ovn-org/libovsdb/database/transaction.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go, go-controller/vendor/modules.txt
backport of https://github.com/openshift/ovn-kubernetes/pull/1516
=> [release-4.11] OCPBUGS-19650: Delete IGMP Groups when deleting stale chassis

Dockerfile
The `ovnkube-trace` binary file built for RHEL9 doesn't work anymore on RHEL8 system due to different shared library dependencies between the two OS versions. So this commit copies ovnkube-trace file built for RHEL8 into `/usr/lib/rhel8` directory so that user can download and run it on RHEL-8 platforms.
=> OCPBUGS-19013: Dockerfile: Copy ovnkube-trace file for RHEL8 platform

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/retry/obj_retry.go
Nodes obj is configured via distributed software
components and previous to this patch, we are
sending numerous kubernetes events of error level warning when infact everything is proceeding normally..
Only emit warning events when we fail to configure a node. This is after 15 retry attempts - ~7m currently.
We continue logging every node add/update/delete failure to logs.
(cherry picked from commit 8889f47c8e5d259fded984b7552f5813213c83c9) (cherry picked from commit dada90de959c2c7d2e45749a947cac08cc4e2c2e)
=> OCPBUGS-18054: Emit node events only when retry failure

go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/util.go
Instead of looking explicitly for libovsdbclient.ErrNotFound, checking logic should account for cases when error has been wrapped.
In particular, this change addresses the logic in: func DeleteNATsOps()
https://github.com/ovn-org/ovn-kubernetes/blob/247483c8d1167072e04cf63e1c6e45264a25310e/go-controller/pkg/libovsdb/ops/router.go#L1078
when the error began to be wrapped as follows:
https://github.com/ovn-org/ovn-kubernetes/pull/3646/commits/25d892cc9e318d19738d9519e0e20fbab28f7eae#r1317615944
=> [release-4.13] OCPBUGS-18672: Check libovsdbclient.ErrNotFound on wrapped errors

go-controller/cmd/ovnkube/ovnkube.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/obj_retry_node.go, go-controller/pkg/ovn/controller/apbroute/external_controller.go, go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go, go-controller/pkg/ovn/controller/apbroute/master_controller.go, go-controller/pkg/ovn/controller/apbroute/network_client.go, go-controller/pkg/ovn/controller/apbroute/node_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/syncmap/syncmap.go, go-controller/pkg/util/kube.go, test/e2e/external_gateways.go
clean backport with no conflicts from https://github.com/openshift/ovn-kubernetes/pull/1917
=> OCPBUGS-19932: OCPBUGS-19931: DownStream Batch Merge Blocker Bug 29th september 2023

Dockerfile.base, go-controller/pkg/ovn/copp.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/types/const.go
- Always CT commit ECMP traffic in original direction to reduce OVS CPU usage in benchmark testing
https://issues.redhat.com/browse/OCPBUGS-19010
- service monitor MAC flow is not rate limited
https://bugzilla.redhat.com/show_bug.cgi?id=2213296
- ovn-controller: Detect and use L4_SYM dp-hash if available
https://bugzilla.redhat.com/show_bug.cgi?id=2188679
- northd: Make sure that skip_snat=true is evaluated before force_snat
https://bugzilla.redhat.com/show_bug.cgi?id=2224260
=> [release-4.13] OCPBUGS-19088,OCPBUGS-7406,OCPBUGS-18791,OCPBUGS-18792: Dockerfile: bump OVN to ovn23.06-23.06.1-8.el9fdp

Dockerfile.base, go-controller/pkg/ovn/gateway_copp.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/types/const.go
- Always CT commit ECMP traffic in original direction to reduce OVS CPU usage in benchmark testing
https://issues.redhat.com/browse/OCPBUGS-19010
- service monitor MAC flow is not rate limited
https://bugzilla.redhat.com/show_bug.cgi?id=2213296
- northd: Make sure that skip_snat=true is evaluated before force_snat
https://bugzilla.redhat.com/show_bug.cgi?id=2224260
- binding: fixed ovn-installed not properly removed (recomputes)
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2150905
- binding: fixed ovn-installed not properly removed (migration)
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2150905
- ofctrl-seqno: Do not truncate the last acked value
https://bugzilla.redhat.com/show_bug.cgi?id=2074019
- northd: prevents sending packet …
=> [release-4.12] OCPBUGS-19089,OCPBUGS-19904,OCPBUGS-19906,OCPBUGS-14708: Dockerfile: bump OVN to ovn22.12-22.12.1-18.el8fdp

Dockerfile
We used to use it for the loopback plugin, but CRI-O (via ocicni) has configured the loopback interface for years already.
=> OCPBUGS-14787: Dockerfile: stop installing CNI plugins RPM

go-controller/pkg/node/node_ip_handler_linux.go
When the addressManager detects changes in the node's address, it will update the node address annotations, but it was not reflecting the address changes in the OpenFlow rules within the node via openflowManager.updateBridgeFlowCache(). This could result in nodes having stale rules that affect functionalities such as hairpin.
=> [release-4.13] OCPBUGS-18976: Update bridge flow cache when the host address changes

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
Backport of 4.14 commits 1c64fab89eca1789f8ebb188cfb7729a57eb571a and 74385911b28efb0cb707b3a53c85a02cb9c84c9d.
No conflicts.
=> OCPBUGS-20047: Adjust python ssl library dependency check

go-controller/pkg/node/node_ip_handler_linux.go
When the addressManager detects changes in the node's address, it will update the node address annotations, but it was not reflecting the address changes in the OpenFlow rules within the node via openflowManager.updateBridgeFlowCache(). This could result in nodes having stale rules that affect functionalities such as hairpin.
=> [release-4.12] OCPBUGS-18353: Update bridge flow cache when the host address changes

go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/topology_version.go, go-controller/pkg/util/util.go
Instead of looking explicitly for libovsdbclient.ErrNotFound, checking logic should account for cases when error has been wrapped.
In particular, this change addresses the logic in: func DeleteNATsOps()
https://github.com/ovn-org/ovn-kubernetes/blob/247483c8d1167072e04cf63e1c6e45264a25310e/go-controller/pkg/libovsdb/ops/router.go#L1078
when the error began to be wrapped as follows:
https://github.com/ovn-org/ovn-kubernetes/pull/3646/commits/25d892cc9e318d19738d9519e0e20fbab28f7eae#r1317615944
=> [release-4.12] OCPBUGS-18681: Check libovsdbclient.ErrNotFound on wrapped errors

test/e2e/e2e.go
Fixes a compilation issue found when running the e2e tests due to a missing int32 parameter while calling the `createServiceForPodsWithLabel` helper function.
@zeeke PTAL.
=> [release-4.13] OCPBUGS-14314: Fix compilation error in e2e.go tests due to missing int32 parameter

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/vendor/k8s.io/client-go/informers/factory.go
Backport of upstream https://github.com/ovn-org/ovn-kubernetes/pull/4012 to reduce ovnkube memory usage.
=> [release-4.14] OCPBUGS-24209: Significantly reduce shared informer memory usage

go-controller/pkg/node/gateway_shared_intf.go
(cherry picked from commit 44a7018ed736f93cf8d1c2844559fce583252a09)
=> OCPBUGS-22735: OVNK/GW: Ignore headless services in syncServices

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_shared_intf.go, test/e2e/egressip.go, test/scripts/e2e-cp.sh
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/4036 from https://github.com/openshift/ovn-kubernetes/pull/1976
Conflicts:
-  `test/e2e/egressip.go`: back to using an old e2e k8s framework API
=> [release-4.14] OCPBUGS-25087: Fragment oversized reply packets in LGW mode

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_shared_intf.go, test/e2e/egressip.go, test/e2e/pod.go, test/e2e/service.go, test/scripts/e2e-cp.sh
Backport of https://github.com/openshift/ovn-kubernetes/pull/1982
Conflicts:
- `go-controller/pkg/node/gateway_shared_intf.go`: less indentation required as there is no microshift specific block checking for usage of a physical port.
=> [release-4.13] OCPBUGS-25095: Fragment oversized reply packets in LGW mode

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_shared_intf.go, test/e2e/egressip.go, test/e2e/pod.go, test/scripts/e2e-cp.sh
Backport of https://github.com/openshift/ovn-kubernetes/pull/1983
=> [release-4.12] OCPBUGS-25096: Fragment oversized reply packets in LGW mode

go-controller/pkg/kubevirt/pod.go, go-controller/pkg/kubevirt/router.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/kubevirt_test.go
When a live migration fails at completed virt-launcher pod with newer
creation timestamp is lingering in the system so the virt-launcher that
is really running the VM is hidden by it and routes are wrongly
reconstructed. This change take into account if the pod is completed to
ignore it marking it as stale.
closes [OCPBUGS-23387](https://issues.redhat.com/browse/OCPBUGS-23387)
It includes a unit test that emulate the result of failing migration, completed virt-launcher pod with newer creation timestamp.
kubevirt: Ignore completed virt-launcher pods
=> [release-4.14] OCPBUGS-23387: Ignore completed virt-launcher pods

go-controller/pkg/node/gateway_shared_intf.go, test/e2e/service.go
For unknown reasons, during the kube rebase, we just decided to flip from sorting the list of endpoints to not sorting it? : 3850450#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4L579 The allocateLBNodePorts feature depends on the list being sorted, else our logic is skewed and the random probability model we use to generate iptables gets skewed up as well. So during endpoints update and such we will behave badly and have left over DNATs towards pods that don't exist anymore which will lead to black-holing the traffic.
(cherry picked from commit d9d618783f373ac98d5203e17fe06915222fb926)
**- Description …
=> OCPBUGS-14799: Updating endpoints when using allocateLBNP=0, lgw mode fails

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/util.go, test/e2e/service.go, test/e2e/util.go
Trivial conflicts with references to things that pertain to IC or code comments that dont exist in 4.13 code. Only significant conflict was missing the GetIPNetFullMask function which I had to make slightly different from upstream due to function dependencies.
=> OCPBUGS-25224: [release-4.13] fixes MTU configuration on gateway router

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/config/config.go
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/3959
downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1952
=> [release-4.14] OCPBUGS-23257: Update leaderelection config to allow retries

Dockerfile.base
- Fix for potential crash in ovn-northd while incrementally processing load balancer changes [FDP-181](https://issues.redhat.com/browse/FDP-181) [OCPBUGS-24322](https://issues.redhat.com/browse/OCPBUGS-24322)
- Support more than 64K OF groups/meters to allow scaling to more than 32K services [FDP-70](https://issues.redhat.com/browse/FDP-70)
- Add missing conntrack flushing support (for LBs on logical routers) [rhbz#2193323](https://bugzilla.redhat.com/show_bug.cgi?id=2193323)
- Fix for incorrect source IP in ICMP needsfrag [FDP-39](https://issues.redhat.com/browse/FDP-39) [OCPBUGS-25357](https://issues.redhat.com/browse/OCPBUGS-25357)
- Fix for check_pkt_larger calculation when tag_request is set to 0 …
=> OCPBUGS-24322,OCPBUGS-25357: Dockerfile: Bump OVN to ovn-23.09.0-91.el9fdp

go-controller/pkg/ovn/controller/apbroute/master_controller.go, test/e2e/external_gateways.go
Backported cherry picked from 4.15. Upstream https://github.com/ovn-org/ovn-kubernetes/pull/3997
@npinaeva @jcaamano PTAL.
=> [release-4.14] OCPBUGS-24320: APB status not updated when fails to process during the first reconciliations

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/retry/obj_retry.go
Kind of a backport of https://github.com/openshift/ovn-kubernetes/pull/1957
But with a full re-implementation because of 4.12 vs 4.13 differences
=> [release-4.12] OCPBUGS-23981: Netpol retryFramework cleanup

go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/ovn/base_network_controller_namespace.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/pods_test.go
clean backport of https://github.com/ovn-org/ovn-kubernetes/pull/4047
d/s merge https://github.com/openshift/ovn-kubernetes/pull/1990
=> OCPBUGS-25395: [release-4.15] Update namespace-owned port group (that used to be managed by multicast)

Dockerfile.base
Includes the following relevant changes
d4d068fef6 ovsdb-server: Fix excessive memory usage on DB open.
- https://bugzilla.redhat.com/show_bug.cgi?id=2228464
=> OCPBUGS-27285: Dockerfile: Bump OVS to openvswitch3.1-3.1.0-73.el9fdp

Dockerfile.base, test/e2e/service.go
backport of https://github.com/ovn-org/ovn-kubernetes/pull/4088 + ovn bump
downstream merge here https://github.com/openshift/ovn-kubernetes/pull/2018
=> [release-4.15] OCPBUGS-27255: Ensure session affinity cleanup on backend removal

go-controller/pkg/libovsdb/ops/portgroup.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/base_network_controller_multicast.go, go-controller/pkg/ovn/base_network_controller_namespace.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/multicast_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/batching/batch.go, go-controller/pkg/util/batching/batch_test.go
Backport of 
[upstream] https://github.com/ovn-org/ovn-kubernetes/pull/3968,  [4.15] https://github.com/openshift/ovn-kubernetes/pull/1952
https://github.com/openshift/ovn-kubernetes/pull/1952
minor conflict to remove new function that were added in 4.15
=> [release-4.14] OCPBUGS-23395: Egressfirewall use port groups

Dockerfile.base, test/e2e/service.go
backport of https://github.com/openshift/ovn-kubernetes/pull/2020
Conflicts:
test/e2e/service.go - switched to the ancient test framework version
=> [release-4.14] OCPBUGS-27256: Ensure session affinity cleanup on backend removal

go-controller/pkg/ovn/controller/services/lb_config.go
clean cherry pick of c22ddd42568f77934e08e89c95c8734eac82bfbb from main.
The service's node_switch LB was using the wrong address, breaking LGW IPv6 ETP=Local services.
=> OCPBUGS-27947: [release-4.15] Fix LGW ETP=Local on IPv6

Dockerfile.base, test/e2e/service.go
Backport of https://github.com/openshift/ovn-kubernetes/pull/2021
Use ovn version 23.06.1-82.el9fdp
=> [release-4.13] OCPBUGS-27257: Ensure session affinity cleanup on backend removal

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
This PR is to take care of following things:
- Remove stale ACLs with priority 1013 and still present in Northbound database.
- Avoid panic due to null pointer. This may occur due to presence of an ACL without a name.
Jira: https://issues.redhat.com/browse/OCPBUGS-25611
- Create ACL with 1013 priority and no name:
$ ovn-nbctl --no-leader acl-add clusterRtrPortGroup to-lport 1013 "outport == @ClusterRtrPortGroup && (ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))" allow
$ ovn-nbctl --no-leader acl-add clusterRtrPortGroup from-lport 1013 "inport == @ClusterRtrPortGroup && (ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))" …
=> [release-4.13] OCPBUGS-25611: Avoid panic due to stale ACLs with 1013 priority

go-controller/pkg/node/default_node_network_controller.go
in some cases, multiple nodes will have to sync and we may not have enough subnets available for all of them. In that case we don't want to quit the sync on other nodes if one is found to not have the subnet annotation as the others may still have it.
Also moves log message for duration of different syncs to the end of their sync so it will only print once.
JIRA: https://issues.redhat.com/browse/OCPBUGS-18598
=> OCPBUGS-27925: dont quit if node does not have subnet annotation

.github/workflows/test.yml, go-controller/pkg/kubevirt/router.go, go-controller/pkg/ovn/kubevirt_test.go, test/e2e/kubevirt.go
Kubevirt live migration between nodes that do not own the VM subnet are creating wrongly at ECMP route since is not replacing the point to point routes, this breaks traffic.
This change use just just IPPrefix and Policy at the point to point routes predicate to prevent ECMP.
(cherry picked from commit fb4dec80e8094136ff52d88861d5c7c5c039946b)
Closes https://issues.redhat.com/browse/OCPBUGS-29001
=> [release-4.15] OCPBUGS-29001: kubevirt, Replace routes on migration

go-controller/pkg/libovsdb/ops/chassis.go, go-controller/pkg/libovsdb/ops/model_client.go, go-controller/pkg/libovsdb/ops/model_client_test.go
Clean backport of 4.15 commits fbd29249541a74dd945ff9a5024f425579690cd3 and 0d0b4462066ee83a9f93ef514a6ca815705a7fa8.
For each chassis, there should only be only 1 encap-ip. However the OVN database allows for multiple encap-ips per chassis. In order to recover from a situation where the database already has an existing encap-ip for a chassis and there is a different encap-ip being added to the chassis; we introduce this fix to use "OnModelUpdates" to override the chassis encaps instead of previously appending to it.
Note: This can happen in the case of the DPU because the DPU can have the incorrect encap-ip stored in the SBDB because converting the cluster to DPU-aware may not be a Day0/1 operation but rather a Day2 operation.
Co-authored-by: Flavio Fernandes <flaviof@redhat.com> …
=> [release-4.14] OCPBUGS-25999: Prevent multiple encap-ips per single chassis

go-controller/pkg/clustermanager/egressip_controller.go, go-controller/pkg/clustermanager/egressip_controller_test.go, go-controller/pkg/clustermanager/egressip_event_handler.go
Clean cherry pick from 63641aa8b5faa50be2e7f33b49a6d95c1eacf36e
=> OCPBUGS-28848: Ignore hybrid-overlay nodes from EgressIP controller

go-controller/pkg/clustermanager/egressservice/egressservice_cluster.go, go-controller/pkg/controller/controller.go, go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/controllers/egressservice/egressservice_node.go, go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go, go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go, go-controller/pkg/types/const.go, go-controller/pkg/util/sync.go
Clean cherry pick of:
- separate the handler sync from the informer sync
- remove the full service resync during the node tracker startup since it's redundant: all service keys are added at each node tracker add, but no service controller workers are consuming those keys yet; the services keys are added already in the service controller startup. This is discussed in: https://issues.redhat.com/browse/OCPBUGS-20336?focusedId=23916634&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23916634 and previous comments
Closes #OCPBUGS-29230
=> OCPBUGS-29230: [release-4.15] separate the handler sync from the informer sync & remove the full service resync during node tracker startup 

go-controller/pkg/config/config.go
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1992
Conflicts:
go-controller/cmd/ovnkube/ovnkube.go - remove crash handling
go-controller/pkg/config/config.go - remove clusterManager
=> OCPBUGS-23259: [release-4.12] Update leaderelection config to allow retries

go-controller/pkg/ovn/base_network_controller_policy.go, go-controller/pkg/ovn/policy_test.go
Backport of the first commit from https://github.com/ovn-org/ovn-kubernetes/pull/4086 (4 last ones are UT refactoring)
d/s merge https://github.com/openshift/ovn-kubernetes/pull/2038/commits
no conflicts
=> [release-4.15] OCPBUGS-28725: Update netpol namespace address sets usage to the old ways

go-controller/pkg/clustermanager/egressservice/egressservice_cluster.go, go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/controllers/egressservice/egressservice_node.go, go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go, go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go, go-controller/pkg/types/const.go, go-controller/pkg/util/sync.go
4.14 backport for:
- separate the handler sync from the informer sync
- remove the full service resync during the node tracker startup since it's redundant: all service keys are added at each node tracker add, but no service controller workers are consuming those keys yet; the services keys are added already in the service controller startup. This is discussed in: https://issues.redhat.com/browse/OCPBUGS-20336?focusedId=23916634&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23916634 and previous comments
Two small conflicts:
```
```
- go-controller/pkg/controller/controller.go doesn't exist in 4.14 (https://github.com/openshift/ovn-kubernetes/tree/release-4.14/go-controller/pkg/controller), so I removed the file 
- the cherry-pick applied …
=> OCPBUGS-29231:[release-4.14] Separate timeout for handler sync from informer sync & do not resync services during node tracker startup

Dockerfile.base
- actions: Use random port selection for SNAT with external_port_range.
[https://issues.redhat.com/browse/FDP-301]
[https://issues.redhat.com/browse/RFE-4980]
- northd: Make sure that affinity flows match on VIP.
[https://issues.redhat.com/browse/FDP-290]
- ovn: Add tunnel PMTUD support.
[https://bugzilla.redhat.com/show_bug.cgi?id=2241711]
- northd: Use proper field for lookup_nd
[https://issues.redhat.com/browse/FDP-283]
[https://issues.redhat.com/browse/OCPBUGS-27093]
- northd: Remove the protocol match from ECMP symmetric reply flows.
[https://issues.redhat.com/browse/FDP-358]
- northd: Explicitly handle SNAT for ICMP need frag.
[https://issues.redhat.com/browse/FDP-159]
=> OCPBUGS-27093: Dockerfile: Bump OVN to ovn-23.09.0-112.el9fdp

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/node_ip_handler_linux.go
Manual backport of 4.14 commits 77aaa9693266edf131489d36c5deef24fee9977c, 4622d618699ad5c16db28e3e099acf22a16caf7c and 4e6fbc60c1334534d25c75cceaaa636fdd78532a.
Conflicts:
`go-controller/pkg/node/node_ip_handler_linux.go`
=> [release-4.13] OCPBUGS-28630: Synchronize node primary address update

go-controller/pkg/ovn/base_network_controller_policy.go, go-controller/pkg/ovn/policy_test.go
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2050
conflicts are related to error checks added in 4.15 https://github.com/openshift/ovn-kubernetes/commit/810ed6ad1cf4a160a87a5a0dcc33081f1230397b, but these function calls were just removed by the change
=> [release-4.14] OCPBUGS-28726: Update netpol namespace address sets usage to the old ways

go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go, go-controller/pkg/ovn/controller/egress_services/egress_services_node.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/egressservices_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/util.go, test/e2e/egress_services.go, test/e2e/egressip.go
Manual cherry-pick of 4.14 commit 5c6edd6271697912d2fd732fc796a60a88981954.
Resolved conflicts:
```
go-controller/pkg/ovn/egressservices_test.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/util/node_annotations.go
go-controller/pkg/util/util.go
```
Match on all node's IP addresses on the no re-route policies so that intra cluster traffic is not routed through the egress or service IP even when the destination IP address is a secondary node IP.
Secondary node IPs might be VIPs that move across nodes.
(cherry picked from commit 5c6edd6271697912d2fd732fc796a60a88981954)
=> OCPBUGS-29851: Egress IP, Services: use all node IP addresses

go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go, go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go, go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go, go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go, go-controller/pkg/ovn/controller/apbroute/gateway_info/gateway_info.go, go-controller/pkg/ovn/controller/apbroute/master_controller.go, go-controller/pkg/ovn/controller/apbroute/network_client.go
Fix backported from 4.15 and merged in https://github.com/ovn-org/ovn-kubernetes/pull/3934
The issue is that pods that don't have an `IP` in their status when being processed by the APB controller fail to trigger a new reconciliation loop, thus missing the logic that adds their configuration to the north bound DB.
@npinaeva @jcaamano PTAL.
@josecastillolema FYI.
=> [release-4.14] OCPBUGS-29342: AdminPolicyBasedExternalRoute CRD failing to watch and reconcile routes for later pods

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
backport of https://github.com/openshift/ovn-kubernetes/pull/2068
conflicts around renaming oc to bnc and unit test functions signature changes
=> [release-4.13] OCPBUGS-28983,OCPBUGS-30920: Update netpol namespace address sets usage to the old ways

Dockerfile
resolves OCPBUGS-24007
For upgrades from 4.12 to 4.13 on fips we needed to include both a rhel8 and 9 binary based ovn-k container image, this is not needed on 4.14+ clusters
=> OCPBUGS-24007: Remove unnecessary rhel8 build layer

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-control-plane.yaml.j2, docs/ovnkube.1, go-controller/pkg/clustermanager/clustermanager_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
CLEAN cherry pick from #2089
"v4-transit-switch-subnet" and "v6-transit-switch-subnet" flags were added via commit[1]. However some configurations were still missing to allow setting custom subnets while creating a kind cluster.
This PR is to allow overriding default v4 and v6 transit switch subnet while creating a kind cluster.
[1] - https://github.com/ovn-org/ovn-kubernetes/commit/ae27492e2ecdbb6139c2deba9919ca9da51d32cc
=> OCPBUGS-32154: Custom v4 and v6 transit switch subnets while creating kind cluster

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-control-plane.yaml.j2, docs/ovnkube.1, go-controller/pkg/clustermanager/clustermanager_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Cherry pick from #2094 
"v4-transit-switch-subnet" and "v6-transit-switch-subnet" flags were added via commit[1]. However some configurations were still missing to allow setting custom subnets while creating a kind cluster.
This PR is to allow overriding default v4 and v6 transit switch subnet while creating a kind cluster.
[1] - ovn-org/ovn-kubernetes@ae27492
=> OCPBUGS-32353: Custom v4 and v6 transit switch subnets while creating kind cluster

Dockerfile.base
Relevant OVN features/performance improvements:
- ovn-northd logical flow incremental processing
- improved RBAC for Southbound BFD, IGMP_Group tables
- QoS packet marking:
https://issues.redhat.com/browse/FDP-42
- BFD support for ECMP policy routes
https://issues.redhat.com/browse/FDP-234
- Support new LSP enable_router_port_acl option to enable conntrack for router ports
OCP relevant fixes:
- a349ec5c14 northd: sync lb applied to logical routers in sb db lb table
https://bugzilla.redhat.com/show_bug.cgi?id=2193323
- allows using OVN's LB conntrack flushing feature on backend removal
- 6eff687d5f acl-log: Properly log the "pass" verdict.
https://issues.redhat.com/browse/FDP-442
Other relevant fixes:
- 69e90f664a northd: fix infinite loop in ovn_allocate_tnlid()
- 72390c4fea pinctrl: …
=> OCPBUGS-32985,SDN-4436: Dockerfile.base: Bump OVN to ovn24.03-24.03.1-36.el9fdp

Dockerfile.base
OVS 3.3 is going to be a new LTS release.  It also includes significant database performance improvements especially in the area of initial database file read and the database conversion on updates.
OVS 3.3 also includes extended support for NXT_CT_FLUSH allowing to flush CT entries by marks and labels.  This will be used in future versions on OVN.  (Though this is not relevant for the ovn-kubernetes container image.)
=> OCPBUGS-32985,OCPBUGS-32925: Dockerfile: Bump OVS to 3.3.0-2

go-controller/pkg/ovn/controller/apbroute/master_controller.go
Fixes an issue when using APB in a cluster with high number of pods where the APB controller would hit the KAPI for each pod event to update the APB status, causing a high cpu usage.
The fix resolves in checking if the last message in the APB status in the informer matches the same message generated for the pod event, and if different or different status (succeeded or failed) then proceed to request the latest copy of the APB CR from the KAPI server and update it.
=> OCPBUGS-29397: 4.14 High CPU usage with APB CRD

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/controller/services/lb_config.go, go-controller/pkg/ovn/controller/services/lb_config_test.go, go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/testing/kube.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
- clean cherry pick of first commit (32d2ce19dd0f9e76eb2a1ca5b966d02507779f0e) from master branch
- cherry pick of ETP=local fix (e2faa152408d9cad1f6cc8dcf0318ab9f4ae6d8c) from master branch, applying the exact same changes we have on master for the affected OCP hacks. I had to replace all calls to `k8s.io/utils/ptr` (e.g. `ptr.To(true)`) with calls to the older library `k8s.io/utils/pointer` (e.g. `utilpointer.Bool(true)`), since that's new code that we only vendor in 4.16.
**First commit:**
The previous implementation was an approximation of KEP-1669 ProxyTerminatingEndpoints: we simply included terminating serving endpoints (ready=false, serving=true, terminating=true) along with ready ones in the endpoint selection logic. Let's fully implement KEP-1669 and only include terminating …
=> OCPBUGS-27852: [release-4.15] Full implementation of KEP-1669 ProxyTerminatingEndpoints + ETP=local fix

Dockerfile.base, dist/images/Dockerfile.fedora, test/e2e/service.go
Bumped fedora to the closest version available.
Bumped OVN within `Dockerfile.base` to a version that contains the fix required in the bug and is available via brew.
The fix is included in `23.06.1-110`: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2944959
=> OCPBUGS-33218: [release-4.13] OVN bump to 23.06.1-112

Dockerfile.base
bumping to version openvswitch3.1-3.1.0-88.el9fdp fixes: 
CVE-2023-3966
CVE-2023-5366
=> [Release 4.15] OCPBUGS-32986: Bump OVS

Dockerfile.base, test/e2e/service.go
Bumped OVN within Dockerfile.base to a version that contains the fix required in the bug and is available via brew.
The fix is included in 23.06.1-110: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2944959
OVN fix:
```
"northd: Don't skip the unSNAT stage for traffic towards VIPs."
upstream commit: a4dbe60d7bf1b7aa7698bfbd25be018492fd25d7
```
=> OCPBUGS-25889: [release-4.12] OVN bump to 23.06.1-112

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/iptables/iptables.go, go-controller/pkg/util/iptables.go, go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go, go-controller/vendor/modules.txt
Only conflicts were in 2nd commit: "Fixes inefficient service parsing". I had to add a downstream carry commit in order to fix ordering for MCS rules and ensure they were at the top of the chain for unit tests.
=> OCPBUGS-32426: [release-4.15] Improves service iptables efficiency on start up

Dockerfile.base
bumping to version openvswitch3.1-3.1.0-88.el9fdp fixes: 
CVE-2023-3966
CVE-2023-5366
=> [Release 4.14] OCPBUGS-32987: Bump OVS

go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck_service.go, go-controller/pkg/ovn/controller/services/lb_config.go, go-controller/pkg/ovn/controller/services/lb_config_test.go, go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/testing/kube.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/util.go
Differences from 4.14 backport (https://github.com/openshift/ovn-kubernetes/pull/2128):
I had to backport two relevant commits from last year that hadn't been backported to 4.13.
- no conflicts
- conflict between old and new code of GetLbEndpoints -> applied new code
- conflict with new tests for GetLbEndpointsL: applied new code
```
$ git cherry-pick -x f9185969ae241916687699048e291f1c803e8843
Auto-merging go-controller/pkg/node/default_node_network_controller.go
Auto-merging go-controller/pkg/node/gateway_shared_intf.go
Auto-merging go-controller/pkg/util/kube.go
CONFLICT (content): Merge conflict in go-controller/pkg/util/kube.go
Auto-merging go-controller/pkg/util/kube_test.go
CONFLICT (content): Merge conflict in go-controller/pkg/util/kube_test.go
error: could not apply f9185969a... …
```
=> OCPBUGS-33421: [release-4.13] Full implementation of KEP-1669 ProxyTerminatingEndpoints + ETP=local fix

Dockerfile.base
fixes two CVE issues
bumping Open Vswitch fixes 
CVE-2023-5366
CVE-2023-3966
=>  [release-4.13] OCPBUGS-32988: Bumping OVS

Dockerfile.base
The current process involving a reconciliation of the openshift/release from ART does not allow overwriting the build arguments in the OKD variant Prow Config for ovn-kubernetes. This commit adds two additional build-args with default values for OKD and let the RUN layer decide on whether to use them as ovn and ovs versions to consider for installation.
To simplify (avoid redundant shell code), this PR also proposes to flatten the second RUN layer into the first.
- [OCP] ci/prow/images should succeed => 
- [OKD] ci/prow/okd-scos-images should succeed => https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2161/pull-ci-openshift-ovn-kubernetes-ma …
=> OKD-40: Add ovnver_okd and ovsver_okd to Dockerfile.base

go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck_service.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_ocphack_test.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/testing/kube.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/util.go
Differences from 4.13 backport (https://github.com/openshift/ovn-kubernetes/pull/2130):
Backporting the whole https://github.com/openshift/ovn-kubernetes/commit/f6ef43368cc79b85bf0de535ff3b79a5856ab481#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4, which had only been partially backported to 4.12 with https://github.com/openshift/ovn-kubernetes/commit/aceef010daf0697fe81dba91a39ed0fdb6563dea#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4, due to https://github.com/openshift/ovn-kubernetes/commit/80dc930e4bc44256a017849762bf6c5f949209fb not being in 4.12 at the time of the backport. This mainly meant that GetLocalEndpointAddresses, modified by my commit in 4.13,  wasn't in go-controller/pkg/node/gateway_shared_intf.go at the time and had to be …
=> OCPBUGS-33422: [release-4.12] Full implementation of KEP-1669 ProxyTerminatingEndpoints + ETP=local fix

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/iptables/iptables.go, go-controller/pkg/util/iptables.go, go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go, go-controller/vendor/modules.txt
Includes manual backport of ec5685b as first commit. This needs close review. The rest of the commits were pretty clean. A few trivial things that don't need close attention.
Note, @tssurya brought up a valid question to why https://github.com/openshift/ovn-kubernetes/pull/2172/commits/461b9882bdd6dee89a5846e8e227068060849c16 was necessary (CARRY: fix ordering of MCS blocking iptables rules).
Due to the forwarding rules added in 4.14 and later in initExternalBridgeServiceForwardingRules, the downstream tests have been broken:
```
[Fail] Gateway Init Operations Setting up the gateway bridge [It] sets up a local gateway with predetermined interface 
/mnt/crucial/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node/gateway_init_linux_test.go:1207
[Fail] Gateway Init Operations …
```
=> [release-4.13] OCPBUGS-33730: Improves service iptables efficiency on start up

go-controller/pkg/clustermanager/node/subnet_allocator.go, go-controller/pkg/clustermanager/node/subnet_allocator_test.go
This PR is to return an already allocated subnet instead of creating a new one if a combination of subnet and node name already exists in the cache.
This PR is to stop multiple allocation of node-subnet from ClusterNetwork CIDR for any node if addition of
'k8s.ovn.org/node-subnets' annotation gets delayed but does not reach default BackOff[1] time limit for retry framework and meanwhile syncNodeNetworkAnnotations[2] gets executed multiple times.
JIRA: https://issues.redhat.com/browse/OCPBUGS-25733
[1] - https://github.com/kubernetes/client-go/blob/v0.26.1/util/retry/util.go#L38
[2] - https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/clustermanager/node/node_allocator.go#L178
Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com> …
=> OCPBUGS-33294: Reuse node-subnet from cache if exists

Dockerfile.base
Bumping ovn to 23.06.1-112.el8fdp brings in fixes for 
CVE-2024-2182
Bumping ovs to 2.17.0-148.el8fdp brings in fixes for 
CVE-2022-4337
CVE-2022-4338
CVE-2023-1668
CVE-2023-3966
CVE-2023-5366
=> [release-4.12] OCPBUGS-32990: Bump OVS

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/node/OCP_HACKS.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/iptables/iptables.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/iptables.go, go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go, go-controller/vendor/modules.txt
Conflicts and modifications done in the first patch: [CARRY: manual cherry pick of iptables refactor](https://github.com/openshift/ovn-kubernetes/commit/5b6b6e9e038ff06c0e3c3d8bf6cf463753b37bfb)
The rest was pretty clean. I also brought in [Make PMTUD works in shared gateway mode](https://github.com/openshift/ovn-kubernetes/commit/84895aea4cdc980202c54969d01da2a70c219ac3)
in order to make the rest of the cherry-picking clean.
@pperiyasamy fyi ^
=> [release-4.12] OCPBUGS-34273,OCPBUGS-34414: Improves service iptables efficiency on start up + ICMP error messages to pass through

Dockerfile.base
This version of OVN reverts some multicast commits that introduced a regression.
https://issues.redhat.com/browse/FDP-656
=> OCPBUGS-35835: [release-4.16] bump OVN to ovn24.03-24.03.2-19.el9fdp 

dist/images/ovnkube.sh, go-controller/pkg/config/config.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/kube.go, test/e2e/service.go, test/e2e/util.go
Backport of 9051f15
Also cherry-picked related (but non feature) commits for reduced conflict resolution:  8bb2db423 0ae0b0ea9
Conflicts (trivial):
* go-controller/pkg/node/gateway_shared_intf.go
* go-controller/pkg/util/kube.go
* test/e2e/util.go
=> OCPBUGS-36382: Handle IP fragments in SGW mode

dist/images/ovnkube.sh, go-controller/pkg/config/config.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/kube.go, test/e2e/service.go, test/e2e/util.go
Backport to 4.14 of e6f139e 3fe4301 b7ba318 from 4.15 #2215
Also cherry-picked related (but non feature) commits from 4.15 for reduced conflict resolution: 7f1d28f
Conflicts:
* ovnkube.sh (trivial)
* util.go (changes on the e2e APIs)
* service.go: this one was in a bad state and did not even compile in HEAD, so added a CARRY commit to fix compilation errors. Then it had trivial conflicts and also changes due to different e2e APIs. No guarantees it actually works as it obviously didn't before. It does compile.
=> OCPBUGS-36554: Handle IP fragments in SGW mode

go-controller/pkg/node/ovspinning/ovspinning_linux.go, go-controller/pkg/node/ovspinning/ovspinning_linux_test.go, go-controller/pkg/node/ovspinning/testdata/fake_thread_process.go
OVS CPU pinning ensures the CPU consumed by the processes `ovsdb-server` and `ovs-vswitchd` are the same as the OVNkube container. `ovs-vswitchd` process has threads and calling `SchedSetaffinity()` on the main PID only is does not guarantee that the already spawned threads inherit that affinity. The following is an example of such a situation:
```
sh-4.4# taskset -apc $(pgrep ovs-vswitchd)
pid 4059's current affinity list: 0-2,6,9,15-66,69,70,73,79-127
pid 4335's current affinity list: 0-2,32,33,64-66,96,97
pid 2715051's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
pid 2715052's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
pid 2715053's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
...
```
This changes makes the CPU align routine loop over all the threads of the …
=> OCPBUGS-36608: [release-4.16] ovspinning: Set affinity of each thread

dist/templates/ovnkube-db.yaml.j2, dist/templates/ovnkube-single-node-zone.yaml.j2, dist/templates/ovnkube-zone-controller.yaml.j2, go-controller/pkg/metrics/ovn_northd.go, helm/ovn-kubernetes/charts/ovnkube-db-raft/templates/statefulset.yaml, helm/ovn-kubernetes/charts/ovnkube-db/templates/deployment.yaml, helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml, helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
With IC, we are not registering northd metrics since there is no ovnkube-master pod. To fix, use `ovn-db-pod=true` label instead since in all our deployment models northd has been collocated with the DBs.
(cherry picked from commit d8c924f33cbaa5a5a8c507c8b759c0209da88496)
no conflicts.
=> OCPBUGS-37362: Fix registering northd metrics on appropriate nodes

dist/templates/ovnkube-db.yaml.j2, dist/templates/ovnkube-single-node-zone.yaml.j2, dist/templates/ovnkube-zone-controller.yaml.j2, go-controller/pkg/metrics/ovn_northd.go
With IC, we are not registering northd metrics since there is no ovnkube-master pod. To fix, use `ovn-db-pod=true` label instead since in all our deployment models northd has been collocated with the DBs.
(cherry picked from commit d8c924f33cbaa5a5a8c507c8b759c0209da88496) (cherry picked from commit f8eaec6f5ede7f5838313658de77a8ebac9bd4ad)
=> [release-4.15] OCPBUGS-37962: Fix registering northd metrics on appropriate nodes

.github/workflows/test.yml, docs/features/cluster-egress-controls/egress-ip.md, go-controller/pkg/node/controllers/egressip/egressip.go, go-controller/pkg/node/controllers/egressip/egressip_test.go, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/linkmanager/link_network_manager.go, go-controller/pkg/node/linkmanager/link_network_manager_test.go, go-controller/pkg/node/openflow_manager.go, go-controller/pkg/node/openflow_manager_test.go, go-controller/pkg/node/routemanager/route_manager.go, go-controller/pkg/node/routemanager/route_manager_test.go, test/e2e/egressip.go
/hold
~During cherry-pick, I needed to adjust d83b3f916cb9a384009afb89dc4a8f70ac87bcc3 to remove the UDN APIs regarding lookup by network for the cluster router name. Also needed to fix conflicts in the OVN EIP test file.~
cc @maiqueb @pperiyasamy @tssurya
=> OCPBUGS-38699,OCPBUGS-38704: EgressIP VRF support & ignore localnet patch ports when bootstrapping

Dockerfile.base
The new OVS version is used by the OVN observability.
RHCOS counterpart: https://issues.redhat.com//browse/OCPBUGS-37875
previous bump: https://github.com/openshift/ovn-kubernetes/pull/2142
=> OCPBUGS-38270: Dockerfile: Bump OVS to 3.4.0-1

go-controller/pkg/libovsdb/ops/router.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Manually cherry-picked. Resolved conflicts:
`go-controller/pkg/ovn/egressip.go` (had to refer to `types.OVNClusterRouter` instead of `e.GetNetworkScopedClusterRouterName()`)
`go-controller/pkg/ovn/egressip_test.go` (had to align the test with 4.17 to get test succeed)
=> [release-4.16] OCPBUGS-38705: Delete EgressIP LRP stale nexthops when node is not found

go-controller/pkg/node/controllers/egressservice/egressservice_node.go, go-controller/pkg/node/egress_service_test.go, test/e2e/egress_services.go
Almost clean cherry-pick, 4.16 uses:
* `errors.NewAggregate` instead of `utilerrors.Join`
* `f4.MatchState(expectedTables)` instead of `f4.MatchState(expectedTables, nil)`
=> OCPBUGS-24386: [release-4.16] EgressService: Fix ETP=Local ingress reply for LGW

go-controller/pkg/ovn/hybrid.go, go-controller/pkg/ovn/hybrid_test.go, go-controller/pkg/ovn/master.go
It can help to avoid the unintended match when the '-gr' substring exists in a node name.
This is manual cherrypick of commit 6dd663235dab22377971f2b9e109b7af327fd9fb
=> [release-4.16] OCPBUGS-38697: Use more exact name match when deleting static routes to HO nodes.

Dockerfile.base
Upstream bump and test: https://github.com/ovn-org/ovn-kubernetes/pull/4712
=> SDN-4930: Bump OVN to ovn24.09-24.09.0-beta.31.el9fdp

go-controller/pkg/clustermanager/clustermanager_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/config/utils.go
This PR is to emit error and terminate ovnkube startup if transit switch subnet is being used as either join switch or masquerade subnet.
Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com>
(cherry picked from commit 46d35e6ce0f5c4a36906f050d11e99b72e390077)
Fixes #
```release-note
```
=> [release-4.16] OCPBUGS-41551: Add subnet overlap check for transit switch subnet

Dockerfile
Until the libreswan issue is fixed in RHEL:
https://issues.redhat.com/browse/RHEL-61461
This is 4.14 only fix 
Several reasons we don't do it in 4.15 and beyond:
1. libreswan is installed on the host via rhcos extension, it was suggested to use layered coreos image instead of pinning the extension
2. libreswan-4.5 doesn't solve the bug on 4.15: https://issues.redhat.com/browse/OCPBUGS-41823
3. It is considered risky by coreos team to update the default rhcos image as libreswan-4.5 is quite old
=> OCPBUGS-42952: pin libreswan to the known working version 4.5

Dockerfile.base
This fixes the database schema mismatch causing ovnkube-node pods to crash.
=> OKD-227: bump ovn version to 24.09.0-41 for OKD

go-controller/pkg/ovn/ovn.go, test/e2e/external_gateways.go, test/scripts/e2e-cp.sh
Backport of https://github.com/ovn-org/ovn-kubernetes/pull/4744
d/s merge https://github.com/openshift/ovn-kubernetes/pull/2314
=> OCPBUGS-42940: Fix egress gateway pod cleanup for remote zone pods.

go-controller/pkg/allocator/pod/pod_annotation_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/pod_annotation.go
When users attach pod to a secondary network and override the default route pod. It will cause the assymetric routing for service haripin traffic.
We add static routes to ensure the traffic to the hairpin masquerade IP always goes to OVN.
(This is a clean cherry-pick of 6cdf7ecdff5ea9017c09ca8b35acc3de944a6eff)
Fixes #
```release-note
```
=> [release-4.17] OCPBUGS-42931: Add static route to the hairpin masquerade IPs to pod

go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go
During live SDN migration, host-to-pod traffic originating from SDN nodes will use the first IP address of the hybrid overlay node subnet. These IPs are being added to ensure proper functionality of host network policies.
This is d/s only patch. It's for the SDN live migration scenario.
=> [release-4.16] OCPBUGS-43344: Add SDN node subnet gateway IP to host-network address_set

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go
Add hybird overlay pod IPs to the namespace address_set.
This is a clean cherry-pick of d20b22110a912a244f4cd42f0969df60eaf434fc
=> [release-4.17] OCPBUGS-44303: Add hybird overlay pod IPs to the namespace address_set

go-controller/pkg/ovn/ovn.go, test/e2e/external_gateways.go, test/scripts/e2e-cp.sh
backport of https://github.com/openshift/ovn-kubernetes/pull/2316
=> OCPBUGS-42944: Fix egress gateway pod cleanup for remote zone pods.

go-controller/pkg/clustermanager/secondary_network_cluster_manager.go, go-controller/pkg/network-attach-def-controller/network_manager.go
This PR ignores topology net managed errors on the initial all networks sync of the cluster manager controllers.
Only the `secondaryNetworkClusterManager` - which is created by the cluster controller manager, and executed in the control plane pods - actually returns this type of error.
The original PR (upstream) is: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4813
The code was merged downstream to openshift/master with: https://github.com/openshift/ovn-kubernetes/pull/2345
Fixes #
This was **not** a clean cherry-pick - there were conflicts in all the files.
Conflicts in `go-controller/pkg/clustermanager/secondary_network_cluster_manager.go`:
```sh
++<<<<<<< HEAD
+// Start the secondary layer3 controller, handles all events and creates all
++=======
+ func (sncm …
```
=> [release-4.17] OCPBUGS-43454: Ignore cluster manager topology not managed errors for localnet with no subnets

go-controller/pkg/libovsdb/ops/router.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Manual cherry-pick of 4.15 commit d61d75bf5b7d4a7b5de3fb7013eb933b5a8adaad.
No conflicts (avoided auto cherry-pick to avoid another backport bug being created)
=> [release-4.14] OCPBUGS-44793: Delete EgressIP LRP stale nexthops when node is not found 

Dockerfile, Dockerfile.base
- connection timeouts are now 5s instead of default 30s
- adding flag to skip_if_unavailable so it will not retry on failure
Fixes #
=> SDN-5498: make dnf get through repo troubles faster

Dockerfile.base
It is the most recent release of 24.03 with all the latest bug fixes.   See the jira for more details.
=> OCPBUGS-45339: Dockerfile: Update OVN to the 24.03.2-32.el9fdp minor release.

Dockerfile
For a crash fix and CVE backports in libreswan
NOTE: This is a temporary fix until the RHEL fix lands because we have time constrants and this will be reverted in the future on all the pinning PRs
=> OCPBUGS-45314: pin libreswan to 4.6-3.el9_0.3

Dockerfile.base
It is the most recent release of 24.03 with all the latest bug fixes. See the jira for more details.
=> OCPBUGS-45343: Dockerfile: Update OVN to the 24.03.2-32.el9fdp minor release.

Dockerfile
For a crash fix and CVE backports in libreswan
=> [release-4.17] OCPBUGS-45312: pin libreswan to 4.6-3.el9_0.3

Dockerfile
For a crash fix and CVE backports in libreswan
=> [release-4.14] OCPBUGS-45096: pin libreswan to 4.6-3.el9_0.3

Dockerfile.base
bump ovs version to openvswitch3.4-3.4.0-18.el9fdp for ocp 4.19 to include the ovs-monitor-ipsec improvement https://issues.redhat.com/browse/FDP-846
=> OCPBUGS-45951: bump OVS version to 3.4.0-18

go-controller/pkg/allocator/pod/pod_annotation_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/pod_annotation.go
When users attach pod to a secondary network and override the default route pod. It will cause the assymetric routing for service haripin traffic.
We add static routes to ensure the traffic to the hairpin masquerade IP always goes to OVN.
This is a manual cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2315. Resolve the conflict by removing the condition check for UDN `podAnnotation.Role == types.NetworkRolePrimary`.
=> [release-4.16] OCPBUGS-44457: Add static route to the hairpin masquerade IPs to pod

Dockerfile
For a crash fix and CVE backports in libreswan
=> [release-4.15] OCPBUGS-45097: pin libreswan to 4.6-3.el9_0.3

go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
Presently for each remote node, ovnkube after creating the remote port in the OVN Northbound db transit switch, binds the port to the remote chassis in the Southbound database.  In order to do this, we have to wait for the remote logical ports (for each of the remote zone nodes) to appear in the OVN Southbound database. This can lead to race conditions.  Instead ask ovn-northd to bind to the remote chassis.  OVN after this commit [1] already supports this.  We just need to set the requested-chassis option in the logical port.
[1] - https://github.com/ovn-org/ovn/commit/170d3e5f19f0fcd760db068cda29fc1b7f1d7ef5
Jira: https://issues.redhat.com/browse/OCPBUGS-42616
Signed-off-by: Numan Siddique <numans@ovn.org>
(cherry picked from commit e4f360cc82c4202175b8667398a4dcc7334aafd9)
=> OCPBUGS-47506: Let OVN-northd bind remote ports

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go
This is a manual cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2352
Fix the function name mismatch in pods_test.go. Replace `ExpectAddressSetWithAddresses` with `ExpectAddressSetWithIPs`.
=> [release-4.15] OCPBUGS-44708: Add hybird overlay pod IPs to the namespace address_set

Dockerfile.base
This picks up the following relevant bug fixes:
https://issues.redhat.com/browse/FDP-906
"ovn-controller: lib/ovsdb-idl.c:3596: assertion row->new_datum != NULL failed in ovsdb_idl_txn_write__()"
6448f5e364 pinctrl: Skip non-local mac bindings in run_buffered_binding().
ea35347320 pinctrl: Skip deleted mac bindings in run_buffered_binding().
33a6ae53f4 pinctrl: Use correct map size in pinctrl_handle_put_fdb().
8eaa7d5991 controller: Fix "use after free" issue in statctrl_run().
8579859f51 mac-cache: Properly handle deletion of SB mac_bindings.
https://issues.redhat.com/browse/FDP-752
"ovn-northd IPAM incorrectly reports duplicate IP when part of excluded_ips"
2a24b03f7f ipam: Do not report error for static assigned IPs.
https://issues.redhat.com/browse/FDP-786
"When an ECMP symmetric …
=> OCPBUGS-42707: Bump OVN to ovn24.09-24.09.1-10.el9fdp

go-controller/pkg/clustermanager/egressip_event_handler.go, go-controller/pkg/clustermanager/network_cluster_controller.go, go-controller/pkg/clustermanager/pod/allocator.go, go-controller/pkg/clustermanager/userdefinednetwork/controller_test.go, go-controller/pkg/clustermanager/zone_cluster_controller.go, go-controller/pkg/node/obj_retry_gateway.go, go-controller/pkg/node/obj_retry_node.go, go-controller/pkg/node/obj_retry_test_helper.go, go-controller/pkg/node/secondary_node_network_controller.go, go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/base_secondary_layer2_network_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/multicast_test.go, go-controller/pkg/ovn/multipolicy_test.go, go-controller/pkg/ovn/network_controller_policy_event_handler.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/secondary_layer2_network_controller.go, go-controller/pkg/ovn/secondary_layer3_network_controller.go, go-controller/pkg/ovn/secondary_localnet_network_controller.go, go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go, go-controller/pkg/retry/obj_retry.go, go-controller/pkg/types/const.go, go-controller/pkg/util/multi_network.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/subnet_annotations.go
Includes latest performance and other fixes merged upstream.
Includes unmerged upstream PR: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5013
do not remove the hold on this PR unless the upstream PR has been approved by @jcaamano or @kyrtapz
=> SDN-4930: [DownstreamMerge] 1-29-25

go-controller/pkg/kubevirt/pod.go, go-controller/pkg/node/linkmanager/link_network_manager.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/multihoming_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/secondary_layer2_network_controller.go, go-controller/pkg/ovn/secondary_layer2_network_controller_test.go, go-controller/pkg/ovn/secondary_layer3_network_controller_test.go, go-controller/pkg/util/arp.go, test/e2e/kubevirt.go, test/e2e/kubevirt/net.go
Merge to include virt last importanat bits for UDN:
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4964
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4917
=> OCPBUGS-45469, OCPBUGS-49337: [DownstreamMerge] 2-6-25

Dockerfile.base
Bump ovn to 24.09.2-14 to bring in a critical fix for ARP binding expiration ([FDP-1131](https://issues.redhat.com//browse/FDP-1131)).
=> OCPBUGS-49840: Bump OVN to 24.09.2-14 for FDP-1131

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/pods_test.go
currently when creating egressIP in a dualstack cluster regardless of if the egressip is ipv4 or ipv6 when disable-snat-multiple-gws is set the code removes both ipv4 and ipv6 snats from the database. This means that the pod will not be able to communicate with the cluster correctly becuase the Gateway Router is missing an SNAT and the traffic will be dropped.
Additionally the testing looks a little different from the others because we do not correctly setup dualstack clusters when running unit tests
Fixes #
=> [release-4.17] OCPBUGS-48828: fixes overzealous deletion of SNAT in egressIP

go-controller/pkg/kubevirt/pod.go, go-controller/pkg/kubevirt/pod_test.go, go-controller/pkg/libovsdb/ops/model.go, go-controller/pkg/libovsdb/ops/switch.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/multihoming_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/secondary_layer2_network_controller_test.go, go-controller/pkg/ovn/secondary_layer3_network_controller_test.go, test/e2e/go.mod, test/e2e/images/crictl.go, test/e2e/kubevirt.go, test/e2e/kubevirt/ip.go, test/e2e/kubevirt/types.go, test/e2e/multihoming_utils.go
Currently all pods have the LSP.Enabled option set to nil (which later
translates to &true) by default.
During live-migration of kubevirt pods, in order to prevent unneeded
packet loss the lsp.Enabled of the migration pods (source and target)
need to be as follows:
until target pod is domain ready: source pod lsp is enabled, target
pod lsp is disabled.
when target pod is domain-ready: source pod lsp is disabled, target
pod lsp is enabled.
This switch significantly reduces the migration downtime to <0.5s (see details below).
This PR also handles the scenario of a failed migration, where the lsp
of the source pod needs to be re-enabled.
Apart from playing with lsp Enabled field for localnet is also needed to remove Addresses field to be sure that OVN is removing the L2 lookup table so …
=> [release-4.17] OCPBUGS-50519: kubevirt, localnet: Reduce live migration downtime

go-controller/pkg/ovn/base_network_controller.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go
During live SDN migration, host-to-pod traffic originating from SDN nodes will use the first IP address of the hybrid overlay node subnet. These IPs are being added to ensure proper functionality of host network policies.
This manual backport resolved the conflict that the method`DeleteAddresses` of `AddressSet` doesn't exist in 4.15, by replacing it with `DeleteIPs`.
=> [release-4.15] OCPBUGS-43605: Add SDN node subnet gateway IP to host-network address_set

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/pods_test.go
currently when creating egressIP in a dualstack cluster regardless of if the egressip is ipv4 or ipv6 when disable-snat-multiple-gws is set the code removes both ipv4 and ipv6 snats from the database. This means that the pod will not be able to communicate with the cluster correctly becuase the Gateway Router is missing an SNAT and the traffic will be dropped.
Additionally the testing looks a little different from the others because we do not correctly setup dualstack clusters when running unit tests
(cherry picked from commit e64d7549bee70494ce829637f97f15282f3b171e)
4.16 is not using ginkgo v2 so the new tests that came in from this PR using DescribeTable() and Entry() from v2 had
to be converted to ginkgotable.DescribeTable and …
=> [release-4.16] OCPBUGS-50594: fixes overzealous deletion of SNAT in egressIP

go-controller/pkg/kubevirt/pod.go, go-controller/pkg/kubevirt/pod_test.go, go-controller/pkg/libovsdb/ops/model.go, go-controller/pkg/libovsdb/ops/switch.go, go-controller/pkg/ovn/base_network_controller_pods.go, go-controller/pkg/ovn/base_network_controller_secondary.go, go-controller/pkg/ovn/multihoming_test.go, go-controller/pkg/ovn/multipolicy_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/secondary_layer2_network_controller_test.go, go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
Currently all pods have the LSP.Enabled option set to nil (which later
translates to &true) by default.
During live-migration of kubevirt pods, in order to prevent unneeded
packet loss the lsp.Enabled of the migration pods (source and target)
need to be as follows:
until target pod is domain ready: source pod lsp is enabled, target
pod lsp is disabled.
when target pod is domain-ready: source pod lsp is disabled, target
pod lsp is enabled.
This switch significantly reduces the migration downtime to <0.5s (see details below).
This PR also handles the scenario of a failed migration, where the lsp
of the source pod needs to be re-enabled.
Apart from playing with lsp Enabled field for localnet is also needed to remove Addresses field to be sure that OVN is removing the L2 lookup table so …
=> [release-4.16] OCPBUGS-50595: kubevirt, localnet: Reduce live migration downtime

Dockerfile.base
This contains the following relevant changes:
- controller: Fix active mac-binding refresh for IPv6.
- controller: Send ARP/ND for stale mac_bindings entries. (#FDP-1135)
https://issues.redhat.com/browse/FDP-1135
- northd: Fix action parsing in build_lb_vip_actions(). (#FDP-1095)
https://issues.redhat.com/browse/FDP-1095
- northd: Fix missing tier related ACL flows. (#FDP-1154)
https://issues.redhat.com/browse/FDP-1154
- mac-cache: Fix expiration of active FDB entry due to skipped update. (#FDP-1132)
https://issues.redhat.com/browse/FDP-1132
- mac-cache: Fix expiration of active MAC binding due to skipped update. (#FDP-1130)
https://issues.redhat.com/browse/FDP-1130
- mac-cache: Fix MAC binding entry lookup for timestamp refresh. (#FDP-1131)
https://issues.redhat.com/browse/FDP-1131
Fixes …
=> OCPBUGS-48678: Update OVN to FDP25.A.1 24.09.2-41

Dockerfile.base
- controller: Fix active mac-binding refresh for IPv6.
- controller: Send ARP/ND for stale mac_bindings entries. (#[FDP-1135](https://issues.redhat.com//browse/FDP-1135))
https://issues.redhat.com/browse/FDP-1135
- northd: Fix action parsing in build_lb_vip_actions(). (#[FDP-1095](https://issues.redhat.com//browse/FDP-1095))
https://issues.redhat.com/browse/FDP-1095
- northd: Fix missing tier related ACL flows. (#[FDP-1154](https://issues.redhat.com//browse/FDP-1154))
https://issues.redhat.com/browse/FDP-1154
- mac-cache: Fix expiration of active FDB entry due to skipped update. (#[FDP-1132](https://issues.redhat.com//browse/FDP-1132))
https://issues.redhat.com/browse/FDP-1132
- mac-cache: Fix expiration of active MAC binding due to skipped update. …
=> [release-4.16] OCPBUGS-54204: Update OVN to FDP25.A.1 24.03.5-40.

Dockerfile.base
Open vSwitch 3.1 is EoL upstream and so the support of this version in FDP is limited.  To ensure timely bug fix delivery for OCP 4.14+ we need to upgrade to the current LTS stream, which is Open vSwitch 3.3. It will be fully supported for much longer.
Consolidation of versions used across releases of OpenShift will also reduce pressure on QE teams allowing to drop older releases not used by any products.
We're moving RHCOS to this version as well in https://github.com/openshift/os/pull/1774, and we should keep the versions in the container and on the host in sync.  The exact build in this PR is the one that is currently used in OCP 4.16.
The plan is to get this into 4.15 and then backport to 4.14.
=> OCPBUGS-53384: [release-4.15] Dockerfile.base: bump OVS version to 3.3

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Pod to node isn't required because its match is based on address sets and not cluster networks.
(cherry picked from commit 27033e321c7e881a2a5a356b062ceee796b7d50d)
=> OCPBUGS-54671: EIP no reroute: allow multiple entries for pod to pod and pod to join

Dockerfile.base
This new version provides configuration flexibility for `openvswitch-ipsec` systemd service which enables OCP to run `ovs-monitor-ipsec` as a service on host instead of running it inside a container.
This PR as such only bumps OVS version to `3.5.0-0.9`, so it doesn't have any harm in merging it. 
The changes https://github.com/openshift/cluster-network-operator/pull/2662, https://github.com/openshift/machine-config-operator/pull/4878 in the PRs get `openvswitch-ipsec` systemd service running on the host and OVN uses it to configure IPsec for east west traffic. 
Until these two PRs are merged, CNO would just continue to use `ovs-monitor-ipsec` process running in the `ovn-ipsec-host` pod container.
=> CORENET-5371: Dockerfile: Bump OVS version to 3.5.0-0.9

Dockerfile.base
Bump ovn and ovs to latest patch releases for their major.minor version to address image grading issues.
=> OCPBUGS-55950: Bump ovs and ovn to latest patch releases

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy_test.go
Fixes a null pointer exception when network policy port has no protocol. If the protocol is missing in the network policy port definition, it should be assumed to be TCP.
(cherry picked from commit bc7e86e468a30200e5867aaf7904429d3f8948ea)
Clean cherry-pick.
=> [release-4.17] OCPBUGS-52480: Handles unspecified protocol in network policy port

Dockerfile.base
This contains the following relevant changes:
- controller: Fix active mac-binding refresh for IPv6.
- controller: Send ARP/ND for stale mac_bindings entries. (#[FDP-1135](https://issues.redhat.com//browse/FDP-1135)) https://issues.redhat.com/browse/FDP-1135
- northd: Fix action parsing in build_lb_vip_actions(). (#[FDP-1095](https://issues.redhat.com//browse/FDP-1095)) https://issues.redhat.com/browse/FDP-1095
- northd: Fix missing tier related ACL flows. (#[FDP-1154](https://issues.redhat.com//browse/FDP-1154)) https://issues.redhat.com/browse/FDP-1154
- mac-cache: Fix expiration of active FDB entry due to skipped update. (#[FDP-1132](https://issues.redhat.com//browse/FDP-1132)) https://issues.redhat.com/browse/FDP-1132
- mac-cache: Fix expiration of active MAC binding due to skipped …
=> OCPBUGS-56419: Update to FDP25.A.1 24.03.5-40.

Dockerfile.base
Change log since 24.09.2-41:
```
* Tue May 06 2025 Mark Michelson <mmichels@redhat.com> - 24.09.2-69
- northd: Set REGBIT_CONNTRACK_COMMIT earlier. (#FDP-1321) [Upstream: f8d6d7b46322d83bbaaacb6970ff15085dd31fcc]
* Tue Apr 29 2025 Ales Musil <amusil@redhat.com> - 24.09.2-68
- contoller, northd: Limit number of claims for virtual ports. (#FDP-443) [Upstream: c2d34d96ba24dea60d843d633b3794ef3be11146]
* Tue Apr 29 2025 Ales Musil <amusil@redhat.com> - 24.09.2-67
- controller: Remove only commited virtual port binding requests. [Upstream: a99aa6e2f08c4d34194fae44e0f3068dd8eaa700]
* Tue Apr 29 2025 Ales Musil <amusil@redhat.com> - 24.09.2-66
- inc-engine: Adjust the force recompute API. (#FDP-753) [Upstream: f0d9df0259f29b817d345f4b77cd1548618225f8]
* Thu Apr 24 2025 Felix Huettner …
```
=> OCPBUGS-52462: Bump OVN to 24.09.2-69.el9fdp

Dockerfile.base
This contains the following relevant changes:
- controller: Fix active mac-binding refresh for IPv6.
- controller: Send ARP/ND for stale mac_bindings entries. (#[FDP-1135](https://issues.redhat.com//browse/FDP-1135)) https://issues.redhat.com/browse/FDP-1135
- northd: Fix action parsing in build_lb_vip_actions(). (#[FDP-1095](https://issues.redhat.com//browse/FDP-1095)) https://issues.redhat.com/browse/FDP-1095
- northd: Fix missing tier related ACL flows. (#[FDP-1154](https://issues.redhat.com//browse/FDP-1154)) https://issues.redhat.com/browse/FDP-1154
- mac-cache: Fix expiration of active FDB entry due to skipped update. (#[FDP-1132](https://issues.redhat.com//browse/FDP-1132)) https://issues.redhat.com/browse/FDP-1132
- mac-cache: Fix expiration of active MAC binding due to skipped …
=> OCPBUGS-56420: Update to FDP25.A.1 24.03.5-40.

Dockerfile.base
This moves ovs from 2.17 in the container image to 3.1 matching RHCOS as used since Feb 2024, see https://issues.redhat.com/browse/OCPBUGS-22701
Regression testing only, no specific functional fixes
=> OCPBUGS-55951: Bump ovn and ovs to latest 23.06 and 3.1 respectively

go-controller/pkg/ovn/egressfirewall.go
(cherry picked from commit ab00a4ba29e181356f826d89a56f3bda186d68ee)
=> OCPBUGS-56812: egressfirewall: avoid nil dereference on node delete

go-controller/pkg/clustermanager/node/node_allocator.go, go-controller/pkg/clustermanager/node/node_allocator_test.go, go-controller/pkg/clustermanager/node/subnet_allocator.go, go-controller/pkg/clustermanager/node/subnet_allocator_test.go, go-controller/pkg/util/net.go
When hybrid overlay clustersubnets is undefined, the hybrid overlay node subnet allocation is not managed by ovn-k.
But we need to  ensures hybrid overlay node subnets are properly marked as allocated in the cluster subnet allocator when they overlap with the cluster subnet ranges, preventing potential subnet allocation conflicts.
The fix helps maintain proper subnet allocation tracking when hybrid overlay nodes use subnets that fall within the cluster's subnet ranges.
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/192f575d351acc9bc049db213bf65f25a315e2c6)
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/13fb9bf54f97136e6eb5bba19240ce58dca2bf94) …
=> [release-4.16] OCPBUGS-55282: Fix hybrid overlay node subnets collision with cluster subnets

go-controller/pkg/libovsdb/util/router.go, go-controller/pkg/libovsdb/util/router_test.go, go-controller/pkg/util/kube.go
Taking over from https://github.com/openshift/ovn-kubernetes/pull/2637, where tide is stuck.
Cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2578
Replacing https://github.com/openshift/ovn-kubernetes/pull/2630, where unit tests were failing. 
No conflicts, but I had to apply the following change to make the patch compatible with 4.16 code:
```
--- a/go-controller/pkg/libovsdb/util/router_test.go
+++ b/go-controller/pkg/libovsdb/util/router_test.go
@@ -220,7 +220,7 @@ func TestCreateDefaultRouteToExternal(t *testing.T) {
tc.preTestAction()
}
-                       if err = CreateDefaultRouteToExternal(nbClient, ovnClusterRouterName, gwRouterName); err != nil {
+                       if err = CreateDefaultRouteToExternal(nbClient, nodeName); err != nil { …
```
=> [release-4.16] OCPBUGS-57396: Fix predicate for cluster subnet route to gateway router

Dockerfile, Dockerfile.base
Dockerfile: Unpin OVS patch versions and consume the latest from FDP.
OVN-Kubernetes is always lagging behind on the version of OVS it pins.
This is causing a lot of trouble with keeping up with bug fixes and
especially CVE fixes on older branches, resulting in scanners constantly
flagging this image with poor security grades.
OVS package inside the container is responsible for the following:
1. Command line utilities to talk with OVS from the host.
2. ovsdb-server processes serving OVN databases.
3. ovs-monitor-ipsec script for managing ipsec configuration on
OVN tunnels.
These tools/programs are not changing that much between patch releases,
and bug fix releases in FDP are going through a lot of testing before
becoming available in the repo.  So, benefits of timely delivery of bug
and …
=> OCPBUGS-58160: Unpin OVS patch versions, move to ovs 3.5

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/openflow_manager.go
Pass `hostSubnets` to `commonFlows` to fix default network -> localnet
We need to pass the host subnets when adding the flows at priority 102 that allow connections from pods in the default network to pods in a localnet attached to breth0 on the same node. We were previously passing the pod subnets for the node as IP dest, which is not correct:
```
sh-5.2# ovs-ofctl dump-flows breth0 | grep y=102
cookie=0xdeff105, duration=3418.445s, table=0, n_packets=0, n_bytes=0, idle_age=3418, priority=102,ip,in_port=2,dl_src=02:42:ac:12:00:04,nw_dst=10.244.0.0/24 actions=ct(commit,zone=64000,exec(load:0x1->NXM_NX_CT_MARK[])),NORMAL
```
We're now adding one such flow for each host subnet found on the node:
```
sh-5.2# ovs-ofctl dump-flows breth0 | grep y=102
cookie=0xdeff105, duration=374.624s, …
```
=> OCPBUGS-59381:[release-4.17] Fix default network -> localnet

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/external_ids_syncer/logical_router_policy/logical_router_policy_sync.go, go-controller/pkg/ovn/external_ids_syncer/logical_router_policy/logical_router_policy_sync_test.go, go-controller/pkg/ovn/external_ids_syncer/nat/nat_sync.go, go-controller/pkg/ovn/external_ids_syncer/nat/nat_sync_test.go
this is an out-of-band PR from our branch sync process in order to expedite a customer regression fix.
These commits will all end up appearing twice as they will also come in via the normal 4.19->4.18 branch sync.
=> [release-4.18] OCPBUGS-59531: EgressIP: fix startup syncer

Dockerfile.base
Bump OVN to 25.03.0-73.el9fdp for OCP and 25.03.1-36.el9s for OKD.
Using a different version for OKD as it is currently the only one available.
This is a list of relevant bug fixes and new core OVN features picked up by the bump:
```
Bug fixes:
==========
- pinctrl: Fix missing garp.
- binding: Avoid 100% CPU when postponing claims.
- northd: Sample_Collector.set_ids can actually be 32-bit values.
New Features:
=============
- Added support to choose selection methods - dp_hash or
hash (with specified hash fields) for ECMP routes
while choosing nexthop.
- Added support for Spine-Leaf topology of logical switches by adding
a new LSP type 'switch' that can directly connect two logical switches.
Supported for both distributed and transit switches.
- SSL/TLS:
* TLSv1 and TLSv1.1 protocols are …
```
=> NO-JIRA: Bump OVN to 25.03

Dockerfile.base
OCPBUGS-61065: OVNK downstream with DPF failing to run upstream script
Fix missing ovndb-raft-functions.sh dependency in DPU service image
Add missing ovndb-raft-functions.sh script to Dockerfile.base as it's required
by the upstream ovnkube.sh script used by DPU service in OCP downstream images.
=> OCPBUGS-61065: Adding ovndb-raft-functions.sh to ovnk image

docs/getting-started/configuration.md, go-controller/pkg/node/default_node_network_controller.go, go-controller/pkg/node/egress_service_test.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/util/iptables.go
Global forwarding works differently for IPv6:
conf/all/forwarding - BOOLEAN
Enable global IPv6 forwarding between all interfaces.
IPv4 and IPv6 work differently here; e.g. netfilter must be used
to control which interfaces may forward packets and which not.
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
It is not possible to configure the IPv6 forwarding per interface by setting the net.ipv6.conf.<ifname>.forwarding sysctl. Instead, the opposite approach is required where the global forwarding is enabled and an iptables policy is added to restrict it by default.
To ensure consistent behavior between IPv4/IPv6 and limit the forwarding scope for IPv4 networks this commit configures the default DROP policy for all configured IP families. …
=> [release-4.16] OCPBUGS-60079: Always enable global IPv6 forwarding

.github/workflows/test.yml, go-controller/pkg/node/bridgeconfig/bridgeflows.go, test/e2e/multihoming.go, test/e2e/multihoming_external_router_utils.go, test/e2e/multihoming_utils.go, test/e2e/util.go
No conflicts.
Upstream: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5480
Downstream master: https://github.com/openshift/ovn-kubernetes/pull/2750
=> OCPBUGS-61453: [4.20] allow default network -> localnet on the same node for any localnet subnet

.github/workflows/test.yml, go-controller/pkg/node/bridgeconfig/bridgeflows.go, test/e2e/multihoming.go, test/e2e/multihoming_external_router_utils.go, test/e2e/multihoming_utils.go, test/e2e/util.go
Upstream: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5480
Downstream master: https://github.com/openshift/ovn-kubernetes/pull/2750
4.20: https://github.com/openshift/ovn-kubernetes/pull/2751
For the 4.18 backport, we'll need to wait for ~https://github.com/openshift/ovn-kubernetes/pull/2745~ https://github.com/openshift/ovn-kubernetes/pull/2663 to merge first.
=> OCPBUGS-61454: [4.19] allow default network -> localnet on the same node for any localnet subnet
